### ISSUE TITLE
PDFs are failing to build

### ISSUE THREAD

**Issue by singingwolfboy** [rtfd/readthedocs.org#1103]
From https://readthedocs.org/builds/flask-dance/2010187/:

```
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/flask-dance/envs/latest/bin/sphinx-build", line 11, in <module>
    sys.exit(main())
  File "/home/docs/checkouts/readthedocs.org/user_builds/flask-dance/envs/latest/local/lib/python2.7/site-packages/sphinx/__init__.py", line 49, in main
    from sphinx import cmdline
ImportError: cannot import name cmdline
```

Using the wrong version of sphinx, perhaps? My project [does not specify a specific version of sphinx in the requirements file](https://github.com/singingwolfboy/flask-dance/blob/master/dev-requirements.txt), so it should be just using whatever is on readthedocs by default.

**Comment by ericholscher** [comment]
Seems this got fixed. Closing the issue.
