### ISSUE TITLE
ImportError: No module named sphinx_rtd_theme on readthedocs.org

### ISSUE THREAD

**Issue by groovecoder** [rtfd/readthedocs.org#1111]
[We're using `sphinx_rtd_theme` when `READTHEDOCS` = `True`](https://github.com/codesy/codesy/blob/master/docs/conf.py#L100-L108), just like [the docs say](https://docs.readthedocs.org/en/latest/faq.html?highlight=theme#how-do-i-change-behavior-for-read-the-docs).

But, about 2 months ago, [our doc builds](https://readthedocs.org/builds/codesy/) started failing with this stacktrace:

```
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/codesy/envs/latest/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 253, in main
    warningiserror, tags, verbosity, parallel)
  File "/home/docs/checkouts/readthedocs.org/user_builds/codesy/envs/latest/local/lib/python2.7/site-packages/sphinx/application.py", line 107, in __init__
    confoverrides or {}, self.tags)
  File "/home/docs/checkouts/readthedocs.org/user_builds/codesy/envs/latest/local/lib/python2.7/site-packages/sphinx/config.py", line 229, in __init__
    execfile_(filename, config)
  File "/home/docs/checkouts/readthedocs.org/user_builds/codesy/envs/latest/local/lib/python2.7/site-packages/sphinx/util/pycompat.py", line 105, in execfile_
    exec code in _globals
  File "conf.py", line 105, in <module>
    import sphinx_rtd_theme
ImportError: No module named sphinx_rtd_theme

Exception occurred:
  File "conf.py", line 105, in <module>
    import sphinx_rtd_theme
ImportError: No module named sphinx_rtd_theme
The full traceback has been saved in /tmp/sphinx-err-uYEvVf.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://bitbucket.org/birkenfeld/sphinx/issues/>. Thanks!
```

So, [we removed the `on_rtd` logic](https://github.com/codesy/codesy/pull/84/files) and that seemed to fix us up.

Was this an expected readthedocs.org change that we missed? Or is this a bug?

**Comment by ericholscher** [comment]
Seems this got fixed. Closing the issue.
