### ISSUE TITLE
Build Errors in RTD Installation in a VM

### ISSUE THREAD

**Issue by MonamiB** [rtfd/readthedocs.org#1206]
I have an RTD instance running in a virtualenv within a VM. I am running the server on the VM's public IP instead of the default 127.0.0.1 or 0.0.0.0.

    ./ manage.py runserver [VM Public IP]:8000

This allows me to access the RTD dash from anywhere in my LAN. The VM can access my Git repo with the checkouts and checkins working fine from within the box. However, when I run the build from the dash (from my laptop and not the VM) it seems to go into a loop before throwing the following errors. I can see there's some error with Elastisearch and that some of it is still building on the localhost 127.0.0.1 instead of the public IP, but have no idea how or where to fix it. Appreciate any help.

ERROR TRACE 1:

    HttpClientError: Client Error 401: http://localhost:8000/api/v1/build/
    [26/Mar/2015 02:59:09] INFO [projects.tasks:132] (Build) [project_name:] Build finished
    [26/Mar/2015 02:59:09] INFO [core.utils:23] Running mkdir -p /home/monami.b/backup_testdocs-virtualenv/checkouts/readthedocs.org/user_builds/[project_name]/translations on app servers
    [26/Mar/2015 02:59:09] INFO [core.utils:23] Running ln -nsf /home/monami.b/backup_testdocs-    virtualenv/checkouts/readthedocs.org/user_builds/[project_name]/rtd-builds  /home/monami.b/backup_testdocs-virtualenv/checkouts/readthedocs.org/user_builds/[project_name]/translations/en on app servers
    [26/Mar/2015 02:59:09] INFO [core.utils:23] Running rm -f /home/monami.b/backup_testdocs-virtualenv/checkouts/readthedocs.org/user_builds/[project_name]/single_version on app servers

ERROR TRACE 2:

    HttpClientError: Client Error 401: http://localhost:8000/api/v1/build/5/
    [26/Mar/2015 02:59:09] "POST /api/v1/build/ HTTP/1.1" 401 0
    [26/Mar/2015 02:59:09] ERROR [projects.tasks:587] (Build) [project_name:latest] Unable to post a new build
    Traceback (most recent call last):
      File "/home/monami.b/backup_testdocs-virtualenv/checkouts/readthedocs.org/readthedocs/projects/tasks.py", line 583, in record_pdf
      exit_code=pdf_exit,
      File "/usr/local/lib/python2.7/dist-packages/slumber/__init__.py", line 146, in post
    resp = self._request("POST", data=data, files=files, params=kwargs)
      File "/usr/local/lib/python2.7/dist-packages/slumber/__init__.py", line 108, in _request
    raise exceptions.HttpClientError("Client Error %s: %s" % (resp.status_code, url), response=resp, content=resp.content)
    HttpClientError: Client Error 401: http://localhost:8000/api/v1/build/
    [26/Mar/2015 02:59:09] INFO [projects.tasks:132] (Build) [project_name:] Build finished

ERROR TRACE 3:

    MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=9200): Max retries exceeded with url: /readthedocs/project/2 (Caused by ProtocolError('Connection aborted.', error(111, 'Connection refused')))
    [26/Mar/2015 02:59:09] INFO [urllib3.connectionpool:203] Starting new HTTP connection (13): 127.0.0.1
    [26/Mar/2015 02:59:09] WARNING [urllib3.connectionpool:613] Retrying (Retry(total=2,  connect=None, read=None, redirect=None)) after connection broken by 'ProtocolError('Connection aborted.', error(111, 'Connection refused'))': /readthedocs/project/2
    [26/Mar/2015 02:59:09] INFO [urllib3.connectionpool:203] Starting new HTTP connection (14): 127.0.0.1
    [26/Mar/2015 02:59:09] WARNING [urllib3.connectionpool:613] Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ProtocolError('Connection aborted.', error(111, 'Connection refused'))': /readthedocs/project/2
    [26/Mar/2015 02:59:09] INFO [urllib3.connectionpool:203] Starting new HTTP connection (15): 127.0.0.1
    [26/Mar/2015 02:59:09] WARNING [urllib3.connectionpool:613] Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ProtocolError('Connection aborted.', error(111, 'Connection refused'))': /readthedocs/project/2
    [26/Mar/2015 02:59:09] INFO [urllib3.connectionpool:203] Starting new HTTP connection (16): 127.0.0.1
    [26/Mar/2015 02:59:09] WARNING [elasticsearch:68] PUT http://127.0.0.1:9200/readthedocs/project/2 [status:N/A request:0.002s]
    Traceback (most recent call last):
    File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_urllib3.py", line 44, in perform_request
    response = self.pool.urlopen(method, url, body, **kw)
    File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 617, in urlopen
    release_conn=release_conn, **response_kw)
    File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 617, in urlopen
    release_conn=release_conn, **response_kw)
    File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 617, in urlopen
    release_conn=release_conn, **response_kw)
    File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 597, in urlopen
    _stacktrace=sys.exc_info()[2])
    File "/usr/local/lib/python2.7/dist-packages/urllib3/util/retry.py", line 271, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
    MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=9200): Max retries exceeded with url: /readthedocs/project/2 (Caused by ProtocolError('Connection aborted.', error(111, 'Connection refused')))
    [26/Mar/2015 02:59:09] "POST /dashboard/import/manual/ HTTP/1.1" 302 0
    ----------------------------------------
    Exception happened during processing of request from ('172.20.229.18', 45701)
    Unhandled exception in thread started by <function wrapper at 0x1f14050>
    Traceback (most recent call last):
    File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 96, in wrapper
    et, ev, tb = sys.exc_info()
    AttributeError: 'NoneType' object has no attribute 'exc_info'

**Comment by agjohnson** [comment]
You should make sure you are pointing the API host and production domain to the correct IP address. I'm assuming you don't want 127.0.0.1, unless you are proxying the port to the vm.

**Comment by destroyerofbuilds** [comment]
@MonamiB, following @agjohnson's comment, are you able to resolve the exceptions?

**Comment by agjohnson** [comment]
Closing due to inactivity.
