### ISSUE TITLE
TemplateDoesNotExist: doc_builder/conf.py.tmpl

### ISSUE THREAD

**Issue by sujaymansingh** [rtfd/readthedocs.org#1251]
I'm trying to run a local version of `readthedocs` but my builds fail with the following.

```
[05/May/2015 02:56:16] ERROR [projects.tasks:129] (Build) [crawl-documents-client:stable] Top-level Build Failure
Traceback (most recent call last):
  File "./projects/tasks.py", line 113, in update_docs
    build_results = build_docs(version, force, pdf, man, epub, dash, search, localmedia)
  File "/opt/env/documentation/local/lib/python2.7/site-packages/celery/app/task.py", line 329, in __call__
    return self.run(*args, **kwargs)
  File "./projects/tasks.py", line 398, in build_docs
    html_builder.append_conf()
  File "./doc_builder/backends/sphinx.py", line 115, in append_conf
    rtd_string = template_loader.get_template('doc_builder/conf.py.tmpl').render(rtd_ctx)
  File "/opt/env/documentation/local/lib/python2.7/site-packages/django/template/loader.py", line 138, in get_template
    template, origin = find_template(template_name)
  File "/opt/env/documentation/local/lib/python2.7/site-packages/django/template/loader.py", line 131, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: doc_builder/conf.py.tmpl
```

Any idea why it can't find the `doc_builder/conf.py.tmpl` file? I have not touched any template config items.

These are the only settings that I have overrided (based upon `sqlite.py`)

```python
from settings.sqlite import *  # noqa

ALLOW_PRIVATE_REPOS = True

ACCOUNT_EMAIL_VERIFICATION = "none"

STATICFILES_DIRS = ("/opt/static",)

SLUMBER_API_HOST = "http://localhost"

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": "/opt/database/readthedocs.db",
    }
}
```

I am running my app using `uwsgi`. Will that make a difference?

**Comment by agjohnson** [comment]
You'll find `doc_builder/conf.py.tmpl` at:
https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/doc_builder/templates/doc_builder/conf.py.tmpl

This is more than likely a path issue, possibly introduced with how you are running uwsgi. I'd introspect via pdb to see what paths are actually set to before the failure
