### ISSUE TITLE
"No module named recommonmark.parser" when building docs

### ISSUE THREAD

**Issue by fjarri** [rtfd/readthedocs.org#1254]
I'm getting the following error when trying to build docs for my [project](https://github.com/fjarri/reikna):

    Traceback (most recent call last):
      File "/home/docs/checkouts/readthedocs.org/user_builds/reikna/envs/latest/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 244, in main
        opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
      File "/home/docs/checkouts/readthedocs.org/user_builds/reikna/envs/latest/local/lib/python2.7/site-packages/sphinx/application.py", line 126, in __init__
        confoverrides or {}, self.tags)
      File "/home/docs/checkouts/readthedocs.org/user_builds/reikna/envs/latest/local/lib/python2.7/site-packages/sphinx/config.py", line 277, in __init__
        execfile_(filename, config)
      File "/home/docs/checkouts/readthedocs.org/user_builds/reikna/envs/latest/local/lib/python2.7/site-packages/sphinx/util/pycompat.py", line 128, in execfile_
        exec_(code, _globals)
      File "/home/docs/checkouts/readthedocs.org/user_builds/reikna/envs/latest/local/lib/python2.7/site-packages/six.py", line 672, in exec_
        exec("""exec _code_ in _globs_, _locs_""")
      File "<string>", line 1, in <module>
      File "conf.py", line 260, in <module>
        from recommonmark.parser import CommonMarkParser
    ImportError: No module named recommonmark.parser

([The full build log](https://readthedocs.org/builds/reikna/2712412/))

I can build the docs locally without any problems using the same Sphinx version, and without having ``recommonmark`` installed. Judging by the RtD sources, it adds this import in the ``conf.py`` file, but for some reason does not install the package in the virtual environment.

**Comment by ericholscher** [comment]
Bah, sorry about that. Will fix it.

**Comment by ericholscher** [comment]
Should be fixed now.

**Comment by ericholscher** [comment]
Seems like it was a busted deploy. The deploy has the code for installing the recommonmark module, but it wasn't getting run properly.

**Comment by fjarri** [comment]
That was quick, thank you! Works fine now.

**Comment by NYKevin** [comment]
I'm seeing this in my project now.  See [this build](https://readthedocs.org/builds/nbtparse/2974593/).
