### ISSUE TITLE
Postgres not found

### ISSUE THREAD

**Issue by evilstickman** [rtfd/readthedocs.org#1266]
I have postgres and psycopg installed on my machine, and both are accessible from within python. However, I am not able to use your code (through your installation instructions) to get the test data running. When I run the following in windows:

`python manage.py syncdb`

I am given the following stacktrace:
```
C:\Users\Matt\Dropbox\Writing\backand\documentation\checkouts\readthedocs.org\re
adthedocs>python manage.py syncdb
Traceback (most recent call last):
  File "manage.py", line 13, in <module>
    execute_from_command_line(sys.argv)
  File "c:\python27\lib\site-packages\django\core\management\__init__.py", line
399, in execute_from_command_line
    utility.execute()
  File "c:\python27\lib\site-packages\django\core\management\__init__.py", line
392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "c:\python27\lib\site-packages\django\core\management\__init__.py", line
261, in fetch_command
    commands = get_commands()
  File "c:\python27\lib\site-packages\django\core\management\__init__.py", line
107, in get_commands
    apps = settings.INSTALLED_APPS
  File "c:\python27\lib\site-packages\django\conf\__init__.py", line 54, in __ge
tattr__
    self._setup(name)
  File "c:\python27\lib\site-packages\django\conf\__init__.py", line 49, in _set
up
    self._wrapped = Settings(settings_module)
  File "c:\python27\lib\site-packages\django\conf\__init__.py", line 128, in __i
nit__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "c:\python27\lib\site-packages\django\utils\importlib.py", line 40, in im
port_module
    __import__(name)
  File "C:\Users\Matt\Dropbox\Writing\backand\documentation\checkouts\readthedoc
s.org\readthedocs\settings\__init__.py", line 1, in <module>
    postgres.py
NameError: name 'postgres' is not defined
```

Is there a dependency that I am missing? It seems that if postgres is installed on my system, then this should not be an issue. Please advise as to how to resolve this error.

**Comment by ericholscher** [comment]
This is likely a windows issue. We have a symlink to postgres.py that might not be working. We don't support running Read the Docs on Windows, so I'm closing this. You would likely find other issues with symlinks, as we use them heavily in our code base.
