### ISSUE TITLE
Encoding problem with installation log

### ISSUE THREAD

**Issue by paternal** [rtfd/readthedocs.org#1320]
When compiling several of my projects ([example](https://readthedocs.org/builds/papersize/2911373/)), I always see the following message.

~~~
install
-----

Traceback (most recent call last):
  File "setup.py", line 75, in <module>
    zip_safe = True,
  File "/usr/lib/python3.4/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/papersize/envs/test/lib/python3.4/site-packages/setuptools/dist.py", line 239, in __init__
    self.fetch_build_eggs(attrs.pop('setup_requires'))
  File "/home/docs/checkouts/readthedocs.org/user_builds/papersize/envs/test/lib/python3.4/site-packages/setuptools/dist.py", line 263, in fetch_build_eggs
    parse_requirements(requires), installer=self.fetch_build_egg
  File "/home/docs/checkouts/readthedocs.org/user_builds/papersize/envs/test/lib/python3.4/site-packages/pkg_resources.py", line 568, in resolve
    dist = best[req.key] = env.best_match(req, self, installer)
  File "/home/docs/checkouts/readthedocs.org/user_builds/papersize/envs/test/lib/python3.4/site-packages/pkg_resources.py", line 806, in best_match
    return self.obtain(req, installer) # try and download/install
  File "/home/docs/checkouts/readthedocs.org/user_builds/papersize/envs/test/lib/python3.4/site-packages/pkg_resources.py", line 818, in obtain
    return installer(requirement)
  File "/home/docs/checkouts/readthedocs.org/user_builds/papersize/envs/test/lib/python3.4/site-packages/setuptools/dist.py", line 313, in fetch_build_egg
    return cmd.easy_install(req)
  File "/home/docs/checkouts/readthedocs.org/user_builds/papersize/envs/test/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 606, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/home/docs/checkouts/readthedocs.org/user_builds/papersize/envs/test/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 636, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/home/docs/checkouts/readthedocs.org/user_builds/papersize/envs/test/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 822, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/home/docs/checkouts/readthedocs.org/user_builds/papersize/envs/test/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 1084, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/home/docs/checkouts/readthedocs.org/user_builds/papersize/envs/test/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 1069, in run_setup
    run_setup(setup_script, args)
  File "/home/docs/checkouts/readthedocs.org/user_builds/papersize/envs/test/lib/python3.4/site-packages/setuptools/sandbox.py", line 69, in run_setup
    lambda: execfile(
  File "/home/docs/checkouts/readthedocs.org/user_builds/papersize/envs/test/lib/python3.4/site-packages/setuptools/sandbox.py", line 120, in run
    return func()
  File "/home/docs/checkouts/readthedocs.org/user_builds/papersize/envs/test/lib/python3.4/site-packages/setuptools/sandbox.py", line 71, in <lambda>
    {'__file__':setup_script, '__name__':'__main__'}
  File "/home/docs/checkouts/readthedocs.org/user_builds/papersize/envs/test/lib/python3.4/site-packages/setuptools/compat.py", line 89, in execfile
    source = f.read()
  File "/home/docs/checkouts/readthedocs.org/user_builds/papersize/envs/test/lib/python3.4/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 87: ordinal not in range(128)
~~~

After some research, I think that the problem is that `readthedocs` expect output to be in ASCII encoding, whereas my setup prints UTF8 encoded characters (in which case it may be related to #917, which is claimed to have been solved ten months ago, but did not solve my issue).

If my analysis is correct, either my setup file should return ASCII characters (which is not, as far as I know, documented, and I do not know how to do this, since I do not know what is printed to standard output), or readthedocs should be less strict about installation output, for example by adding  ``errors="replace"`` to the open function used to read (and log) standard output.

Cheers,
-- Louis

**Comment by paternal** [comment]
I have installed the package at home, in verbose mode, looking for *weird* characters, but every characters is ASCII. Thus I do not understand what is happening.

**Comment by paternal** [comment]
I eventually locally installed readthedocs.org, to reproduce the bug, (following [these instructions](http://docs.readthedocs.org/en/latest/install.html) but:
- either I run it in a virtualenv, and my documentation is compiled using python2, ignoring the "Python interpreter" option;
- or I run it outside a virtualenv, and compilation hangs up.

These bug is preventing me from [building other documentation](https://readthedocs.org/builds/dummypdf/2921968). A workaround would be for me to mock the module causing the problem.

**Comment by gregmuellegger** [comment]
I tried this now with a few different constellations locally but I wasn't able to reproduce. We likely need to investigate this on the build servers.

**Comment by ericholscher** [comment]
We have a new build system that should fix this issue.

**Comment by paternal** [comment]
[It works !](https://readthedocs.org/projects/dummypdf/builds/3265399/) Thanks.
