### ISSUE TITLE
Python 3 doc builds failing when installing dependencies

### ISSUE THREAD

**Issue by takluyver** [rtfd/readthedocs.org#1394]
Both the `doc_builder` and the `requirements` steps show errors like this:

```
The directory '/root/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
You are using pip version 7.0.1, however version 7.1.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
The directory '/root/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Exception:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/jupyter-core/envs/latest/lib/python3.4/site-packages/pip/basecommand.py", line 223, in main
    status = self.run(options, args)
  File "/home/docs/checkouts/readthedocs.org/user_builds/jupyter-core/envs/latest/lib/python3.4/site-packages/pip/commands/install.py", line 291, in run
    wb.build(autobuilding=True)
  File "/home/docs/checkouts/readthedocs.org/user_builds/jupyter-core/envs/latest/lib/python3.4/site-packages/pip/wheel.py", line 704, in build
    self.requirement_set.prepare_files(self.finder)
  File "/home/docs/checkouts/readthedocs.org/user_builds/jupyter-core/envs/latest/lib/python3.4/site-packages/pip/req/req_set.py", line 317, in prepare_files
    functools.partial(self._prepare_file, finder))
  File "/home/docs/checkouts/readthedocs.org/user_builds/jupyter-core/envs/latest/lib/python3.4/site-packages/pip/req/req_set.py", line 304, in _walk_req_to_install
    more_reqs = handler(req_to_install)
  File "/home/docs/checkouts/readthedocs.org/user_builds/jupyter-core/envs/latest/lib/python3.4/site-packages/pip/req/req_set.py", line 439, in _prepare_file
    req_to_install.populate_link(finder, self.upgrade)
  File "/home/docs/checkouts/readthedocs.org/user_builds/jupyter-core/envs/latest/lib/python3.4/site-packages/pip/req/req_install.py", line 244, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/home/docs/checkouts/readthedocs.org/user_builds/jupyter-core/envs/latest/lib/python3.4/site-packages/pip/req/req_install.py", line 256, in link
    self._link = self._wheel_cache.cached_wheel(link, self.name)
  File "/home/docs/checkouts/readthedocs.org/user_builds/jupyter-core/envs/latest/lib/python3.4/site-packages/pip/wheel.py", line 62, in cached_wheel
    self._cache_dir, link, self._format_control, package_name)
  File "/home/docs/checkouts/readthedocs.org/user_builds/jupyter-core/envs/latest/lib/python3.4/site-packages/pip/wheel.py", line 123, in cached_wheel
    wheel_names = os.listdir(root)
PermissionError: [Errno 13] Permission denied: '/root/.cache/pip/wheels/c9/b4/72/4de2802cbc4bfd82f938ff92015e1b42f01131583675ab4d00'
```

**Comment by minrk** [comment]
This is presumably due to a recent bump of pip to 7.0, which builds and caches wheels by default, but the build user doesn't have permission to write to the cache dir. The fix is presumably either:

1. disable the wheel-building step (`pip install --no-cache-dir`)
2. make the cache dir a path that's writable (`pip install --cache-dir=/somewhere/writable`)

**Comment by minrk** [comment]
Actually, this appears to be a bug in pip 7. Pip has a check for disabling the http cache when the cache dir isn't writable, but no similar check for the wheel cache.

**Comment by minrk** [comment]
Should be fixed by pypa/pip#2951 once that gets into a release.

**Comment by agjohnson** [comment]
Thanks for the report and the pip patch. I'll watch for the next release and get those in.

The underlying issue I'll poke around to solve is why py3.4 virtualenvs are still considering `/root` as the build user's home path. This shouldn't be the case. Overriding the option should be enough, but this might point to something more systemic.

**Comment by agjohnson** [comment]
I have deployed a fix to env vars passed to pip/etc to our servers. It seems the newer pip surfaced the issue for us, but was ultimately how the process environment was established.

**Comment by takluyver** [comment]
Thanks! I've started a build to check that it succeeds now.

**Comment by takluyver** [comment]
And indeed it does :-)

**Comment by takluyver** [comment]
This issue seems to be back today:

https://readthedocs.org/builds/astsearch/3070812/

**Comment by agjohnson** [comment]
It is, looks like i provisioned the servers with a branch lacking this patch. Fixing it now.

**Comment by agjohnson** [comment]
Reprovisioned with the patch applied, @takluyver your docs seem to building now

**Comment by takluyver** [comment]
They are indeed. Thanks for the quick response!
