### ISSUE TITLE
Stale html documentation

### ISSUE THREAD

**Issue by Balooga** [rtfd/readthedocs.org#1459]
On a fresh install of RTD with a manual import from a HTTP git repository.  RTD generates the documentation the first time, even though the following error is displayed on stdout.

```
[20/Jul/2015 15:48:42] INFO [privacy.backends.syncers:18] Local Copy /users/lcrook/rtd/checkouts/readthedocs.org/user_builds/edm-v/artifacts/latest/mkdocs to /users/lcrook/rtd/checkouts/readthedocs.org/user_builds/edm-v/rtd-builds/latest
[20/Jul/2015 15:48:42] ERROR [projects.symlinks:27] (Build) [edm-v:latest] Failed to symlink cnames, Redis error.
Traceback (most recent call last):
  File "/users/lcrook/rtd/checkouts/readthedocs.org/readthedocs/projects/symlinks.py", line 25, in symlink_cnames
    cnames = redis_conn.smembers('rtd_slug:v1:%s' % version.project.slug)
  File "/users/lcrook/rtd/lib/python2.7/site-packages/redis/client.py", line 974, in smembers
    return self.execute_command('SMEMBERS', name)
  File "/users/lcrook/rtd/lib/python2.7/site-packages/redis/client.py", line 363, in execute_command
    connection.send_command(*args)
  File "/users/lcrook/rtd/lib/python2.7/site-packages/redis/connection.py", line 299, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/users/lcrook/rtd/lib/python2.7/site-packages/redis/connection.py", line 281, in send_packed_command
    self.connect()
  File "/users/lcrook/rtd/lib/python2.7/site-packages/redis/connection.py", line 229, in connect
    raise ConnectionError(self._error_message(e))
ConnectionError: Error 111 connecting localhost:6379. Connection refused.
[20/Jul/2015 15:48:42] INFO [core.utils:25] Running mkdir -p /users/lcrook/rtd/checkouts/readthedocs.org/user_builds/edm-v/translations on app servers
[20/Jul/2015 15:48:42] INFO [core.utils:25] Running ln -nsf /users/lcrook/rtd/checkouts/readthedocs.org/user_builds/edm-v/rtd-builds /users/lcrook/rtd/checkouts/readthedocs.org/user_builds/edm-v/translations/en on app servers
[20/Jul/2015 15:48:42] INFO [core.utils:25] Running rm -f /users/lcrook/rtd/checkouts/readthedocs.org/user_builds/edm-v/single_version on app servers
[20/Jul/2015 15:48:42] INFO [projects.tasks:836] (Build) [edm-v:] Updating static metadata
[20/Jul/2015 15:48:42] INFO [privacy.backends.syncers:18] Local Copy /users/lcrook/rtd/checkouts/readthedocs.org/user_builds/edm-v/metadata.json to /users/lcrook/rtd/checkouts/readthedocs.org/user_builds/edm-v/metadata.json
[20/Jul/2015 15:48:42] INFO [projects.tasks:740] (Build) [edm-v:latest] Creating ImportedFiles
[20/Jul/2015 15:48:42] INFO [projects.tasks:709] (Search Index) Sending Data: edm-v []
[20/Jul/2015 15:48:42] INFO [urllib3.connectionpool:203] Starting new HTTP connection (1): 127.0.0.1
[20/Jul/2015 15:48:42] WARNING [elasticsearch:82] PUT http://127.0.0.1:9200/readthedocs/project/24 [status:N/A request:0.004s]
Traceback (most recent call last):
  File "/users/lcrook/rtd/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 74, in perform_request
    response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)
  File "/users/lcrook/rtd/lib/python2.7/site-packages/urllib3/connectionpool.py", line 597, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/users/lcrook/rtd/lib/python2.7/site-packages/urllib3/util/retry.py", line 222, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/users/lcrook/rtd/lib/python2.7/site-packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/users/lcrook/rtd/lib/python2.7/site-packages/urllib3/connectionpool.py", line 349, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/opt/rh/python27/root/usr/lib64/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/opt/rh/python27/root/usr/lib64/python2.7/httplib.py", line 1007, in _send_request
    self.endheaders(body)
  File "/opt/rh/python27/root/usr/lib64/python2.7/httplib.py", line 969, in endheaders
    self._send_output(message_body)
  File "/opt/rh/python27/root/usr/lib64/python2.7/httplib.py", line 829, in _send_output
    self.send(msg)
  File "/opt/rh/python27/root/usr/lib64/python2.7/httplib.py", line 791, in send
    self.connect()
  File "/users/lcrook/rtd/lib/python2.7/site-packages/urllib3/connection.py", line 155, in connect
    conn = self._new_conn()
  File "/users/lcrook/rtd/lib/python2.7/site-packages/urllib3/connection.py", line 134, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/users/lcrook/rtd/lib/python2.7/site-packages/urllib3/util/connection.py", line 88, in create_connection
    raise err
ProtocolError: ('Connection aborted.', error(111, 'Connection refused'))
[20/Jul/2015 15:48:42] INFO [urllib3.connectionpool:203] Starting new HTTP connection (2): 127.0.0.1
[20/Jul/2015 15:48:42] WARNING [elasticsearch:82] PUT http://127.0.0.1:9200/readthedocs/project/24 [status:N/A request:0.001s]
Traceback (most recent call last):
  File "/users/lcrook/rtd/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 74, in perform_request
    response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)
  File "/users/lcrook/rtd/lib/python2.7/site-packages/urllib3/connectionpool.py", line 597, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/users/lcrook/rtd/lib/python2.7/site-packages/urllib3/util/retry.py", line 222, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/users/lcrook/rtd/lib/python2.7/site-packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/users/lcrook/rtd/lib/python2.7/site-packages/urllib3/connectionpool.py", line 349, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/opt/rh/python27/root/usr/lib64/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/opt/rh/python27/root/usr/lib64/python2.7/httplib.py", line 1007, in _send_request
    self.endheaders(body)
  File "/opt/rh/python27/root/usr/lib64/python2.7/httplib.py", line 969, in endheaders
    self._send_output(message_body)
  File "/opt/rh/python27/root/usr/lib64/python2.7/httplib.py", line 829, in _send_output
    self.send(msg)
  File "/opt/rh/python27/root/usr/lib64/python2.7/httplib.py", line 791, in send
    self.connect()
  File "/users/lcrook/rtd/lib/python2.7/site-packages/urllib3/connection.py", line 155, in connect
    conn = self._new_conn()
  File "/users/lcrook/rtd/lib/python2.7/site-packages/urllib3/connection.py", line 134, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/users/lcrook/rtd/lib/python2.7/site-packages/urllib3/util/connection.py", line 88, in create_connection
    raise err
ProtocolError: ('Connection aborted.', error(111, 'Connection refused'))
[20/Jul/2015 15:48:42] INFO [urllib3.connectionpool:203] Starting new HTTP connection (3): 127.0.0.1
[20/Jul/2015 15:48:42] WARNING [elasticsearch:82] PUT http://127.0.0.1:9200/readthedocs/project/24 [status:N/A request:0.002s]
Traceback (most recent call last):
  File "/users/lcrook/rtd/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 74, in perform_request
    response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)
  File "/users/lcrook/rtd/lib/python2.7/site-packages/urllib3/connectionpool.py", line 597, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/users/lcrook/rtd/lib/python2.7/site-packages/urllib3/util/retry.py", line 222, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/users/lcrook/rtd/lib/python2.7/site-packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/users/lcrook/rtd/lib/python2.7/site-packages/urllib3/connectionpool.py", line 349, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/opt/rh/python27/root/usr/lib64/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/opt/rh/python27/root/usr/lib64/python2.7/httplib.py", line 1007, in _send_request
    self.endheaders(body)
  File "/opt/rh/python27/root/usr/lib64/python2.7/httplib.py", line 969, in endheaders
    self._send_output(message_body)
  File "/opt/rh/python27/root/usr/lib64/python2.7/httplib.py", line 829, in _send_output
    self.send(msg)
  File "/opt/rh/python27/root/usr/lib64/python2.7/httplib.py", line 791, in send
    self.connect()
  File "/users/lcrook/rtd/lib/python2.7/site-packages/urllib3/connection.py", line 155, in connect
    conn = self._new_conn()
  File "/users/lcrook/rtd/lib/python2.7/site-packages/urllib3/connection.py", line 134, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/users/lcrook/rtd/lib/python2.7/site-packages/urllib3/util/connection.py", line 88, in create_connection
    raise err
ProtocolError: ('Connection aborted.', error(111, 'Connection refused'))
[20/Jul/2015 15:48:42] INFO [urllib3.connectionpool:203] Starting new HTTP connection (4): 127.0.0.1
[20/Jul/2015 15:48:42] WARNING [elasticsearch:82] PUT http://127.0.0.1:9200/readthedocs/project/24 [status:N/A request:0.001s]
Traceback (most recent call last):
  File "/users/lcrook/rtd/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 74, in perform_request
    response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)
  File "/users/lcrook/rtd/lib/python2.7/site-packages/urllib3/connectionpool.py", line 597, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/users/lcrook/rtd/lib/python2.7/site-packages/urllib3/util/retry.py", line 222, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/users/lcrook/rtd/lib/python2.7/site-packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/users/lcrook/rtd/lib/python2.7/site-packages/urllib3/connectionpool.py", line 349, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/opt/rh/python27/root/usr/lib64/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/opt/rh/python27/root/usr/lib64/python2.7/httplib.py", line 1007, in _send_request
    self.endheaders(body)
  File "/opt/rh/python27/root/usr/lib64/python2.7/httplib.py", line 969, in endheaders
    self._send_output(message_body)
  File "/opt/rh/python27/root/usr/lib64/python2.7/httplib.py", line 829, in _send_output
    self.send(msg)
  File "/opt/rh/python27/root/usr/lib64/python2.7/httplib.py", line 791, in send
    self.connect()
  File "/users/lcrook/rtd/lib/python2.7/site-packages/urllib3/connection.py", line 155, in connect
    conn = self._new_conn()
  File "/users/lcrook/rtd/lib/python2.7/site-packages/urllib3/connection.py", line 134, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/users/lcrook/rtd/lib/python2.7/site-packages/urllib3/util/connection.py", line 88, in create_connection
    raise err
ProtocolError: ('Connection aborted.', error(111, 'Connection refused'))
[20/Jul/2015 15:48:42] "POST /build/24 HTTP/1.1" 302 0
[20/Jul/2015 15:48:42] "GET /builds/edm-v/ HTTP/1.1" 200 10335
```

However subsequent updates to the documentation in git are not reflected.  The build indicates "passed", and in the log I see this;

```
checkout
-----

venv
-----

doc_builder
-----

install
-----

No setup.py, skipping install
```

**Comment by gregmuellegger** [comment]
You get this error when running a standalone installation of RTD, right? Seems a bit like your Redis setup is not running, but I'm not 100% sure based on the message.

We cannot support custom RTD installations because of resouce constraints, but I'm marking this ticket as community effort to allow anyone who wants to help out to help here.

**Comment by jonafato** [comment]
It looks like both redis and elasticsearch are unreachable based on the errors shown here. Do you have both of these running on localhost on the default ports?

**Comment by Balooga** [comment]
Negative on both counts.  I shall attempt to fix.

**Comment by Balooga** [comment]
Redis is now running, so the errors above have disappeared.  However RTD does not seem to be building any updates to the documentation following the initial manual import.

````
[14/Aug/2015 16:34:31]"GET /api/v1/project/27/ HTTP/1.1" 200 1294
[14/Aug/2015 16:34:31]"GET /api/v1/version/26/ HTTP/1.1" 200 1555
[14/Aug/2015 16:34:31]"GET /api/v1/build/31/ HTTP/1.1" 200 381
[14/Aug/2015 16:34:31]"PUT /api/v1/build/31/ HTTP/1.1" 200 413
[14/Aug/2015 16:34:31] INFO [readthedocs.projects.tasks:207] (Build) [edm-v:latest] Updating docs from VCS
[14/Aug/2015 16:34:31]"GET /api/v1/version/26/ HTTP/1.1" 200 1555
[14/Aug/2015 16:34:31] INFO [readthedocs.projects.tasks:460] (Build) [edm-v:latest] Checking out version latest: master
[14/Aug/2015 16:34:32]"POST /api/v2/project/27/sync_versions/ HTTP/1.1" 200 43
[14/Aug/2015 16:34:32]"PUT /api/v1/build/31/ HTTP/1.1" 200 454
[14/Aug/2015 16:34:32] INFO [readthedocs.doc_builder.environments:79] Running: 'python -mvirtualenv --no-site-packages /users/lcrook/rtd/checkouts/readthedocs.org/user_builds/edm-v/envs/latest' [/users/lcrook/rtd/checkouts/readthedocs.org]
[14/Aug/2015 16:34:38] INFO [readthedocs.doc_builder.environments:79] Running: 'python /users/lcrook/rtd/checkouts/readthedocs.org/user_builds/edm-v/envs/latest/bin/pip install --use-wheel --find-links=/users/lcrook/rtd/checkouts/readthedocs.org/deploy/wheels -U sphinx==1.3.1 Pygments==2.0.2 virtualenv==13.1.0 setuptools==18.0.1 docutils==0.11 mkdocs==0.14.0 mock==1.0.1 pillow==2.6.1 readthedocs-sphinx-ext==0.5.4 sphinx-rtd-theme==0.1.8 alabaster>=0.7,<0.8,!=0.7.5 recommonmark==0.1.1' [/users/lcrook/rtd/checkouts/readthedocs.org]
[14/Aug/2015 16:34:44]"PUT /api/v1/build/31/ HTTP/1.1" 200 5216
[14/Aug/2015 16:34:44] INFO [readthedocs.doc_builder.base:46] Forcing a build
[14/Aug/2015 16:34:44] INFO [readthedocs.doc_builder.environments:79] Running: 'python /users/lcrook/rtd/checkouts/readthedocs.org/user_builds/edm-v/envs/latest/bin/mkdocs build --clean --site-dir _build/html --theme readthedocs' [/users/lcrook/rtd/checkouts/readthedocs.org/user_builds/edm-v/checkouts/latest]
[14/Aug/2015 16:34:46] INFO [readthedocs.doc_builder.base:62] Copying mkdocs on the local filesystem
[14/Aug/2015 16:34:46] INFO [readthedocs.doc_builder.environments:79] Running: 'python /users/lcrook/rtd/checkouts/readthedocs.org/user_builds/edm-v/envs/latest/bin/mkdocs json --clean --site-dir _build/json' [/users/lcrook/rtd/checkouts/readthedocs.org/user_builds/edm-v/checkouts/latest]
[14/Aug/2015 16:34:47] INFO [readthedocs.doc_builder.base:62] Copying mkdocs_json on the local filesystem
[14/Aug/2015 16:34:47] INFO [readthedocs.core.utils:25] Running rm -rf /users/lcrook/rtd/checkouts/readthedocs.org/media/pdf/edm-v/latest/edm-v.pdf on app servers
[14/Aug/2015 16:34:47] INFO [readthedocs.core.utils:25] Running rm -rf /users/lcrook/rtd/checkouts/readthedocs.org/media/epub/edm-v/latest/edm-v.epub on app servers
[14/Aug/2015 16:34:47] INFO [readthedocs.core.utils:25] Running mkdir -p /users/lcrook/rtd/checkouts/readthedocs.org/user_builds/edm-v/translations on app servers
[14/Aug/2015 16:34:47] INFO [readthedocs.core.utils:25] Running ln -nsf /users/lcrook/rtd/checkouts/readthedocs.org/user_builds/edm-v/rtd-builds /users/lcrook/rtd/checkouts/readthedocs.org/user_builds/edm-v/translations/en on app servers
[14/Aug/2015 16:34:47] INFO [readthedocs.core.utils:25] Running rm -f /users/lcrook/rtd/checkouts/readthedocs.org/user_builds/edm-v/single_version on app servers
[14/Aug/2015 16:34:47] INFO [readthedocs.projects.tasks:748] (Build) [edm-v:] Updating static metadata
[14/Aug/2015 16:34:48] ERROR [readthedocs.search.utils:121] Unable to index file headers for: /users/lcrook/rtd/checkouts/readthedocs.org/media/json/edm-v/latest/index.json
[14/Aug/2015 16:34:48]"PUT /api/v1/build/31/ HTTP/1.1" 200 6011
[14/Aug/2015 16:34:48] INFO [readthedocs.doc_builder.environments:243] (Build) [edm-v:latest] Build finished
[14/Aug/2015 16:34:48]"POST /build/27 HTTP/1.1" 302 0
[14/Aug/2015 16:34:48]"GET /projects/edm-v/builds/ HTTP/1.1" 200 10194

````

**Comment by agjohnson** [comment]
Automatically? Because you need to set up a webhook that can be received by RTD.

**Comment by stsewd** [comment]
@Balooga Hi, can you check if what Anthony says is the problem? Or maybe you have already solved this problem?

**Comment by stsewd** [comment]
Closing this as the user [hasn't responded or given more information](https://docs.readthedocs.io/en/latest/contribute.html#initial-triage), feel free to reopen with more information if you are still having this problem :).
