### ISSUE TITLE
Problems with new gulp build system

### ISSUE THREAD

**Issue by gregmuellegger** [rtfd/readthedocs.org#1490]
While working on #1417 and merging the current master I found these problems with the gulp buildsystem. When running `gulp build` I get:

```
[17:38:43] Using gulpfile ~/projects/readthedocs.org/gulpfile.js
[17:38:43] Starting 'build'...
[17:38:43] Building source files
[17:38:47] Collecting static files
$ django-admin.py collectstatic --noinput
Traceback (most recent call last):
  File "/home/gregor/.virtualenvs/readthedocs.org/bin/django-admin.py", line 5, in <module>
    management.execute_from_command_line()
  File "/home/gregor/.virtualenvs/readthedocs.org/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/gregor/.virtualenvs/readthedocs.org/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/gregor/.virtualenvs/readthedocs.org/lib/python2.7/site-packages/django/core/management/__init__.py", line 182, in fetch_command
    settings.INSTALLED_APPS
  File "/home/gregor/.virtualenvs/readthedocs.org/lib/python2.7/site-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/home/gregor/.virtualenvs/readthedocs.org/lib/python2.7/site-packages/django/conf/__init__.py", line 42, in _setup
    % (desc, ENVIRONMENT_VARIABLE))
django.core.exceptions.ImproperlyConfigured: Requested setting INSTALLED_APPS, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
[17:38:47] 'build' errored after 4.27 s
[17:38:47] Error: Command `django-admin.py collectstatic --noinput` exited with code 1
    at ChildProcess.<anonymous> (/home/gregor/projects/readthedocs.org/node_modules/gulp-run/lib/command.js:145:15)
    at ChildProcess.g (events.js:199:16)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Command `django-admin.py collectstatic --noinput` exited with code 1
    at ChildProcess.<anonymous> (/home/gregor/projects/readthedocs.org/node_modules/gulp-run/lib/command.js:145:15)
    at ChildProcess.g (events.js:199:16)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
gulp build  6,44s user 0,71s system 112% cpu 6,330 total
```

However `PYTHONPATH=readthedocs DJANGO_SETTINGS_MODULE=settings.sqlite gulp build` works. Is this expected?

Also the `gulp dev` doesn't work. I get this (both when run from top-level or from within `readthedocs/`):

```
[17:40:07] Using gulpfile ~/projects/readthedocs.org/gulpfile.js
[17:40:07] Starting 'dev'...
[17:40:07] Continually building source files
[17:40:09] dev saw core/js/projectimport.js was changed
[17:40:10] Collecting static files
[17:40:14] dev saw core/js/projectimport.js was changed
[17:40:15] Collecting static files
$ ./manage.py collectstatic --noinput
sh: ./manage.py: Datei oder Verzeichnis nicht gefunden
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Command `./manage.py collectstatic --noinput` exited with code 127
    at ChildProcess.<anonymous> (/home/gregor/projects/readthedocs.org/node_modules/gulp-run/lib/command.js:145:15)
    at ChildProcess.g (events.js:199:16)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Socket.<anonymous> (child_process.js:1183:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:485:12)
```

The reason is propably that gulp `cd`s into the root directory when running gulp. Do you get the same errors? Are you doing something differently?

Also the `gulp dev` issue about not finding `manage.py` only happens on the second save of a watched file. The first one triggers the build, the second save brings up the error above.

**Comment by agjohnson** [comment]
So two issues here. I missed the second `manage.py` script, which i intended to be `django-admin.py`. The second issue is that I assumed other had their env configured like mine was :). If you don't set the default settings module and a pythonpath, `django-admin` is likely to fail like this ^.

After some discussion, we figure we should probably continue using manage.py for development purposes, until we have answers for automating/fixing some of the setup that manage.py performs.

**Comment by gregmuellegger** [comment]
Awesome! #1491 fixed this for me. :beers: cheers!
