### ISSUE TITLE
Version mismatch in matplotlib?

### ISSUE THREAD

**Issue by hamogu** [rtfd/readthedocs.org#1494]
This issue appeared for me in the project "marx.readthedocs.org". The sphinx docs contain a plot directive
```
.. plot:: plots/sketch_coords.py optical_element_coords
```
which should include the following matplotlib plot:
```
"""This module make plots and sketches for the documentation."""

import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import numpy as np

def optical_element_coords():
   fig = plt.figure()
   ax = fig.add_subplot(111, projection='3d')
   ax.quiver([2,0,0],[0,2,0],[0,0, 2],[1,0,0],[0,1,0], [0,0,1], length=4, arrow_length_ratio=.05, color='k', lw=2)
   ax.bar3d(-1, -1, -1, 1, 2, 2, zsort='average', alpha=0.5, color=['b'] *5 + ['r'], zorder=1)
   ax.set_axis_off()
   ax.text(2.1, 0, 0, 'x', None, fontsize='x-large')
   ax.text(0, 2.1, 0, 'y', None, fontsize='x-large')
   ax.text(0, 0, 2.1, 'z', None, fontsize='x-large')
   ax.set_xlim([-1.2,1.2])
   ax.set_ylim([-1.2,1.2])
   ax.set_zlim([-1.2,1.2])
   fig.subplots_adjust(left=0,right=1,top=1,bottom=0)
   plt.show()
```
This builds without warnings locally using matplotlib 1.4.3.
However, it fails on readthedocs, even though I require the exact same matplotlib version there.
```
Build Standard Error



html
-----

/usr/lib/pymodules/python2.7/matplotlib/__init__.py:758: UserWarning: Found matplotlib configuration in ~/.matplotlib/. To conform with the XDG base directory standard, this configuration location has been deprecated on Linux, and the new location is now '/home/docs/.config'/matplotlib/. Please move your configuration there to ensure that matplotlib will continue to find it in the future.
  _get_xdg_config_dir())
/home/docs/checkouts/readthedocs.org/user_builds/marxs/checkouts/latest/docs/API/marxs.optics.marx.MarxMirror.rst:3: WARNING: Duplicate explicit target name: "marx".
/home/docs/checkouts/readthedocs.org/user_builds/marxs/checkouts/latest/docs/conventions.rst:42: WARNING: Exception occurred in plotting sketch_coords
 from /home/docs/checkouts/readthedocs.org/user_builds/marxs/checkouts/latest/docs/plots/sketch_coords.py:
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/matplotlib/sphinxext/plot_directive.py", line 517, in run_code
    exec function_name + "()" in ns
  File "<string>", line 1, in <module>
  File "<string>", line 10, in optical_element_coords
  File "/usr/lib/pymodules/python2.7/matplotlib/axes.py", line 6836, in quiver
    q = mquiver.Quiver(self, *args, **kw)
  File "/usr/lib/pymodules/python2.7/matplotlib/quiver.py", line 417, in __init__
    **kw)
  File "/usr/lib/pymodules/python2.7/matplotlib/collections.py", line 742, in __init__
    Collection.__init__(self, **kwargs)
  File "/usr/lib/pymodules/python2.7/matplotlib/collections.py", line 128, in __init__
    self.update(kwargs)
  File "/usr/lib/pymodules/python2.7/matplotlib/artist.py", line 739, in update
    raise AttributeError('Unknown property %s' % k)
AttributeError: Unknown property arrow_length_ratio
```

An example is this build: https://readthedocs.org/builds/marxs/3158024/

**Comment by gregmuellegger** [comment]
I'm not 100% sure but I think we are using the 1.3.1 version of `python-matplotlib` on the server. We are using the ubuntu distribution of this as we do not want to maintain a self-compiled package.

Is it possible so that you make the code compatible with 1.3.x of matplotlib?

**Comment by hamogu** [comment]
I'll try rewriting my matplotlib code (but not right now,  because there are currently other issues in that repository that I'll need to resolve, but don't have time to look at right now).

However, if you use version 1.3.1, why does the build log claim that 1.4.3 is installed?
```
requirements
-----

Collecting matplotlib>=1.4 (from -r docs/rtd-pip-requirements (line 1))
  Using cached matplotlib-1.4.3.tar.gz
    Complete output from command python setup.py egg_info:
    IMPORTANT WARNING:
        pkg-config is not installed.
        matplotlib may not be able to find some of its dependencies
    ============================================================================
    Edit setup.cfg to change the build options
    
    BUILDING MATPLOTLIB
                matplotlib: yes [1.4.3]
                    python: yes [2.7.6 (default, Mar 22 2014, 22:59:56)  [GCC
                            4.8.2]]
                  platform: yes [linux2]
    
    REQUIRED DEPENDENCIES AND EXTENSIONS
                     numpy: yes [version 1.8.2]
                       six: yes [using six version 1.9.0]
                  dateutil: yes [using dateutil version 1.5]
                      pytz: yes [using pytz version 2015.4]
                   tornado: yes [using tornado version 4.2.1]
                 pyparsing: yes [using pyparsing version 2.0.1]
                     pycxx: yes [Couldn't import.  Using local copy.]
                    libagg: yes [pkg-config information for 'libagg' could not
                            be found. Using local copy.]
                  freetype: no  [The C/C++ header for freetype2 (ft2build.h)
                            could not be found.  You may need to install the
                            development package.]
                       png: no  [pkg-config information for 'libpng' could not
                            be found.]
                     qhull: yes [pkg-config information for 'qhull' could not be
                            found. Using local copy.]
```

**Comment by hamogu** [comment]
(That's why I chose "Version mismatch in matplotlib?" as the title for this issue). It looks to me that the version of matplotlib that is used and the one that is listed in the build log are not the same.

**Comment by gregmuellegger** [comment]
Oh, ok. I assume someone with more matplotlib/server experience needs to have a look. @ericholscher maybe? :)

**Comment by hamogu** [comment]
Please note: I've just removed the line "matplotlib>=1.4.3" from
readthedocs-pip-requirements (no point wasting extra time in the build
if it does not do what it's supposed to anyway), so you won't see the
problem any longer in new builds, but it's of course still present in
any of the older builds.

**Comment by paternal** [comment]
> I'm not 100% sure but I think we are using the 1.3.1 version of python-matplotlib on the server.

Shameless self promotion : [python-matplotlib 1.3.1 is installed](http://packages.readthedocs.org/en/latest/deb/?highlight=matplotlib) (look for `matplotlib` on the jinked page).

**Comment by gregmuellegger** [comment]
@paternal thanks for the clarification! :)

**Comment by ericholscher** [comment]
Has this been resolved?

**Comment by agjohnson** [comment]
Closing this due to inactivity, but feel free to reopen if this was not resolved.

**Comment by mgeier** [comment]
This seems to be still not resolved.

See for example this build: https://readthedocs.org/projects/sfs-python/builds/4658260/

In `doc/requirements.txt` I ask for `matplotlib>=1.5` and the build log shows

```
...
Collecting matplotlib>=1.5 (from -r doc/requirements.txt (line 8))
  Using cached matplotlib-1.5.3-cp34-cp34m-manylinux1_x86_64.whl
...
Installing collected packages: cycler, matplotlib
  Found existing installation: matplotlib 1.3.1
    Not uninstalling matplotlib at /usr/lib/python3/dist-packages, outside environment /home/docs/checkouts/readthedocs.org/user_builds/sfs-python/envs/readthedocs-update
Successfully installed cycler-0.10.0 matplotlib-1.5.3
...
```

... which looks good.

However, in my `conf.py` I'm checking for `matplotlib.__version__` and this yields `1.3.1`.
