### ISSUE TITLE
"pip install -r requirements.txt" failure

### ISSUE THREAD

**Issue by Balooga** [rtfd/readthedocs.org#1536]
Hi,

Using the latest from git, "pip install -r requirements.txt" returns the following error.

````
Collecting bzr==2.6 (from -r requirements/pip.txt (line 24))
  Using cached bzr-2.6.0.tar.gz
    Complete output from command python setup.py egg_info:
    No Cython, trying Pyrex...
    
    The python package 'Pyrex' is not available. If the .c files are available,
    they will be built, but modifying the .pyx files will not rebuild them.
    
    running egg_info
    creating pip-egg-info/bzr.egg-info
    writing dependency_links to pip-egg-info/bzr.egg-info/dependency_links.txt
    writing pip-egg-info/bzr.egg-info/PKG-INFO
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-g1yt3g/bzr/setup.py", line 780, in <module>
        setup(**ARGS)
      File "/opt/rh/python33/root/usr/lib64/python3.3/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/opt/rh/python33/root/usr/lib64/python3.3/distutils/dist.py", line 929, in run_commands
        self.run_command(cmd)
      File "/opt/rh/python33/root/usr/lib64/python3.3/distutils/dist.py", line 948, in run_command
        cmd_obj.run()
      File "<string>", line 14, in replacement_run
      File "/users/lcrook/rtd/lib/python3.3/site-packages/setuptools/command/egg_info.py", line 415, in write_pkg_info
        metadata.write_pkg_info(cmd.egg_info)
      File "/opt/rh/python33/root/usr/lib64/python3.3/distutils/dist.py", line 1027, in write_pkg_info
        self.write_pkg_file(pkg_info)
      File "/opt/rh/python33/root/usr/lib64/python3.3/distutils/dist.py", line 1048, in write_pkg_file
        long_desc = rfc822_escape(self.get_long_description())
      File "/opt/rh/python33/root/usr/lib64/python3.3/distutils/util.py", line 490, in rfc822_escape
        lines = header.split('\n')
    TypeError: Type str doesn't support the buffer API
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-g1yt3g/bzr
````

**Comment by gregmuellegger** [comment]
It works for me in a new empty virtualenv. Do you have all the required dependencies installed listed here: http://docs.readthedocs.org/en/latest/install.html ?

For example, on Ubuntu you need:
```bash
sudo apt-get install build-essential
sudo apt-get install python-dev
sudo apt-get install libxml2-dev libxslt1-dev zlib1g-dev
```

**Comment by Balooga** [comment]
"pip install -r requirements.txt" worked for me in an empty virtualenv up until very recently (about a week ago, I think).

**Comment by agjohnson** [comment]
This looks to be because you are using Python 3.3, which we do not support. We might aim for Python 3 support with 3.4 at some point, but the long tail of dependencies like the above bzr failure on Python 3 needs to be addressed.

**Comment by Balooga** [comment]
Yes.  Me actually following the instructions helped enormously.
