### ISSUE TITLE
matplotlib plot directive unable to import documented project

### ISSUE THREAD

**Issue by ZeeD26** [rtfd/readthedocs.org#1626]
Matplotlib provides a plot directive that allows rendering the image that results from code by merely inserting said code.
If this code, however, includes an import statement of the very same package I am trying to document it does not work with the readthedocs builder, while on my machine everything runs smoothly.

As a minimal example take
http://pydougu.readthedocs.org/en/latest/matplotlib/colormaps.html
where you can download see the source.

The warning I get from the builder is the following
```
/home/docs/checkouts/readthedocs.org/user_builds/pydougu/checkouts/latest/docs/matplotlib/colormaps.rst:9: WARNING: Exception occurred in plotting show_viridis
 from /home/docs/checkouts/readthedocs.org/user_builds/pydougu/checkouts/latest/docs/pyplots/show_viridis.py:
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/matplotlib/sphinxext/plot_directive.py", line 515, in run_code
    exec code in ns
  File "<string>", line 3, in <module>
ImportError: No module named matplotlib.colormaps._viridis
/home/docs/checkouts/readthedocs.org/user_builds/pydougu/checkouts/latest/docs/matplotlib/colormaps.rst:14: WARNING: Exception occurred in plotting show_magma
 from /home/docs/checkouts/readthedocs.org/user_builds/pydougu/checkouts/latest/docs/pyplots/show_magma.py:
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/matplotlib/sphinxext/plot_directive.py", line 515, in run_code
    exec code in ns
  File "<string>", line 3, in <module>
ImportError: No module named matplotlib.colormaps._magma
/home/docs/checkouts/readthedocs.org/user_builds/pydougu/checkouts/latest/docs/matplotlib/colormaps.rst:19: WARNING: Exception occurred in plotting show_inferno
 from /home/docs/checkouts/readthedocs.org/user_builds/pydougu/checkouts/latest/docs/pyplots/show_inferno.py:
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/matplotlib/sphinxext/plot_directive.py", line 515, in run_code
    exec code in ns
  File "<string>", line 3, in <module>
ImportError: No module named matplotlib.colormaps._inferno
/home/docs/checkouts/readthedocs.org/user_builds/pydougu/checkouts/latest/docs/matplotlib/colormaps.rst:24: WARNING: Exception occurred in plotting show_plasma
 from /home/docs/checkouts/readthedocs.org/user_builds/pydougu/checkouts/latest/docs/pyplots/show_plasma.py:
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/matplotlib/sphinxext/plot_directive.py", line 515, in run_code
    exec code in ns
  File "<string>", line 3, in <module>
ImportError: No module named matplotlib.colormaps._plasma
```

It seems like the name of my package somehow gets lost on the way, as I am never trying to merely import ``matplotlib.colormaps._*`` but ``pydougu.matplotlib.colormas._*``.

**Comment by gregmuellegger** [comment]
Hi, I think the reason for you issue is, that the source distribution that is installed for the build with `python setup.py install` does not contain the `pydougu/matplotlib/` subdirectory.

See the contents of the generated tar file after I created the source distribution with `python setup.py sdist`:
```
$ tar -tf dist/pydougu-1.0.0.tar.gz 
pydougu-1.0.0/
pydougu-1.0.0/README.rst
pydougu-1.0.0/pydougu.egg-info/
pydougu-1.0.0/pydougu.egg-info/top_level.txt
pydougu-1.0.0/pydougu.egg-info/SOURCES.txt
pydougu-1.0.0/pydougu.egg-info/dependency_links.txt
pydougu-1.0.0/pydougu.egg-info/requires.txt
pydougu-1.0.0/pydougu.egg-info/PKG-INFO
pydougu-1.0.0/pydougu/
pydougu-1.0.0/pydougu/__init__.py
pydougu-1.0.0/setup.py
pydougu-1.0.0/setup.cfg
pydougu-1.0.0/PKG-INFO
```

The matplotlib directory is missing. So this is a problem with your package setup.
I assume you need to add the missing modules to the `packages` argument in `setup.py` or use setuptools' `find_packages` helper: https://pythonhosted.org/setuptools/setuptools.html#using-find-packages
