### ISSUE TITLE
Can't build the docs

### ISSUE THREAD

**Issue by kottenator** [rtfd/readthedocs.org#1658]
I'm installing self-hosted RTD now (commit: `e34541f3895`)

When I try to do `manage.py update_repos pip`

It raises an error:

```
Traceback (most recent call last):
  File "/var/www/readthedocs.org/readthedocs/projects/tasks.py", line 125, in run
    outcomes = self.build_docs()
  File "/var/www/readthedocs.org/readthedocs/projects/tasks.py", line 346, in build_docs
    outcomes['html'] = self.build_docs_html()
  File "/var/www/readthedocs.org/readthedocs/projects/tasks.py", line 362, in build_docs_html
    html_builder.append_conf()
  File "/var/www/readthedocs.org/readthedocs/doc_builder/backends/sphinx.py", line 78, in append_conf
    remote_version = self.version.get_vcs_slug()
AttributeError: 'Version' object has no attribute 'get_vcs_slug'
[15/Sep/2015 14:57:36] INFO [readthedocs.doc_builder.environments:274] (Build) [pip:latest] Build finished
```

**Comment by gregmuellegger** [comment]
There shouldn't be any reference to `get_vcs_slug` left in the current code base as with the merge of #1650. Please update to the latest master.
