### ISSUE TITLE
Old PIP is used for  latest virtualenv 

### ISSUE THREAD

**Issue by Vitexus** [rtfd/readthedocs.org#1667]
On Ubuntu Precise with successfully installed RTD:

Projects docs dir is fresh and empty skeleton with no dependencies.

```
[pid: 31905|app: 0|req: 239/977] 127.0.0.1 () {38 vars in 567 bytes} [Fri Sep 18 11:34:25 2015] PUT /api/v2/build/43/ => generated 309 bytes in 1109 msecs (HTTP/1.1 200) 4 headers in 159 bytes (1 switches on core 0)
[18/Sep/2015 11:34:26] INFO [readthedocs.doc_builder.environments:99] Running: 'python -mvirtualenv --system-site-packages /opt/rtd/checkouts/readthedocs.org/user_builds/netspot-webservice-v3/envs/latest' [/opt/rtd/checkouts/readthedocs.org/readthedocs]
[pid: 31905|app: 0|req: 240/978] 127.0.0.1 () {38 vars in 566 bytes} [Fri Sep 18 11:34:33 2015] POST /api/v2/command/ => generated 666 bytes in 1041 msecs (HTTP/1.1 201) 4 headers in 150 bytes (1 switches on core 0)
[18/Sep/2015 11:34:34] INFO [readthedocs.doc_builder.environments:99] Running: 'python /opt/rtd/checkouts/readthedocs.org/user_builds/netspot-webservice-v3/envs/latest/bin/pip install --use-wheel --find-links=/opt/rtd/checkouts/readthedocs.org/deploy/wheels -U -I sphinx==1.3.1 Pygments==2.0.2 virtualenv==13.1.0 setuptools==18.0.1 docutils==0.11 mkdocs==0.14.0 mock==1.0.1 pillow==2.6.1 readthedocs-sphinx-ext==0.5.4 sphinx-rtd-theme==0.1.9 alabaster>=0.7,<0.8,!=0.7.5 recommonmark==0.1.1' [/opt/rtd/checkouts/readthedocs.org/readthedocs]
[pid: 31905|app: 0|req: 241/979] 127.0.0.1 () {38 vars in 566 bytes} [Fri Sep 18 11:34:35 2015] POST /api/v2/command/ => generated 848 bytes in 950 msecs (HTTP/1.1 201) 4 headers in 150 bytes (1 switches on core 0)
[18/Sep/2015 11:34:36] ERROR [readthedocs.doc_builder.environments:293] (Build) [netspot-webservice-v3:latest] Command python /opt/rtd/checkouts/readthedocs.org/user_builds/netspot-webservice-v3/envs/latest/bin/pip install --use-wheel --find-links=/opt/rtd/checkouts/readthedocs.org/deploy/wheels -U -I sphinx==1.3.1 Pygments==2.0.2 virtualenv==13.1.0 setuptools==18.0.1 docutils==0.11 mkdocs==0.14.0 mock==1.0.1 pillow==2.6.1 readthedocs-sphinx-ext==0.5.4 sphinx-rtd-theme==0.1.9 alabaster>=0.7,<0.8,!=0.7.5 recommonmark==0.1.1 failed:
Usage: /opt/rtd/checkouts/readthedocs.org/user_builds/netspot-webservice-v3/envs/latest/bin/pip install [OPTIONS] PACKAGE_NAMES...

/opt/rtd/checkouts/readthedocs.org/user_builds/netspot-webservice-v3/envs/latest/bin/pip install: error: no such option: --use-wheel
Traceback (most recent call last):
  File "/opt/rtd/checkouts/readthedocs.org/readthedocs/projects/tasks.py", line 121, in run
    self.setup_environment()
  File "/opt/rtd/checkouts/readthedocs.org/readthedocs/projects/tasks.py", line 277, in setup_environment
    *cmd,
  File "/opt/rtd/checkouts/readthedocs.org/readthedocs/doc_builder/environments.py", line 304, in run
    return self.run_command_class(cls=self.command_class, cmd=cmd, **kwargs)
  File "/opt/rtd/checkouts/readthedocs.org/readthedocs/doc_builder/environments.py", line 335, in run_command_class
    raise BuildEnvironmentWarning(msg)
BuildEnvironmentWarning: Command python /opt/rtd/checkouts/readthedocs.org/user_builds/netspot-webservice-v3/envs/latest/bin/pip install --use-wheel --find-links=/opt/rtd/checkouts/readthedocs.org/deploy/wheels -U -I sphinx==1.3.1 Pygments==2.0.2 virtualenv==13.1.0 setuptools==18.0.1 docutils==0.11 mkdocs==0.14.0 mock==1.0.1 pillow==2.6.1 readthedocs-sphinx-ext==0.5.4 sphinx-rtd-theme==0.1.9 alabaster>=0.7,<0.8,!=0.7.5 recommonmark==0.1.1 failed:
Usage: /opt/rtd/checkouts/readthedocs.org/user_builds/netspot-webservice-v3/envs/latest/bin/pip install [OPTIONS] PACKAGE_NAMES...

/opt/rtd/checkouts/readthedocs.org/user_builds/netspot-webservice-v3/envs/latest/bin/pip install: error: no such option: --use-wheel
```

**Comment by agjohnson** [comment]
Is there any more information on this failure? I don't see a good reason that a recent version of pip isn't being used. Either way, hard for us to support this issue on an external installation.

**Comment by Vitexus** [comment]
No. Please close this issue. We will hope in fresh pip poweres :)

**Comment by mazhenhit** [comment]
Is the issue solved? I meet the same issue.
How you solve it ?
Could you explain it ?
