### ISSUE TITLE
pip/requests issue resulting in build failure

### ISSUE THREAD

**Issue by abakan** [rtfd/readthedocs.org#1752]
I started seeing the following pip/requests issue. It appeared in more than 10 build attempts back to back.

No issue: https://readthedocs.org/projects/ablog/builds/3391768/
...
Has issue: https://readthedocs.org/projects/ablog/builds/3391848
...
No issue: https://readthedocs.org/projects/ablog/builds/3391856/

There is another issue that I am trying to resolve related to my build, but this looked like unrelated to that. Any idea what's going on?

```python
$ python /home/docs/checkouts/readthedocs.org/user_builds/ablog/envs/latest/bin/pip install --use-wheel --find-links=/home/docs/checkouts/readthedocs.org/deploy/wheels -U -I sphinx==1.3.1 Pygments==2.0.2 virtualenv==13.1.0 setuptools==18.0.1 docutils==0.11 mkdocs==0.14.0 mock==1.0.1 pillow==2.6.1 readthedocs-sphinx-ext==0.5.4 sphinx-rtd-theme==0.1.9 alabaster>=0.7,<0.8,!=0.7.5 recommonmark==0.1.1

Downloading/unpacking sphinx==1.3.1
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 1178, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 252, in find_requirement
    for page in self._get_pages(locations, req):
  File "/usr/lib/python3/dist-packages/pip/index.py", line 387, in _get_pages
    page = self._get_page(location, req)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 568, in _get_page
    session=self.session,
  File "/usr/lib/python3/dist-packages/pip/index.py", line 670, in get_page
    resp = session.get(url, headers={"Accept": "text/html"})
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 467, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/pip/download.py", line 237, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 421, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 359, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/lib/python3/dist-packages/requests/models.py", line 287, in prepare
    self.prepare_url(url, params)
  File "/usr/lib/python3/dist-packages/requests/models.py", line 338, in prepare_url
    "Perhaps you meant http://{0}?".format(url))
requests.exceptions.MissingSchema: Invalid URL '/home/docs/checkouts/readthedocs.org/deploy/wheels': No schema supplied. Perhaps you meant http:///home/docs/checkouts/readthedocs.org/deploy/wheels?

Storing debug log for failure in /home/docs/.pip/pip.log
```

**Comment by ericholscher** [comment]
Looks like builds are passing lately, so closing this. Please let us know if it's still an issue.
