### ISSUE TITLE
`UnicodeDecodeError` during `pip install`

### ISSUE THREAD

**Issue by paternal** [rtfd/readthedocs.org#1768]
The documentation of [jouets](https://git.framasoft.org/spalax/jouets/) fails because of a `UnicodeDecodeError`:

https://readthedocs.org/projects/jouets/builds/3376918/

~~~sh
$ python /home/docs/checkouts/readthedocs.org/user_builds/jouets/envs/latest/bin/pip install --exists-action=w -rdoc/requirements.txt
Exception:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/jouets/envs/latest/lib/python3.4/site-packages/pip/basecommand.py", line 211, in main
    status = self.run(options, args)
  File "/home/docs/checkouts/readthedocs.org/user_builds/jouets/envs/latest/lib/python3.4/site-packages/pip/commands/install.py", line 282, in run
    wheel_cache
  File "/home/docs/checkouts/readthedocs.org/user_builds/jouets/envs/latest/lib/python3.4/site-packages/pip/basecommand.py", line 291, in populate_requirement_set
    wheel_cache=wheel_cache):
  File "/home/docs/checkouts/readthedocs.org/user_builds/jouets/envs/latest/lib/python3.4/site-packages/pip/req/req_file.py", line 77, in parse_requirements
    filename, comes_from=comes_from, session=session
  File "/home/docs/checkouts/readthedocs.org/user_builds/jouets/envs/latest/lib/python3.4/site-packages/pip/download.py", line 413, in get_file_content
    content = f.read()
  File "/home/docs/checkouts/readthedocs.org/user_builds/jouets/envs/latest/lib/python3.4/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 70: ordinal not in range(128)
~~~

I think it is a readthedocs bug because two successive compilations with the same repository (same commit hash) yield different results: [success](https://readthedocs.org/projects/jouets/builds/3355845/), and [fail](https://readthedocs.org/projects/jouets/builds/3376918/).

Both my [`setup.py`](https://git.framasoft.org/spalax/jouets/blob/master/setup.py) and my [`conf.py`](https://git.framasoft.org/spalax/jouets/blob/master/doc/conf.py) contain non-ascii characters, but I tried removing them, and the result is still the same.

As far as I can tell, this is not related to any other issue mentionning a `UnicodeDecodeError`.

-- Louis

**Comment by techtonik** [comment]
Might be a `pip` problem. `success` build uses 7.0.1 and complains that 7.1.2 is available. Fail doesn't complain. For better troubleshooting it will be nice if rtfd builds explicitly dumped versions.

**Comment by paternal** [comment]
I fixed this by removing all non-ascii characters in the `requirements.txt` file. It was a `pip` problem.
