### ISSUE TITLE
Build passed ok but no generated documentation(?)

### ISSUE THREAD

**Issue by tarball69** [rtfd/readthedocs.org#1814]
Hi all,
First of all, thanks a lot for your awesome work. :+1: 
However, while trying to import my GitHub project 'CoolWorld' into rtfd's dashboard, I faced two major issues.
GitHub project: https://github.com/tarball69/CoolWorld
The first issue is the same as the one listed in #1809, so I imported my project manually.
First automatic build failed: this is quite normal, my project is **Python3**-oriented (Python >=3.2).
I changed in *advanced settings* the Python executable from Python2.x to Python3.x and then build passed OK... but no documentation were generated.
I took a look to builds' log:
```sh
Running Sphinx v1.3.1
making output directory...
loading translations [en]... done
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [readthedocs]: targets for 11 source files that are out of date
updating environment: 0 added, 10 changed, 0 removed
reading sources... [ 10%] CoolWorld
reading sources... [ 20%] CoolWorld.events
reading sources... [ 30%] CoolWorld.game
reading sources... [ 40%] CoolWorld.geometry
reading sources... [ 50%] CoolWorld.images
reading sources... [ 60%] CoolWorld.shapes
reading sources... [ 70%] CoolWorld.sounds
reading sources... [ 80%] CoolWorld.tkinter_ui
reading sources... [ 90%] CoolWorld.visual
reading sources... [100%] CoolWorld.world

/home/docs/checkouts/readthedocs.org/user_builds/coolworld/checkouts/latest/docs/CoolWorld.rst:4: WARNING: autodoc: failed to import module 'CoolWorld'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/coolworld/envs/latest/local/lib/python3.4/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
ImportError: No module named 'CoolWorld'
/home/docs/checkouts/readthedocs.org/user_builds/coolworld/checkouts/latest/docs/CoolWorld.events.rst:4: WARNING: autodoc: failed to import module 'CoolWorld.events'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/coolworld/envs/latest/local/lib/python3.4/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
ImportError: No module named 'CoolWorld'
/home/docs/checkouts/readthedocs.org/user_builds/coolworld/checkouts/latest/docs/CoolWorld.game.rst:4: WARNING: autodoc: failed to import module 'CoolWorld.game'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/coolworld/envs/latest/local/lib/python3.4/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
ImportError: No module named 'CoolWorld'
/home/docs/checkouts/readthedocs.org/user_builds/coolworld/checkouts/latest/docs/CoolWorld.geometry.rst:4: WARNING: autodoc: failed to import module 'CoolWorld.geometry'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/coolworld/envs/latest/local/lib/python3.4/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
ImportError: No module named 'CoolWorld'
/home/docs/checkouts/readthedocs.org/user_builds/coolworld/checkouts/latest/docs/CoolWorld.images.rst:4: WARNING: autodoc: failed to import module 'CoolWorld.images'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/coolworld/envs/latest/local/lib/python3.4/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
ImportError: No module named 'CoolWorld'
/home/docs/checkouts/readthedocs.org/user_builds/coolworld/checkouts/latest/docs/CoolWorld.shapes.rst:4: WARNING: autodoc: failed to import module 'CoolWorld.shapes'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/coolworld/envs/latest/local/lib/python3.4/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
ImportError: No module named 'CoolWorld'
/home/docs/checkouts/readthedocs.org/user_builds/coolworld/checkouts/latest/docs/CoolWorld.sounds.rst:4: WARNING: autodoc: failed to import module 'CoolWorld.sounds'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/coolworld/envs/latest/local/lib/python3.4/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
ImportError: No module named 'CoolWorld'
/home/docs/checkouts/readthedocs.org/user_builds/coolworld/checkouts/latest/docs/CoolWorld.tkinter_ui.rst:4: WARNING: autodoc: failed to import module 'CoolWorld.tkinter_ui'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/coolworld/envs/latest/local/lib/python3.4/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
ImportError: No module named 'CoolWorld'
/home/docs/checkouts/readthedocs.org/user_builds/coolworld/checkouts/latest/docs/CoolWorld.visual.rst:4: WARNING: autodoc: failed to import module 'CoolWorld.visual'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/coolworld/envs/latest/local/lib/python3.4/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
ImportError: No module named 'CoolWorld'
/home/docs/checkouts/readthedocs.org/user_builds/coolworld/checkouts/latest/docs/CoolWorld.world.rst:4: WARNING: autodoc: failed to import module 'CoolWorld.world'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/coolworld/envs/latest/local/lib/python3.4/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
ImportError: No module named 'CoolWorld'
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [  9%] CoolWorld
writing output... [ 18%] CoolWorld.events
writing output... [ 27%] CoolWorld.game
writing output... [ 36%] CoolWorld.geometry
writing output... [ 45%] CoolWorld.images
writing output... [ 54%] CoolWorld.shapes
writing output... [ 63%] CoolWorld.sounds
writing output... [ 72%] CoolWorld.tkinter_ui
writing output... [ 81%] CoolWorld.visual
writing output... [ 90%] CoolWorld.world
writing output... [100%] index

generating indices... genindex
writing additional pages... search
copying static files... WARNING: html_static_path entry '/home/docs/checkouts/readthedocs.org/user_builds/coolworld/checkouts/latest/docs/_static' does not exist
WARNING: html_static_path entry '/home/docs/checkouts/readthedocs.org/readthedocs/templates/sphinx/_static' does not exist
done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 12 warnings.
Copying readthedocs-dynamic-include.js_t... done
Copying readthedocs-data.js_t... done
```

The issue seems to be `ImportError: No module named 'CoolWorld'`.
Okay, let's try locally, maybe I made a mistake somewhere:
```sh
$ cd tmp
$ git clone https://github.com/tarball69/CoolWorld.git
$ cd CoolWorld/docs
$ make clean
$ make html
```
I have **python3-sphinx**>=1.3.1 deb package installed on an Ubuntu 15.10 desktop, no special tuning, all default options.
Here is the output log on `make html` building process:
```sh
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.3.1
making output directory...
loading translations [en]... done
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 11 source files that are out of date
updating environment: 11 added, 0 changed, 0 removed
reading sources... [100%] index                                                 
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] index                                                  
generating indices... genindex py-modindex
highlighting module code... [100%] CoolWorld.world                              
writing additional pages... search
copying static files... WARNING: html_static_path entry '/home/rs/tmp/CoolWorld/docs/_static' does not exist
done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 1 warning.

Build finished. The HTML pages are in _build/html.
```
So, all is quite clean locally.
When browsing to `_build/html/index.html` with my Chromium web browser, I get the stuff correctly done.
I have a default-generated `docs/conf.py` with a unique change on line 24:
```python
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# CoolWorld documentation build configuration file, created by
# sphinx-quickstart on Wed Nov 11 11:08:55 2015.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import sys
import os
import shlex

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#sys.path.insert(0, os.path.abspath('.'))
sys.path.insert(0, '../..')
```
I tried many options in *advanced settings* (using virtualenv and setup.py, using site-packages globally, etc.), all give the same result: build passes OK, but no documentation generated (because of the import error).
The 'CoolWorld' library package is **Python3**-oriented and cannot be generated through **python(2)-sphinx** executables. It needs **python3-sphinx** executables to work properly.
Do you think this issue could be fixed in any way?
Thanks a lot for your support. :+1: 
Regards.
tarball69.

**Comment by tarball69** [comment]
Okay, I fixed the problem.
Simply created a `docs/rtfd-requirements.txt` file with a single line: `CoolWorld` (package name).
Went to *advanced settings*, checked "use virtualenv", specified "docs/rtfd-requirements.txt" in requirement file form field and then it built OK.
RTD = cool concept. I like much. :+1: 
Regards.
tarball69.

**Comment by Chrislann1974** [comment]
Open

**Comment by Chrislann1974** [comment]
Patch
