### ISSUE TITLE
Completed build with no autodoc content due to ImportError on modules from the project itself

### ISSUE THREAD

**Issue by bskinn** [rtfd/readthedocs.org#1817]
I'm experiencing the same problem as #1814.

[RTD project](https://readthedocs.org/projects/opan/)
[GitHub project](https://www.github.com/bskinn/opan)
["Successful" build](https://readthedocs.org/projects/opan/builds/3484475/)

Representative errors from a problem build (branch `docdev`; this is a Python 2.7 project):

    /home/docs/checkouts/readthedocs.org/user_builds/opan/checkouts/docdev/doc/source/api/anharm.rst:7: WARNING: autodoc: failed to import module u'opan.anharm'; the following exception was raised:
    Traceback (most recent call last):
      File "/home/docs/checkouts/readthedocs.org/user_builds/opan/envs/docdev/local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
        __import__(self.modname)
    ImportError: No module named opan.anharm
    /home/docs/checkouts/readthedocs.org/user_builds/opan/checkouts/docdev/doc/source/api/const.rst:7: WARNING: autodoc: failed to import module u'opan.const'; the following exception was raised:
    Traceback (most recent call last):
      File "/home/docs/checkouts/readthedocs.org/user_builds/opan/envs/docdev/local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
        __import__(self.modname)
    ImportError: No module named opan.const

I've tried everything I can think of in terms of adding directories to `sys.path` that would be suitable roots for importing from the (sub-)packages, and nothing has made a difference.  I **am** able to compile the docs successfully on my local system even when I remove my root path (`C:\git`) from my `PYTHONPATH` environment variable.  (Without adding `os.path.abspath('../../..')` to `sys.path`, the docs DO NOT compile w/o the root path in `PYTHONPATH`, so I'm pretty sure I've got the path set okay in `conf.py`.)

I don't have my project on PyPI yet, so the solution of enabling the virtualenv and adding the `requirements.txt` file that worked to resolve #1814 appears not to be available to me without first getting it posted there.  As I'm still in relatively early development, posting to PyPI seems premature.

While I guess the above means that worrying about RTD builds working may also be premature, is there any way to make `autodoc` happy without getting PyPI set up?

**Comment by bskinn** [comment]
**RESOLVED:** I had structured my project directory improperly. Moving the code into its own package subdirectory made it play nice with RTD/autodoc.

I do still have the following in my `conf.py`, which may also be important:

    sys.path.insert(0, os.path.abspath('../..'))
