### ISSUE TITLE
Feature request: please consider enabling `repoze.sphinx.autointerface`

### ISSUE THREAD

**Issue by posita** [rtfd/readthedocs.org#1821]
For those projects that require [Twisted](http://twistedmatrix.com/) (or, more generally, [`zope.interface`](http://docs.zope.org/zope.interface/README.html)), [`repoze.sphinx.autointerface`](https://github.com/repoze/repoze.sphinx.autointerface) can be very helpful. Please consider enabling it on RTD to avoid build errors like these:

```py
Running Sphinx v1.3.1
making output directory...

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/txsocketio/envs/master/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 244, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/txsocketio/envs/master/local/lib/python2.7/site-packages/sphinx/application.py", line 143, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/txsocketio/envs/master/local/lib/python2.7/site-packages/sphinx/application.py", line 433, in setup_extension
    err)
ExtensionError: Could not import extension repoze.sphinx.autointerface (exception: No module named repoze.sphinx.autointerface)

Extension error:
Could not import extension repoze.sphinx.autointerface (exception: No module named repoze.sphinx.autointerface)
```

**Comment by posita** [comment]
After some thought, I'm pretty sure this should be closed as `INVALID`. RTD allows for installing packages via a `requirements.txt` file in a `virtualenv`. If you don't want to add doc-specific packages (like `repoze.sphinx.autointerface`) to your root-level `requirements.txt`, you can always do something like the following:

```
# requirements.txt
# <normal requirements go here> ...
```

```
# docs-requirements.txt
-r requirements.txt
repoze.sphinx.autointerface
```
