### ISSUE TITLE
Error importing module privacy.backends.syncers.DoubleRemotePuller with readthedocs.settings.postgres as DJANGO_SETTINGS_MODULE

### ISSUE THREAD

**Issue by saeedsq** [rtfd/readthedocs.org#1830]
With Python 2.7 and `DJANGO_SETTINGS_MODULE=readthedocs.settings.postgres`, after running these commands:

    pip install -r requirements/deploy.txt
    ./manage.py migrate

I got following error:

    Traceback (most recent call last):
      File "./manage.py", line 11, in <module>
        execute_from_command_line(sys.argv)
      File "/home/saeed/Envs/rtd/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
        utility.execute()
      File "/home/saeed/Envs/rtd/lib/python2.7/site-packages/django/core/management/__init__.py", line 312, in execute
        django.setup()
      File "/home/saeed/Envs/rtd/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
        apps.populate(settings.INSTALLED_APPS)
      File "/home/saeed/Envs/rtd/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
        app_config.import_models(all_models)
      File "/home/saeed/Envs/rtd/lib/python2.7/site-packages/django/apps/config.py", line 198, in import_models
          self.models_module = import_module(models_module_name)
        File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
          __import__(name)
        File "/home/saeed/Projects/readthedocs/readthedocs/bookmarks/models.py", line 5, in <module>
          from readthedocs.builds.models import Version
        File "/home/saeed/Projects/readthedocs/readthedocs/builds/models.py", line 14, in <module>
          from readthedocs.privacy.loader import (VersionManager, RelatedBuildManager,
        File "/home/saeed/Projects/readthedocs/readthedocs/privacy/loader.py", line 33, in <module>
          'readthedocs.privacy.backends.syncers.LocalSyncer'))
        File "/home/saeed/Envs/rtd/lib/python2.7/site-packages/django/utils/module_loading.py", line 50, in import_by_path
          sys.exc_info()[2])
        File "/home/saeed/Envs/rtd/lib/python2.7/site-packages/django/utils/module_loading.py", line 45, in import_by_path
          attr = import_string(dotted_path)
        File "/home/saeed/Envs/rtd/lib/python2.7/site-packages/django/utils/module_loading.py", line 26, in import_string
          module = import_module(module_path)
        File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
          __import__(name)
      django.core.exceptions.ImproperlyConfigured: Error importing module privacy.backends.syncers.DoubleRemotePuller: "No module named privacy.backends.syncers"

**Comment by agjohnson** [comment]
This settings file is going to be removed, it is a relic of our old production environment. If you need to use postgres, just override the database settings with a `local_settings` override.

**Comment by saeedsq** [comment]
I'm already using `local_settings`.
This is not just postgres, You should at least provide some templates for production environment setting or document it somewhere, I had to guess and test what settings will work for production environment at our own host. `DEBUG` is deeply used in your codes and setting it to `False` causes some problems to run the web application.

**Comment by agjohnson** [comment]
But we can't dictate anything about anyone else's production environment, so it just comes back to setting basic Django settings. If you are running an instance, you should be wholly familiar with Django project administration, and know what `DEBUG` does. Additional settings are documented here: http://docs.readthedocs.org/en/latest/settings.html
