### ISSUE TITLE
Sphinx documentation build always failing on Windows 

### ISSUE THREAD

**Issue by apalmer** [rtfd/readthedocs.org#1923]
I was able to get, build and launch readthedocs code successfully on Windows 7 Professional with Python2.7 .  

I am hosting the web site with the command 'python .\manage.py runserver' as per the installation guide. 

I am able to launch the website at localhost:8000 and was able to configure new project and configure documentation build successfully through the UI.

HOWEVER when documentation build actually launches it always. The log details are at the bottom of this. From what little i can tell it seems to be in readthedocs.org/readthedocs/doc_builder/python_environments.py the lines like this:
     self.venv_bin(version=self.version.slug, filename='pip') 
is returning a path like {install dir}\user_builds\{project}\envs\latest\bin\pip , which doesn't exist. It seems like the path {install dir}\user_builds\{project}\envs\latest\Scripts\pip.exe does exists. I am guessing this is related to virtualenv. 

Logs:
[13/Jan/2016 11:15:46] ERROR [readthedocs.doc_builder.environments:299] (Build) [compass-documentation:stable] Command python C:\rtd\checkouts\readthedocs.org\user_builds\compass-documentation\envs\stable\bin\pip install --use-wheel -U --cache-dir C:\rtd\checkouts\readthedocs.org\user_builds\compass-documentation\.cache\pip sphinx==1.3.1 Pygments==2.0.2 setuptools==18.6.1 docutils==0.11 mkdocs==0.14.0 mock==1.0.1 pillow==2.6.1 readthedocs-sphinx-ext==0.5.4 sphinx-rtd-theme==0.1.9 alabaster>=0.7,<0.8,!=0.7.5 commonmark==0.5.4 recommonmark==0.1.1 failed:
python: can't open file 'C:\rtd\checkouts\readthedocs.org\user_builds\compass-documentation\envs\stable\bin\pip': [Errno 2] No such file or directory

Traceback (most recent call last):
  File "C:\rtd\checkouts\readthedocs.org\readthedocs\projects\tasks.py", line 143, in run
    self.setup_environment()
  File "C:\rtd\checkouts\readthedocs.org\readthedocs\projects\tasks.py", line 244, in setup_environment
    self.python_env.install_core_requirements()
  File "C:\rtd\checkouts\readthedocs.org\readthedocs\doc_builder\python_environments.py", line 133, in install_core_requirements
    bin_path=self.venv_bin(version=self.version.slug)
  File "C:\rtd\checkouts\readthedocs.org\readthedocs\doc_builder\environments.py", line 310, in run
    return self.run_command_class(cls=self.command_class, cmd=cmd, **kwargs)
  File "C:\rtd\checkouts\readthedocs.org\readthedocs\doc_builder\environments.py", line 341, in run_command_class
    raise BuildEnvironmentWarning(msg)
BuildEnvironmentWarning: Command python C:\rtd\checkouts\readthedocs.org\user_builds\compass-documentation\envs\stable\bin\pip install --use-wheel -U --cache-dir C:\rtd\checkouts\readthedocs.org\user_builds\compass-documentation\.cache\pip sphinx==1.3.1 Pygments==2.0.2 setuptools==18.6.1 docutils==0.11 mkdocs==0.14.0 mock==1.0.1 pillow==2.6.1 readthedocs-sphinx-ext==0.5.4 sphinx-rtd-theme==0.1.9 alabaster>=0.7,<0.8,!=0.7.5 commonmark==0.5.4 recommonmark==0.1.1 failed:
python: can't open file 'C:\rtd\checkouts\readthedocs.org\user_builds\compass-documentation\envs\stable\bin\pip': [Errno 2] No such file or directory

[13/Jan/2016 11:15:48] INFO [readthedocs.doc_builder.environments:280] (Build) [compass-documentation:stable] Build finished

**Comment by ericholscher** [comment]
We don't support Read the Docs on Windows via our open source project. We do provide commercial support, if you're interested more information is here: http://docs.readthedocs.org/en/latest/support.html#commercial-support
