### ISSUE TITLE
readthedocs local install will not generate PDF docs -- please help!

### ISSUE THREAD

**Issue by brianjking** [rtfd/readthedocs.org#1936]
Hello,

I'm attempting to install a local copy of readthedocs and have followed the instructions online at [https://docs.readthedocs.org/en/latest/install.html](https://docs.readthedocs.org/en/latest/install.html). 

* This is running on an Ubuntu 15.10 VirtualBox install

When attempting to build any docs, including the readthedocs.org docs it seems to fail if I have PDF creation turned **ON**.

```
[15/Jan/2016 22:12:55] INFO [readthedocs.doc_builder.base:63] Copying sphinx on the local filesystem
[15/Jan/2016 22:12:56] INFO [readthedocs.doc_builder.base:74] Removing old artifact path: /home/bk/rtd/checkouts/readthedocs.org/user_builds/read-the-docs/checkouts/latest/docs/_build/json
[15/Jan/2016 22:12:56] INFO [readthedocs.doc_builder.environments:100] Running: 'python /home/bk/rtd/checkouts/readthedocs.org/user_builds/read-the-docs/envs/latest/bin/sphinx-build -T -b json -d _build/doctrees-json -D language=en . _build/json' [/home/bk/rtd/checkouts/readthedocs.org/user_builds/read-the-docs/checkouts/latest/docs]
[15/Jan/2016 22:13:19]"POST /api/v2/command/ HTTP/1.1" 201 8903
[15/Jan/2016 22:13:19] INFO [readthedocs.doc_builder.base:63] Copying sphinx_search on the local filesystem
[15/Jan/2016 22:13:19] INFO [readthedocs.doc_builder.base:74] Removing old artifact path: /home/bk/rtd/checkouts/readthedocs.org/user_builds/read-the-docs/checkouts/latest/docs/_build/localmedia
[15/Jan/2016 22:13:20] INFO [readthedocs.doc_builder.environments:100] Running: 'python /home/bk/rtd/checkouts/readthedocs.org/user_builds/read-the-docs/envs/latest/bin/sphinx-build -T -b readthedocssinglehtmllocalmedia -d _build/doctrees-readthedocssinglehtmllocalmedia -D language=en . _build/localmedia' [/home/bk/rtd/checkouts/readthedocs.org/user_builds/read-the-docs/checkouts/latest/docs]
[15/Jan/2016 22:13:37]"POST /api/v2/command/ HTTP/1.1" 201 7352
[15/Jan/2016 22:13:37] INFO [readthedocs.doc_builder.backends.sphinx:202] Creating zip file from /home/bk/rtd/checkouts/readthedocs.org/user_builds/read-the-docs/checkouts/latest/docs/_build/localmedia
[15/Jan/2016 22:13:37] INFO [readthedocs.doc_builder.environments:100] Running: 'python /home/bk/rtd/checkouts/readthedocs.org/user_builds/read-the-docs/envs/latest/bin/sphinx-build -b latex -D language=en -d _build/doctrees . _build/latex' [/home/bk/rtd/checkouts/readthedocs.org/user_builds/read-the-docs/checkouts/latest/docs]
[15/Jan/2016 22:13:59]"POST /api/v2/command/ HTTP/1.1" 201 12101
[15/Jan/2016 22:13:59] INFO [readthedocs.doc_builder.environments:100] Running: 'pdflatex -interaction=nonstopmode /home/bk/rtd/checkouts/readthedocs.org/user_builds/read-the-docs/checkouts/latest/docs/_build/latex/ReadTheDocs.tex' [/home/bk/rtd/checkouts/readthedocs.org/user_builds/read-the-docs/checkouts/latest/docs/_build/latex]
[15/Jan/2016 22:14:00]"POST /api/v2/command/ HTTP/1.1" 201 722
[15/Jan/2016 22:14:00] WARNING [readthedocs.doc_builder.environments:339] (Build) [read-the-docs:latest] Command pdflatex -interaction=nonstopmode /home/bk/rtd/checkouts/readthedocs.org/user_builds/read-the-docs/checkouts/latest/docs/_build/latex/ReadTheDocs.tex failed:
Traceback (most recent call last):
  File "/home/bk/rtd/checkouts/readthedocs.org/readthedocs/doc_builder/environments.py", line 134, in run
    env=environment,
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

[15/Jan/2016 22:14:00] INFO [readthedocs.doc_builder.environments:100] Running: 'makeindex -s python.ist ReadTheDocs.idx' [/home/bk/rtd/checkouts/readthedocs.org/user_builds/read-the-docs/checkouts/latest/docs/_build/latex]
[15/Jan/2016 22:14:00]"POST /api/v2/command/ HTTP/1.1" 201 619
[15/Jan/2016 22:14:00] WARNING [readthedocs.doc_builder.environments:339] (Build) [read-the-docs:latest] Command makeindex -s python.ist ReadTheDocs.idx failed:
Traceback (most recent call last):
  File "/home/bk/rtd/checkouts/readthedocs.org/readthedocs/doc_builder/environments.py", line 134, in run
    env=environment,
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

[15/Jan/2016 22:14:00] INFO [readthedocs.doc_builder.environments:100] Running: 'pdflatex -interaction=nonstopmode /home/bk/rtd/checkouts/readthedocs.org/user_builds/read-the-docs/checkouts/latest/docs/_build/latex/ReadTheDocs.tex' [/home/bk/rtd/checkouts/readthedocs.org/user_builds/read-the-docs/checkouts/latest/docs/_build/latex]
[15/Jan/2016 22:14:01]"POST /api/v2/command/ HTTP/1.1" 201 729
[15/Jan/2016 22:14:01] WARNING [readthedocs.doc_builder.environments:339] (Build) [read-the-docs:latest] Command pdflatex -interaction=nonstopmode /home/bk/rtd/checkouts/readthedocs.org/user_builds/read-the-docs/checkouts/latest/docs/_build/latex/ReadTheDocs.tex failed:
Traceback (most recent call last):
  File "/home/bk/rtd/checkouts/readthedocs.org/readthedocs/doc_builder/environments.py", line 134, in run
    env=environment,
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

[15/Jan/2016 22:14:02] INFO [readthedocs.core.utils:24] Running rm -rf /home/bk/rtd/checkouts/readthedocs.org/media/pdf/read-the-docs/latest/read-the-docs.pdf on app servers
[15/Jan/2016 22:14:02] INFO [readthedocs.core.utils:24] Running rm -rf /home/bk/rtd/checkouts/readthedocs.org/media/epub/read-the-docs/latest/read-the-docs.epub on app servers
[15/Jan/2016 22:14:03] INFO [readthedocs.core.utils:24] Running mkdir -p /home/bk/rtd/checkouts/readthedocs.org/user_builds/read-the-docs/translations on app servers
[15/Jan/2016 22:14:03] INFO [readthedocs.core.utils:24] Running ln -nsf /home/bk/rtd/checkouts/readthedocs.org/user_builds/read-the-docs/rtd-builds /home/bk/rtd/checkouts/readthedocs.org/user_builds/read-the-docs/translations/en on app servers
[15/Jan/2016 22:14:03] INFO [readthedocs.core.utils:24] Running rm -f /home/bk/rtd/checkouts/readthedocs.org/user_builds/read-the-docs/single_version on app servers
[15/Jan/2016 22:14:03] INFO [readthedocs.projects.tasks:732] (Build) [read-the-docs:] Updating static metadata
[15/Jan/2016 22:14:04] INFO [readthedocs.projects.tasks:551] (Search Index) Sending Data: read-the-docs [single_version badges builds features i18n issue-labels sponsors story webhooks embed alternate_domains design changelog conda open-source-philosophy faq vcs settings automatic-redirects talks index privacy install architecture versions user-defined-redirects contribute localization rtfd api tests canonical symlinks gsoc getting_started support theme yaml-config business/organizations business/analytics business/index business/sharing development/standards development/buildenvironments api/core api/builds api/bookmarks api/doc_builder api/projects api/index api/vcs_support custom_installs/customization custom_installs/local_rtd_vm custom_installs/index features/embed]
[15/Jan/2016 22:14:04] INFO [readthedocs.restapi.utils:90] (Server Search) Indexing Pages: read-the-docs [single_version badges builds features i18n issue-labels sponsors story webhooks embed alternate_domains design changelog conda open-source-philosophy faq vcs settings automatic-redirects talks index privacy install architecture versions user-defined-redirects contribute localization rtfd api tests canonical symlinks gsoc getting_started support theme yaml-config business/organizations business/analytics business/index business/sharing development/standards development/buildenvironments api/core api/builds api/bookmarks api/doc_builder api/projects api/index api/vcs_support custom_installs/customization custom_installs/local_rtd_vm custom_installs/index features/embed]
[15/Jan/2016 22:14:04] INFO [urllib3.connectionpool:207] Starting new HTTP connection (1): 127.0.0.1
[15/Jan/2016 22:14:04] WARNING [elasticsearch:82] PUT http://127.0.0.1:9200/readthedocs/project/1 [status:N/A request:0.002s]
Traceback (most recent call last):
  File "/home/bk/rtd/local/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 74, in perform_request
    response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)
  File "/home/bk/rtd/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 608, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/bk/rtd/local/lib/python2.7/site-packages/urllib3/util/retry.py", line 224, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/bk/rtd/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 558, in urlopen
    body=body, headers=headers)
  File "/home/bk/rtd/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 353, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 1052, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1092, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1048, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 892, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 854, in send
    self.connect()
  File "/home/bk/rtd/local/lib/python2.7/site-packages/urllib3/connection.py", line 162, in connect
    conn = self._new_conn()
  File "/home/bk/rtd/local/lib/python2.7/site-packages/urllib3/connection.py", line 146, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fd902dd4910>: Failed to establish a new connection: [Errno 111] Connection refused
[15/Jan/2016 22:14:04] INFO [urllib3.connectionpool:207] Starting new HTTP connection (2): 127.0.0.1
[15/Jan/2016 22:14:04] WARNING [elasticsearch:82] PUT http://127.0.0.1:9200/readthedocs/project/1 [status:N/A request:0.001s]
Traceback (most recent call last):
  File "/home/bk/rtd/local/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 74, in perform_request
    response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)
  File "/home/bk/rtd/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 608, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/bk/rtd/local/lib/python2.7/site-packages/urllib3/util/retry.py", line 224, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/bk/rtd/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 558, in urlopen
    body=body, headers=headers)
  File "/home/bk/rtd/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 353, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 1052, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1092, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1048, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 892, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 854, in send
    self.connect()
  File "/home/bk/rtd/local/lib/python2.7/site-packages/urllib3/connection.py", line 162, in connect
    conn = self._new_conn()
  File "/home/bk/rtd/local/lib/python2.7/site-packages/urllib3/connection.py", line 146, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fd902dd4710>: Failed to establish a new connection: [Errno 111] Connection refused
[15/Jan/2016 22:14:04] INFO [urllib3.connectionpool:207] Starting new HTTP connection (3): 127.0.0.1
[15/Jan/2016 22:14:04] WARNING [elasticsearch:82] PUT http://127.0.0.1:9200/readthedocs/project/1 [status:N/A request:0.002s]
Traceback (most recent call last):
  File "/home/bk/rtd/local/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 74, in perform_request
    response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)
  File "/home/bk/rtd/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 608, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/bk/rtd/local/lib/python2.7/site-packages/urllib3/util/retry.py", line 224, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/bk/rtd/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 558, in urlopen
    body=body, headers=headers)
  File "/home/bk/rtd/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 353, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 1052, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1092, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1048, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 892, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 854, in send
    self.connect()
  File "/home/bk/rtd/local/lib/python2.7/site-packages/urllib3/connection.py", line 162, in connect
    conn = self._new_conn()
  File "/home/bk/rtd/local/lib/python2.7/site-packages/urllib3/connection.py", line 146, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fd902dd4690>: Failed to establish a new connection: [Errno 111] Connection refused
[15/Jan/2016 22:14:04] INFO [urllib3.connectionpool:207] Starting new HTTP connection (4): 127.0.0.1
[15/Jan/2016 22:14:04] WARNING [elasticsearch:82] PUT http://127.0.0.1:9200/readthedocs/project/1 [status:N/A request:0.001s]
Traceback (most recent call last):
  File "/home/bk/rtd/local/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 74, in perform_request
    response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)
  File "/home/bk/rtd/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 608, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/bk/rtd/local/lib/python2.7/site-packages/urllib3/util/retry.py", line 224, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/bk/rtd/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 558, in urlopen
    body=body, headers=headers)
  File "/home/bk/rtd/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 353, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 1052, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1092, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1048, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 892, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 854, in send
    self.connect()
  File "/home/bk/rtd/local/lib/python2.7/site-packages/urllib3/connection.py", line 162, in connect
    conn = self._new_conn()
  File "/home/bk/rtd/local/lib/python2.7/site-packages/urllib3/connection.py", line 146, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fd902dd4910>: Failed to establish a new connection: [Errno 111] Connection refused
[15/Jan/2016 22:14:04]"PUT /api/v2/build/14/ HTTP/1.1" 200 84962
[15/Jan/2016 22:14:04] INFO [readthedocs.doc_builder.environments:280] (Build) [read-the-docs:latest] Build finished
[15/Jan/2016 22:14:04]"POST /dashboard/read-the-docs/advanced/ HTTP/1.1" 302 0
[15/Jan/2016 22:14:05]"GET /projects/read-the-docs/ HTTP/1.1" 200 14267
[15/Jan/2016 22:14:07]"GET /projects/read-the-docs/badge/?version=latest HTTP/1.1" 302 0
[15/Jan/2016 22:14:20]"GET /projects/read-the-docs/builds/ HTTP/1.1" 200 11641
[15/Jan/2016 22:14:22]"GET /static/core/img/loader.gif HTTP/1.1" 304 0
[15/Jan/2016 22:14:28]"GET /projects/read-the-docs/builds/14/ HTTP/1.1" 200 10954
[15/Jan/2016 22:14:30]"GET /static/builds/css/detail.css HTTP/1.1" 304 0
[15/Jan/2016 22:14:30]"GET /static/vendor/knockout.js HTTP/1.1" 304 0
[15/Jan/2016 22:14:30]"GET /static/builds/js/detail.js HTTP/1.1" 304 0
[15/Jan/2016 22:14:30]"GET /api/v2/build/14/ HTTP/1.1" 200 84962
```

**Comment by agjohnson** [comment]
As the error states, you're missing `pdflatex`. Make sure to install `latex` and related packages.

**Comment by brianjking** [comment]
@agjohnson Via ````sudo apt-get install texlive````?

Thanks!

**Comment by agjohnson** [comment]
Correct, that's the one.

**Comment by agjohnson** [comment]
Closing, but feel free to reopen if those aren't the only dependencies you need.
