### ISSUE TITLE
Unable to launch local instance with gunicorn

### ISSUE THREAD

**Issue by HarryRybacki** [rtfd/readthedocs.org#2043]
## Details
While attempting to launch an instance of readthedocs with gunicorn I'm running into an odd import error. 

### System info:
* Operating System: Fedora22

## Steps to reproduce:
1. git clone https://github.com/rtfd/readthedocs.org.git 
2. cd ./readthedocs.org && git reset --hard bc1decf4524c8a876c344d08d2da42aeeea19c72  # running the latest version will leave all builds stuck in a *triggerd* state indefintely (can't find any useful log to debug)
3. pip install -r requirements.txt
4. pip install gunicorn
5. ./manage.py migrate
6. ./manage.py createsuperuser
7. ./manage.py collectstatic
8. ./manage.py loaddata test_data
9. gunicorn readthedocs.wsgi

## Expected output:
    ...
    Starting development server at http://127.0.0.1:8000/
    Quit the server with CONTROL-C.

## Actual output:
    [root@<host> readthedocs.org]# gunicorn readthedocs.wsgi
    [2016-03-02 14:59:44 +0000] [6616] [INFO] Starting gunicorn 19.4.5
    [2016-03-02 14:59:44 +0000] [6616] [INFO] Listening at: http://127.0.0.1:8000 (6616)
    [2016-03-02 14:59:44 +0000] [6616] [INFO] Using worker: sync
    [2016-03-02 14:59:44 +0000] [6621] [INFO] Booting worker with pid: 6621
    [2016-03-02 14:59:45 +0000] [6621] [ERROR] Exception in worker process:
    Traceback (most recent call last):
      File "/root/rtd/venv/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
      File "/root/rtd/venv/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
      File "/root/rtd/venv/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
      File "/root/rtd/venv/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
      File "/root/rtd/venv/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
      File "/root/rtd/venv/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
      File "/root/rtd/venv/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
      File "/root/rtd/readthedocs.org/readthedocs/wsgi.py", line 9, in <module>
    application = get_wsgi_application()
      File "/root/rtd/venv/lib/python2.7/site-packages/django/core/wsgi.py", line 14, in get_wsgi_application
    django.setup()
      File "/root/rtd/venv/lib/python2.7/site-packages/django/__init__.py", line 17, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
      File "/root/rtd/venv/lib/python2.7/site-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
      File "/root/rtd/venv/lib/python2.7/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
      File "/root/rtd/venv/lib/python2.7/site-packages/django/conf/__init__.py", line 92, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
      File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
    ImportError: No module named settings.postgres
    Traceback (most recent call last):
      File "/root/rtd/venv/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
      File "/root/rtd/venv/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
      File "/root/rtd/venv/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
      File "/root/rtd/venv/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
     File "/root/rtd/venv/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
      File "/root/rtd/venv/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
      File "/root/rtd/venv/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
      File "/root/rtd/readthedocs.org/readthedocs/wsgi.py", line 9, in <module>
    application = get_wsgi_application()
      File "/root/rtd/venv/lib/python2.7/site-packages/django/core/wsgi.py", line 14, in get_wsgi_application
    django.setup()
      File "/root/rtd/venv/lib/python2.7/site-packages/django/__init__.py", line 17, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
      File "/root/rtd/venv/lib/python2.7/site-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
      File "/root/rtd/venv/lib/python2.7/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
      File "/root/rtd/venv/lib/python2.7/site-packages/django/conf/__init__.py", line 92, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
      File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
    ImportError: No module named settings.postgres
    [2016-03-02 14:59:45 +0000] [6621] [INFO] Worker exiting (pid: 6621)
    [2016-03-02 14:59:46 +0000] [6616] [INFO] Shutting down: Master
    [2016-03-02 14:59:46 +0000] [6616] [INFO] Reason: Worker failed to boot.

**Comment by agjohnson** [comment]
The error

```
ImportError: No module named settings.postgres
```

implies you aren't able to import the settings file. Try `readthedocs.settings.postgres`

**Comment by HarryRybacki** [comment]
@agjohnson yep, modifying `readthedocs/wsgi.py` accordingly worked straight away. Thanks!

**Comment by HarryRybacki** [comment]
Issue resolved

**Comment by radkin** [comment]
@HarryRybacki please let us know your modification. When I tried changing
```bash
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "settings.postgres")
```
to
```bash
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "readthedocs.settings.postgres")
```
it had the same error.
