### ISSUE TITLE
Unable to run a doc build locally

### ISSUE THREAD

**Issue by thereapman** [rtfd/readthedocs.org#2154]
## Details

I want to look into contributing to readthedocs and started setting up my local version.
Now i'm stuck at a point i can't get the hang of it.

when i trigger a build from the webgui i get the following output in the console of the dev webserver.
I assume it could by caused by faulty line endings that it `can't cd to root/rtd/checkouts/readthedocs.org` but i don't find the location this command is comming from. 

```
[21/Apr/2016 01:27:44] ERROR [readthedocs.doc_builder.environments:309] (Build) [pip:latest] Command python -mvirtualenv --no-site-packages /root/rtd/checkouts/readthedocs.org/user_builds/pip/envs/latest failed:
/bin/sh: 1: cd: can't cd to /root/rtd/checkouts/readthedocs.org
Traceback (most recent call last):
  File "/root/rtd/checkouts/readthedocs.org/readthedocs/projects/tasks.py", line 165, in run
    self.setup_environment()
  File "/root/rtd/checkouts/readthedocs.org/readthedocs/projects/tasks.py", line 301, in setup_environment
    self.python_env.setup_base()
  File "/root/rtd/checkouts/readthedocs.org/readthedocs/doc_builder/python_environments.py", line 97, in setup_base
    bin_path=None,  # Don't use virtualenv bin that doesn't exist yet
  File "/root/rtd/checkouts/readthedocs.org/readthedocs/doc_builder/environments.py", line 320, in run
    return self.run_command_class(cls=self.command_class, cmd=cmd, **kwargs)
  File "/root/rtd/checkouts/readthedocs.org/readthedocs/doc_builder/environments.py", line 357, in run_command_class
    raise BuildEnvironmentWarning(msg)
BuildEnvironmentWarning: Command python -mvirtualenv --no-site-packages /root/rtd/checkouts/readthedocs.org/user_builds/pip/envs/latest failed:
/bin/sh: 1: cd: can't cd to /root/rtd/checkouts/readthedocs.org
```

**Comment by thereapman** [comment]
I got it figured out. I had DOCKER_ENABLE = True and this then failed becaus the commands din't find stuff inside the docker container.
