### ISSUE TITLE
pygments_style = 'python' not working

### ISSUE THREAD

**Issue by stuaxo** [rtfd/readthedocs.org#2168]
Build: 3945953
Project: shoebot-test-rtd

For some reason pygments_style = 'python' doesn't seem to work:

```

cat conf.py
python /home/docs/checkouts/readthedocs.org/user_builds/shoebot-test-rtd/envs/master/bin/sphinx-build -T -E -b readthedocs -d _build/doctrees-readthedocs -D language=en . _build/html
Running Sphinx v1.3.5
making output directory...
loading translations [en]... done

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/shoebot-test-rtd/envs/master/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 243, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/shoebot-test-rtd/envs/master/local/lib/python2.7/site-packages/sphinx/application.py", line 189, in __init__
    self._init_builder(self.buildername)
  File "/home/docs/checkouts/readthedocs.org/user_builds/shoebot-test-rtd/envs/master/local/lib/python2.7/site-packages/sphinx/application.py", line 251, in _init_builder
    self.builder = builderclass(self)
  File "/home/docs/checkouts/readthedocs.org/user_builds/shoebot-test-rtd/envs/master/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 87, in __init__
    self.init()
  File "/home/docs/checkouts/readthedocs.org/user_builds/shoebot-test-rtd/envs/master/local/lib/python2.7/site-packages/sphinx/builders/html.py", line 107, in init
    self.init_highlighter()
  File "/home/docs/checkouts/readthedocs.org/user_builds/shoebot-test-rtd/envs/master/local/lib/python2.7/site-packages/sphinx/builders/html.py", line 155, in init_highlighter
    self.config.trim_doctest_flags)
  File "/home/docs/checkouts/readthedocs.org/user_builds/shoebot-test-rtd/envs/master/local/lib/python2.7/site-packages/sphinx/highlighting.py", line 78, in __init__
    style = get_style_by_name(stylename)
  File "/home/docs/checkouts/readthedocs.org/user_builds/shoebot-test-rtd/envs/master/local/lib/python2.7/site-packages/pygments/styles/__init__.py", line 64, in get_style_by_name
    (builtin and ", though it should be builtin") + ".")
ClassNotFound: Could not find style module 'python'.

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/shoebot-test-rtd/envs/master/local/lib/python2.7/site-packages/pygments/styles/__init__.py", line 64, in get_style_by_name
    (builtin and ", though it should be builtin") + ".")
ClassNotFound: Could not find style module 'python'.
The full traceback has been saved in /tmp/sphinx-err-GVFqUg.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Command time: 1s Return: 1
```

**Comment by stuaxo** [comment]
Closing. - this was my lack of sphinx knowledge.
