### ISSUE TITLE
Search working in documents but not in the project Home.

### ISSUE THREAD

**Issue by carukc** [rtfd/readthedocs.org#2174]
Hello, 

I've created a build of ReadTheDocs and have pretty much everything working.

Strangely I seem to be able to search in the document itself but a search in the doc management pages does not return any results.

I am seeing a search related  warning when I build (included below).

Do I need to create an index in Elastic for the combined index?  I am using commonmark… Would that cause a problem with the combined index?

Is this a known issue or have I configured something incorrectly?   It seems really strange that search would work in the document itself but not in the main site.

Please assist.
Thanks
Chris

[27/Apr/2016 15:18:18] ERROR [celery.worker.job:282] Task readthedocs.projects.tasks.update_search[e44ad4f9-074f-4931-b6fe-16829d29ff39] raised unexpected: RequestError(400, u'illegal_argument_exception', {u'status': 400, u'error': {u'root_cause': [{u'reason': u"Can't specify parent if no parent field has been configured", u'type': u'illegal_argument_exception'}], u'type': u'illegal_argument_exception', u'reason': u"Can't specify parent if no parent field has been configured"}})
Traceback (most recent call last):
  File "/venv/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(_args, *_kwargs)
  File "/venv/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in **protected_call**
    return self.run(_args, *_kwargs)
  File "/app/readthedocs/projects/tasks.py", line 561, in update_search
    delete=delete_non_commit_files,
  File "/app/readthedocs/restapi/utils.py", line 144, in index_search_request
    page_obj.bulk_index(index_list, parent=project.slug)
  File "/app/readthedocs/search/indexes.py", line 140, in bulk_index
    bulk_index(self.es, docs, chunk_size=chunk_size)
  File "/venv/local/lib/python2.7/site-packages/elasticsearch/helpers/**init**.py", line 182, in bulk
    for ok, item in streaming_bulk(client, actions, **kwargs):
  File "/venv/local/lib/python2.7/site-packages/elasticsearch/helpers/**init**.py", line 124, in streaming_bulk
    raise e
RequestError: TransportError(400, u'illegal_argument_exception')

**Comment by agjohnson** [comment]
Yeah, you need elastic search. Our docs go through the required setup there.

**Comment by carukc** [comment]
Thanks.. I think that there must be something that I am not understanding re the setup instructions.

I've got icu working but it looks like I also have to execute some python.  I'll try to figure out how to do that next.

Thanks
Chris

**Comment by stsewd** [comment]
There is the same issue reported here #3803 with more up to date information and also there is a PR in progress for adding the documentation #3881 

So closing this in favor of the other one
