### ISSUE TITLE
ImportError: No module named 'pip._vendor'

### ISSUE THREAD

**Issue by jluttine** [rtfd/readthedocs.org#2189]
I'm not able to build my project. It fails at the first step. I've tried wiping the environment but it doesn't help. This error is confusing to me because if it doesn't do anything project specific at the first step, if I understand correctly. That is, I have no idea how I can even try to affect what is done at the first step.

## Details

Error message:
```
Using base prefix '/usr'
New python executable in /home/docs/checkouts/readthedocs.org/user_builds/bayespy/envs/latest/bin/python3
Not overwriting existing python script /home/docs/checkouts/readthedocs.org/user_builds/bayespy/envs/latest/bin/python (you must use /home/docs/checkouts/readthedocs.org/user_builds/bayespy/envs/latest/bin/python3)
Installing setuptools, pip, wheel...
  Complete output from command /home/docs/checkouts...s/latest/bin/python3 - setuptools pip wheel:
  Traceback (most recent call last):
  File "<stdin>", line 9, in <module>
  File "/usr/lib/python3.4/pkgutil.py", line 611, in get_data
    spec = importlib.util.find_spec(package)
  File "/home/docs/checkouts/readthedocs.org/user_builds/bayespy/envs/latest/lib/python3.4/importlib/util.py", line 86, in find_spec
    parent = __import__(parent_name, fromlist=['__path__'])
ImportError: No module named 'pip._vendor'
----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.4/dist-packages/virtualenv.py", line 2316, in <module>
    main()
  File "/usr/local/lib/python3.4/dist-packages/virtualenv.py", line 708, in main
    symlink=options.symlink)
  File "/usr/local/lib/python3.4/dist-packages/virtualenv.py", line 941, in create_environment
    download=download,
  File "/usr/local/lib/python3.4/dist-packages/virtualenv.py", line 897, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/usr/local/lib/python3.4/dist-packages/virtualenv.py", line 792, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /home/docs/checkouts...s/latest/bin/python3 - setuptools pip wheel failed with error code 1
```

If this issue is for a specific project or build, include the following:

* Project: bayespy
* Build #: 3969868

https://readthedocs.org/projects/bayespy/builds/3969868/

**Comment by jluttine** [comment]
I'm not sure what exactly fixed this issue but it seems to work now. I wiped my environments and put the requirement to setup.py and chose to install my package to the virtual environment in the settings.
