### ISSUE TITLE
ImportError: No module named 'pip._vendor'

### ISSUE THREAD

**Issue by alimanfoo** [rtfd/readthedocs.org#2197]
## Details

If this issue is for a specific project or build, include the following:
- Project: Zarr
- Build #: #3976363

Recent builds are failing when trying to execute the first step to create a virtual environment:

```
python3 -mvirtualenv --system-site-packages /home/docs/checkouts/readthedocs.org/user_builds/zarr/envs/refactor
```

...with the following error message:

```
Using base prefix '/usr'
New python executable in /home/docs/checkouts/readthedocs.org/user_builds/zarr/envs/refactor/bin/python3
Not overwriting existing python script /home/docs/checkouts/readthedocs.org/user_builds/zarr/envs/refactor/bin/python (you must use /home/docs/checkouts/readthedocs.org/user_builds/zarr/envs/refactor/bin/python3)
Installing setuptools, pip, wheel...
  Complete output from command /home/docs/checkouts...refactor/bin/python3 - setuptools pip wheel:
  Traceback (most recent call last):
  File "<stdin>", line 9, in <module>
  File "/usr/lib/python3.4/pkgutil.py", line 611, in get_data
    spec = importlib.util.find_spec(package)
  File "/home/docs/checkouts/readthedocs.org/user_builds/zarr/envs/refactor/lib/python3.4/importlib/util.py", line 86, in find_spec
    parent = __import__(parent_name, fromlist=['__path__'])
ImportError: No module named 'pip._vendor'
----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.4/dist-packages/virtualenv.py", line 2316, in <module>
    main()
  File "/usr/local/lib/python3.4/dist-packages/virtualenv.py", line 708, in main
    symlink=options.symlink)
  File "/usr/local/lib/python3.4/dist-packages/virtualenv.py", line 941, in create_environment
    download=download,
  File "/usr/local/lib/python3.4/dist-packages/virtualenv.py", line 897, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/usr/local/lib/python3.4/dist-packages/virtualenv.py", line 792, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /home/docs/checkouts...refactor/bin/python3 - setuptools pip wheel failed with error code 1
```

**Comment by agjohnson** [comment]
Do you have any luck building with python3 if you first wipe the version from the version admin page and then switch the interpreter to python3?

**Comment by alimanfoo** [comment]
Hi @agjohnson, I switched back to building with Python 2 to work around this. Sorry I don't have time to investigate currently.

**Comment by agjohnson** [comment]
I'm going to close this then. We've made a number of changes to the build images that build documentation, perhaps any of these changes might solve this. If you ever get back to testing this, feel free to reopen if this is still a problem.
