### ISSUE TITLE
RuntimeError building with mkdocs and Python 3

### ISSUE THREAD

**Issue by jacebrowning** [rtfd/readthedocs.org#2225]
## Details

* Project URL: https://readthedocs.org/projects/gitman
* Build URL (if applicable): https://readthedocs.org/projects/gitman/builds/4037411/
* Read the Docs username (if applicable): jacebrowning

One of my projects has a dependency that requires Python 3, so I selected a `CPython 3.x` interpreter for my project documented using `mkdocs`.

## Excepted Result

`mkdocs` succeeds in building the site, as it does locally.

## Actual Result

`click` (a dependency of `mkdocs`) raises a `RunTime` error during the build:

```
python3 -mvirtualenv --no-site-packages /home/docs/checkouts/readthedocs.org/user_builds/gitman/envs/latest
python /home/docs/checkouts/readthedocs.org/user_builds/gitman/envs/latest/bin/pip install --use-wheel -U --cache-dir /home/docs/checkouts/readthedocs.org/user_builds/gitman/.cache/pip sphinx==1.3.5 Pygments==2.1.3 setuptools==20.1.1 docutils==0.12 mkdocs==0.15.0 mock==1.0.1 pillow==2.6.1 git+https://github.com/rtfd/readthedocs-sphinx-ext.git@0.6-alpha#egg=readthedocs-sphinx-ext sphinx-rtd-theme==0.1.9 alabaster>=0.7,<0.8,!=0.7.5 commonmark==0.5.4 recommonmark==0.1.1
python /home/docs/checkouts/readthedocs.org/user_builds/gitman/envs/latest/bin/pip install --exists-action=w --cache-dir /home/docs/checkouts/readthedocs.org/user_builds/gitman/.cache/pip -r/home/docs/checkouts/readthedocs.org/user_builds/gitman/checkouts/latest/requirements.txt
python /home/docs/checkouts/readthedocs.org/user_builds/gitman/envs/latest/bin/mkdocs build --clean --site-dir _build/html --theme readthedocs
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/gitman/envs/latest/bin/mkdocs", line 11, in <module>
    sys.exit(cli())
  File "/home/docs/checkouts/readthedocs.org/user_builds/gitman/envs/latest/lib/python3.4/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/gitman/envs/latest/lib/python3.4/site-packages/click/core.py", line 675, in main
    _verify_python3_env()
  File "/home/docs/checkouts/readthedocs.org/user_builds/gitman/envs/latest/lib/python3.4/site-packages/click/_unicodefun.py", line 119, in _verify_python3_env
    'mitigation steps.' + extra)
RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment.  Either run this under Python 2 or consult http://click.pocoo.org/python3/ for mitigation steps.

This system supports the C.UTF-8 locale which is recommended.
You might be able to resolve your issue by exporting the
following environment variables:

    export LC_ALL=C.UTF-8
    export LANG=C.UTF-8
```

**Comment by berkerpeksag** [comment]
@jacebrowning could you please try again? If I'm not mistaken, https://github.com/rtfd/readthedocs-docker-images/issues/12 is now deployed so this is likely resolved now (at least I haven't had problem win my dev setup :)). Thanks!

**Comment by jacebrowning** [comment]
Yes, that seems to be working. Thanks!
