### ISSUE TITLE
[ExtensionError]: Could not import extension sphinx.ext.githubpages

### ISSUE THREAD

**Issue by loicgasser** [rtfd/readthedocs.org#2269]
## Details

* Project URL: http://quantized-mesh-tile.readthedocs.org/
* Build URL (if applicable):https://readthedocs.org/projects/quantized-mesh-tile/builds/4118363/
* Read the Docs username (if applicable): loicgasser4

## Expected Result

The build is successful.

## Actual Result

while executing this command.

`python /home/docs/checkouts/readthedocs.org/user_builds/quantized-mesh-tile/envs/latest/bin/sphinx-build -T -b readthedocs -d _build/doctrees-readthedocs -D language=en . _build/html`

I keep getting the same error:

```python
Running Sphinx v1.3.5
making output directory...

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/quantized-mesh-tile/envs/latest/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 243, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/quantized-mesh-tile/envs/latest/local/lib/python2.7/site-packages/sphinx/application.py", line 144, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/quantized-mesh-tile/envs/latest/local/lib/python2.7/site-packages/sphinx/application.py", line 435, in setup_extension
    err)
ExtensionError: Could not import extension sphinx.ext.githubpages (exception: No module named githubpages)

Extension error:
Could not import extension sphinx.ext.githubpages (exception: No module named githubpages)
```

I have tried a couple of things but no luck so far.

**Comment by loicgasser** [comment]
Ok I removed the tag `sphinx.ext.githubpage` from my extensions in my `conf.py` (a default extension when creating a new sphinx doc project) and it now works.
Aren't you reading those per default?
Anyway, thank you very much for this great service.

**Comment by ericholscher** [comment]
This is new in 1.4, you're using 1.3.
