### ISSUE TITLE
Build fails if needs_sphinx = '1.4'

### ISSUE THREAD

**Issue by dahlia** [rtfd/readthedocs.org#2280]
## Details

* Project URL: <https://readthedocs.org/projects/sqlalchemy-imageattach/>
* Build URL (if applicable): <https://readthedocs.org/projects/sqlalchemy-imageattach/builds/4152529/>
* Read the Docs username (if applicable): `dahlia`

## Expected Result

Since my docs became to require Sphinx 1.4 at least, I specified `needs_sphinx = '1.4'` in docs/conf.py.  I expected the docs will be built with Sphinx 1.4 (or higher) by RTD.

## Actual Result

The build failed with the following error:

```pytb
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/sqlalchemy-imageattach/envs/latest/local/lib/python3.4/site-packages/sphinx/cmdline.py", line 243, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/sqlalchemy-imageattach/envs/latest/local/lib/python3.4/site-packages/sphinx/application.py", line 165, in __init__
    'be built with this version.' % self.config.needs_sphinx)
sphinx.errors.VersionRequirementError: This project needs at least Sphinx v1.4 and therefore cannot be built with this version.
```

**Comment by ericholscher** [comment]
You can specify a Sphinx version in your requirements.txt

**Comment by dahlia** [comment]
[It does work well now!][1]  Thank you!

[1]: https://readthedocs.org/projects/sqlalchemy-imageattach/builds/4155265/
