### ISSUE TITLE
Error: underlying buffer has been detached

### ISSUE THREAD

**Issue by astrofrog** [rtfd/readthedocs.org#2316]
## Details
- Project URL: https://github.com/glue-viz/glue
- Build URL (if applicable): https://readthedocs.org/projects/glueviz/builds/4203556/
- Read the Docs username (if applicable): @astrofrog
## Expected Result

The build should run and succeed every time.
## Actual Result

The following error occurs non-deterministically (it sometimes happens, but not always):

```
Running Sphinx v1.3.5
making output directory...

Installed /home/docs/checkouts/readthedocs.org/user_builds/glueviz/checkouts/stable/doc/.eggs/astropy_helpers-1.2-py3.5.egg
/home/docs/checkouts/readthedocs.org/user_builds/glueviz/conda/stable/lib/python3.5/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
/home/docs/checkouts/readthedocs.org/user_builds/glueviz/conda/stable/lib/python3.5/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
/home/docs/checkouts/readthedocs.org/user_builds/glueviz/conda/stable/lib/python3.5/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
/home/docs/checkouts/readthedocs.org/user_builds/glueviz/conda/stable/lib/python3.5/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/glueviz/conda/stable/lib/python3.5/site-packages/Sphinx-1.3.5-py3.5.egg/sphinx/cmdline.py", line 243, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/glueviz/conda/stable/lib/python3.5/site-packages/Sphinx-1.3.5-py3.5.egg/sphinx/application.py", line 183, in __init__
    self._init_i18n()
  File "/home/docs/checkouts/readthedocs.org/user_builds/glueviz/conda/stable/lib/python3.5/site-packages/Sphinx-1.3.5-py3.5.egg/sphinx/application.py", line 197, in _init_i18n
    self.config.language), nonl=True)
  File "/home/docs/checkouts/readthedocs.org/user_builds/glueviz/conda/stable/lib/python3.5/site-packages/Sphinx-1.3.5-py3.5.egg/sphinx/application.py", line 334, in info
    self._log(message, self._status, nonl)
  File "/home/docs/checkouts/readthedocs.org/user_builds/glueviz/conda/stable/lib/python3.5/site-packages/Sphinx-1.3.5-py3.5.egg/sphinx/application.py", line 291, in _log
    wfile.write(message)
ValueError: underlying buffer has been detached

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/glueviz/conda/stable/lib/python3.5/site-packages/Sphinx-1.3.5-py3.5.egg/sphinx/application.py", line 291, in _log
    wfile.write(message)
ValueError: underlying buffer has been detached
The full traceback has been saved in /tmp/sphinx-err-ylxmdyde.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

**Comment by willingc** [comment]
Hi @astrofrog, Do you have a link to the environment.yml and rtd.yml that you have been using?

**Comment by astrofrog** [comment]
@willingc - yep, they are the latest ones in https://github.com/glue-viz/glue

**Comment by humitos** [comment]
@astrofrog is this still an issue for you? I saw that the last buildings are passing.

**Comment by humitos** [comment]
Closing. Feel free to reopen if you consider.
