### ISSUE TITLE
RuntimeError for numpy version?

### ISSUE THREAD

**Issue by bmorris3** [rtfd/readthedocs.org#2336]
## Details

* Project URL: https://github.com/bmorris3/shampoo
* Build URL (if applicable): https://readthedocs.org/projects/shampoo/builds/4238576/
* Read the Docs username (if applicable): bmorris3

## Expected Result

I'm trying to build some docs that depend on numpy and scikit-image.

## Actual Result

The following is the output of the build:

```
Running Sphinx v1.3.5
making output directory...

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/shampoo/envs/latest/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 243, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/shampoo/envs/latest/local/lib/python2.7/site-packages/sphinx/application.py", line 127, in __init__
    confoverrides or {}, self.tags)
  File "/home/docs/checkouts/readthedocs.org/user_builds/shampoo/envs/latest/local/lib/python2.7/site-packages/sphinx/config.py", line 277, in __init__
    execfile_(filename, config)
  File "/home/docs/checkouts/readthedocs.org/user_builds/shampoo/envs/latest/local/lib/python2.7/site-packages/sphinx/util/pycompat.py", line 128, in execfile_
    exec_(code, _globals)
  File "/usr/lib/python2.7/dist-packages/six.py", line 549, in exec_
    exec("""exec _code_ in _globs_, _locs_""")
  File "<string>", line 1, in <module>
  File "conf.py", line 105, in <module>
    __import__(setup_cfg['package_name'])
  File "/home/docs/checkouts/readthedocs.org/user_builds/shampoo/envs/latest/local/lib/python2.7/site-packages/shampoo-0.1.dev119-py2.7.egg/shampoo/__init__.py", line 8, in <module>
    from .reconstruction import *
  File "/home/docs/checkouts/readthedocs.org/user_builds/shampoo/envs/latest/local/lib/python2.7/site-packages/shampoo-0.1.dev119-py2.7.egg/shampoo/reconstruction.py", line 19, in <module>
    from .vis import save_scaled_image
  File "/home/docs/checkouts/readthedocs.org/user_builds/shampoo/envs/latest/local/lib/python2.7/site-packages/shampoo-0.1.dev119-py2.7.egg/shampoo/vis.py", line 5, in <module>
    from skimage.io import imsave
  File "/home/docs/checkouts/readthedocs.org/user_builds/shampoo/envs/latest/local/lib/python2.7/site-packages/skimage/io/__init__.py", line 7, in <module>
    from .manage_plugins import *
  File "/home/docs/checkouts/readthedocs.org/user_builds/shampoo/envs/latest/local/lib/python2.7/site-packages/skimage/io/manage_plugins.py", line 28, in <module>
    from .collection import imread_collection_wrapper
  File "/home/docs/checkouts/readthedocs.org/user_builds/shampoo/envs/latest/local/lib/python2.7/site-packages/skimage/io/collection.py", line 14, in <module>
    from ..external.tifffile import TiffFile
  File "/home/docs/checkouts/readthedocs.org/user_builds/shampoo/envs/latest/local/lib/python2.7/site-packages/skimage/external/tifffile/__init__.py", line 1, in <module>
    from .tifffile import imsave, imread, imshow, TiffFile, TiffWriter, TiffSequence
  File "/home/docs/checkouts/readthedocs.org/user_builds/shampoo/envs/latest/local/lib/python2.7/site-packages/skimage/external/tifffile/tifffile.py", line 153, in <module>
    from . import _tifffile
RuntimeError: module compiled against API version a but this version of numpy is 9

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/shampoo/envs/latest/local/lib/python2.7/site-packages/skimage/external/tifffile/tifffile.py", line 153, in <module>
    from . import _tifffile
RuntimeError: module compiled against API version a but this version of numpy is 9
The full traceback has been saved in /tmp/sphinx-err-DkNW32.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Segmentation fault
```

Both numpy and scikit-image should be built and installed by pip, so I don't understand where the failure is coming from.

**Comment by bmorris3** [comment]
This was resolved by installing scikit-image via Anaconda rather than pip.
