### ISSUE TITLE
Custom conf.py is ignored?

### ISSUE THREAD

**Issue by toomanybrians** [rtfd/readthedocs.org#2376]
I'm trying to get rtd to build with a custom `conf.py` file called `rtd-conf.py`, but it seems to be ignoring that setting? The build log shows a successful cat of `rtd-conf.py` (with the proper file contents), but then the sphinx-build process gives an error which shows that it's using `conf.py` and not `rtd_conf.py`. (The reason for the custom file is we're experimenting with rtd to see if we want to switch to it from our current docs site.

## Details

* Project URL: https://github.com/missionpinball/mpf-docs
* Build URL (if applicable): https://readthedocs.org/projects/mpf/builds/4313881/
* Read the Docs username (if applicable): brianmadden

## Expected Result

sphinx-build should use `rtd-conf.py`

## Actual Result

sphinx-build appears to be using `conf.py`

From the build log step `cat rtd_conf.py`, line 18:

`# import sphinx_bootstrap_theme` 

From the build log step `python /home/docs/checkouts/readthedocs.org/user_builds/mpf/envs/0.30/bin/sphinx-build -T`

```
Running Sphinx v1.3.5
making output directory...

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/mpf/envs/0.30/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 243, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/mpf/envs/0.30/local/lib/python2.7/site-packages/sphinx/application.py", line 127, in __init__
    confoverrides or {}, self.tags)
  File "/home/docs/checkouts/readthedocs.org/user_builds/mpf/envs/0.30/local/lib/python2.7/site-packages/sphinx/config.py", line 277, in __init__
    execfile_(filename, config)
  File "/home/docs/checkouts/readthedocs.org/user_builds/mpf/envs/0.30/local/lib/python2.7/site-packages/sphinx/util/pycompat.py", line 128, in execfile_
    exec_(code, _globals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/mpf/envs/0.30/local/lib/python2.7/site-packages/six.py", line 699, in exec_
    exec("""exec _code_ in _globs_, _locs_""")
  File "<string>", line 1, in <module>
  File "conf.py", line 18, in <module>
    import sphinx_bootstrap_theme
ImportError: No module named sphinx_bootstrap_theme

Exception occurred:
  File "conf.py", line 18, in <module>
    import sphinx_bootstrap_theme
ImportError: No module named sphinx_bootstrap_theme
The full traceback has been saved in /tmp/sphinx-err-gpZGLC.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks
```

So you can see it's using `conf.py` (which does not have the import commented out). So I think this is a bug?

**Comment by ericholscher** [comment]
Believe sphinx requires the file to be called `conf.py` -- we can only pass a directory path to the file: http://www.sphinx-doc.org/en/stable/invocation.html#cmdoption-sphinx-build-c

**Comment by toomanybrians** [comment]
That was it. Looks like I didn't read/understand the descriptive text around that config option, but renaming my file to conf.py and putting it in its own folder fixed it.

Thanks!
