### ISSUE TITLE
Extension error: Could not import extension sphinx.ext.githubpages

### ISSUE THREAD

**Issue by Gabriel-p** [rtfd/readthedocs.org#2402]
## Details
- Project URL: https://readthedocs.org/projects/photom/
- Build URL (if applicable):
- Read the Docs username (if applicable): Gabriel-p
## Expected Result

A successful build. In my system I use:

```
$ make html
sphinx-build -b html -d build/doctrees   source build/html
Running Sphinx v1.4.6
making output directory...
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 1 source files that are out of date
updating environment: 1 added, 0 changed, 0 removed
reading sources... [100%] index                                                                        
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] index                                                                         
generating indices... genindex
writing additional pages... search
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded.

Build finished. The HTML pages are in build/html.
```
## Actual Result

The build [fails with](https://readthedocs.org/projects/python-ccd-photometry/builds/4376610/):

```
Running Sphinx v1.3.5
making output directory...

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/python-ccd-photometry/envs/latest/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 243, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/python-ccd-photometry/envs/latest/local/lib/python2.7/site-packages/sphinx/application.py", line 144, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/python-ccd-photometry/envs/latest/local/lib/python2.7/site-packages/sphinx/application.py", line 435, in setup_extension
    err)
ExtensionError: Could not import extension sphinx.ext.githubpages (exception: No module named githubpages)

Extension error:
Could not import extension sphinx.ext.githubpages (exception: No module named githubpages)
```

This is similar to issue #2269. Over there the issue apparently was that the user was using an older version of `sphinx`, but I'm using v1.4.6.

Why does the online build use v1.3.5?

**Comment by buzdykg** [comment]
I experience the same issue. Deleting the extension from conf.py solved the issue for now.

**Comment by ericholscher** [comment]
You likely need to install this extension in your requirements.txt or setup.py. As documented here: http://docs.readthedocs.io/en/latest/yaml-config.html?highlight=requirements.txt#requirements-file
