### ISSUE TITLE
Build Failing: BadZipfile: File is not a zip file

### ISSUE THREAD

**Issue by xalgorithm** [rtfd/readthedocs.org#2420]
## Details
- Project URL: http://slac-ocio-dev-processes.readthedocs.io/en/latest/
- Build URL (if applicable): https://readthedocs.org/projects/slac-ocio-dev-processes/builds/4421562/
- Read the Docs username (if applicable): xalg
## Expected Result

My newest revision to build.
## Actual Result

```
Collecting sphinx==1.3.5
  Using cached Sphinx-1.3.5-py2.py3-none-any.whl
Collecting Pygments==2.1.3
  Using cached Pygments-2.1.3-py2.py3-none-any.whl
Collecting setuptools==20.1.1
  Using cached setuptools-20.1.1-py2.py3-none-any.whl
Collecting docutils==0.12
Collecting mkdocs==0.15.0
  Using cached mkdocs-0.15.0-py2.py3-none-any.whl
Collecting mock==1.0.1
Collecting pillow==2.6.1
Exception:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/slac-ocio-dev-processes/envs/latest/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/docs/checkouts/readthedocs.org/user_builds/slac-ocio-dev-processes/envs/latest/local/lib/python2.7/site-packages/pip/commands/install.py", line 310, in run
    wb.build(autobuilding=True)
  File "/home/docs/checkouts/readthedocs.org/user_builds/slac-ocio-dev-processes/envs/latest/local/lib/python2.7/site-packages/pip/wheel.py", line 750, in build
    self.requirement_set.prepare_files(self.finder)
  File "/home/docs/checkouts/readthedocs.org/user_builds/slac-ocio-dev-processes/envs/latest/local/lib/python2.7/site-packages/pip/req/req_set.py", line 370, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/home/docs/checkouts/readthedocs.org/user_builds/slac-ocio-dev-processes/envs/latest/local/lib/python2.7/site-packages/pip/req/req_set.py", line 587, in _prepare_file
    session=self.session, hashes=hashes)
  File "/home/docs/checkouts/readthedocs.org/user_builds/slac-ocio-dev-processes/envs/latest/local/lib/python2.7/site-packages/pip/download.py", line 798, in unpack_url
    unpack_file_url(link, location, download_dir, hashes=hashes)
  File "/home/docs/checkouts/readthedocs.org/user_builds/slac-ocio-dev-processes/envs/latest/local/lib/python2.7/site-packages/pip/download.py", line 705, in unpack_file_url
    unpack_file(from_path, location, content_type, link)
  File "/home/docs/checkouts/readthedocs.org/user_builds/slac-ocio-dev-processes/envs/latest/local/lib/python2.7/site-packages/pip/utils/__init__.py", line 599, in unpack_file
    flatten=not filename.endswith('.whl')
  File "/home/docs/checkouts/readthedocs.org/user_builds/slac-ocio-dev-processes/envs/latest/local/lib/python2.7/site-packages/pip/utils/__init__.py", line 484, in unzip_file
    zip = zipfile.ZipFile(zipfp, allowZip64=True)
  File "/usr/lib/python2.7/zipfile.py", line 770, in __init__
    self._RealGetContents()
  File "/usr/lib/python2.7/zipfile.py", line 811, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
BadZipfile: File is not a zip file
```

Steps I have tried:
    - Clicked the build button again
    - "Wiped" the instance
    - Disabled ePub and PDF
    - Review yml syntax for errors with a linter
    - cursing at it

**Comment by ericholscher** [comment]
Sorry this took a while, it looks like it has been fixed (as the latest builds are passing). Did you do anything in particular to get it to work, or did it just magically start working?

**Comment by WoLpH** [comment]
@ericholscher It appears to be broken intermittendly, I got it twice in the last few days but it's not always the case. I'm guessing there's a corrupt download somewhere on one of the machines.

Here's two broken builds for your viewing pleasure:

 - https://readthedocs.org/projects/progressbar-2/builds/5471290/
 - https://readthedocs.org/projects/progressbar-2/builds/5475772/

**Comment by stsewd** [comment]
@xalgorithm @WoLpH your latest builds are passing or failing for other reasons. Feel free to reopen if you are still having this problem,

**Comment by WoLpH** [comment]
it seems the issue hasn't occurred recently so I assume it has been fixed
