### ISSUE TITLE
ImportError: No module named transform

### ISSUE THREAD

**Issue by ldesousa** [rtfd/readthedocs.org#2466]
## Details
- Project URL: https://github.com/ldesousa/rtd-md
- Build URL (if applicable): https://readthedocs.org/projects/rtd-md/builds/4533766/
- Read the Docs username (if applicable): ldesousa
## Expected Result

I expected RTC to compile the project successfully as it happens on my system.
## Actual Result

RTC seems to be importing the `recommonmark` namespace correctly, but then fails to access the `transform`package. Here is the trace:

```
 python /home/docs/checkouts/readthedocs.org/user_builds/rtd-md/envs/latest/bin/sphinx-build -T -b readthedocs -d _build/doctrees-readthedocs -D language=en . _build/html
Running Sphinx v1.3.5
making output directory...

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/rtd-md/envs/latest/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 243, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/rtd-md/envs/latest/local/lib/python2.7/site-packages/sphinx/application.py", line 127, in __init__
    confoverrides or {}, self.tags)
  File "/home/docs/checkouts/readthedocs.org/user_builds/rtd-md/envs/latest/local/lib/python2.7/site-packages/sphinx/config.py", line 277, in __init__
    execfile_(filename, config)
  File "/home/docs/checkouts/readthedocs.org/user_builds/rtd-md/envs/latest/local/lib/python2.7/site-packages/sphinx/util/pycompat.py", line 128, in execfile_
    exec_(code, _globals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/rtd-md/envs/latest/local/lib/python2.7/site-packages/six.py", line 699, in exec_
    exec("""exec _code_ in _globs_, _locs_""")
  File "<string>", line 1, in <module>
  File "conf.py", line 24, in <module>
    from recommonmark.transform import AutoStructify
ImportError: No module named transform

Exception occurred:
  File "conf.py", line 24, in <module>
    from recommonmark.transform import AutoStructify
ImportError: No module named transform
The full traceback has been saved in /tmp/sphinx-err-BQjtaQ.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

**Comment by ldesousa** [comment]
A workaround to this issue is to fix the `recommonmark` to version 0.4.0, like so:

https://github.com/ldesousa/rtd-md/blob/master/requirements.txt

For whatever reason, RTD is compiling these documents with a previous version of `recommonmark`.

**Comment by Basti890** [comment]
Thanks for this workarround. I just had the same issue. I hope this Bug can be fixed soon.

**Comment by agjohnson** [comment]
We're pinning `recommonmark==0.4.0` now, so this should be resolved.
