### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'traverse'

### ISSUE THREAD

**Issue by anatskiy** [rtfd/readthedocs.org#2609]
## Details

* Project URL: https://github.com/maxplanck-ie/parkour/tree/develop/docs
* Build URL (if applicable): https://readthedocs.org/projects/parkour/builds/4939482/

## Expected Result

A successful build.

## Actual Result

Right after changing the default branch (' ' -> `develop`) in the Project's settings on readthedocs.org, builds started to fail. I know this issue is quite common, but I didn't see any solution.

### Sphinx version

1.5.2

### Traceback

```
Running Sphinx v1.5.2
making output directory...
loading translations [en]... done
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [readthedocssinglehtmllocalmedia]: all documents
updating environment: 1 added, 0 changed, 0 removed
reading sources... [100%] index

looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
assembling single document... 
writing... 
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/parkour/envs/latest/lib/python3.4/site-packages/sphinx/cmdline.py", line 296, in main
    app.build(opts.force_all, filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/parkour/envs/latest/lib/python3.4/site-packages/sphinx/application.py", line 333, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/parkour/envs/latest/lib/python3.4/site-packages/sphinx/builders/__init__.py", line 246, in build_update
    self.build(['__all__'], to_build)
  File "/home/docs/checkouts/readthedocs.org/user_builds/parkour/envs/latest/lib/python3.4/site-packages/sphinx/builders/__init__.py", line 322, in build
    self.write(docnames, list(updated_docnames), method)
  File "/home/docs/checkouts/readthedocs.org/user_builds/parkour/envs/latest/lib/python3.4/site-packages/sphinx/builders/html.py", line 1053, in write
    self.write_doc(self.config.master_doc, doctree)
  File "/home/docs/checkouts/readthedocs.org/user_builds/parkour/envs/latest/lib/python3.4/site-packages/sphinx/builders/html.py", line 458, in write_doc
    self.handle_page(docname, ctx, event_arg=doctree)
  File "/home/docs/checkouts/readthedocs.org/user_builds/parkour/envs/latest/lib/python3.4/site-packages/sphinx/builders/html.py", line 820, in handle_page
    output = self.templates.render(templatename, ctx)
  File "/home/docs/checkouts/readthedocs.org/user_builds/parkour/envs/latest/lib/python3.4/site-packages/readthedocs_ext/readthedocs.py", line 101, in rtd_render
    content = old_render(template, render_context)
  File "/home/docs/checkouts/readthedocs.org/user_builds/parkour/envs/latest/lib/python3.4/site-packages/sphinx/jinja2glue.py", line 158, in render
    return self.environment.get_template(template).render(context)
  File "/home/docs/checkouts/readthedocs.org/user_builds/parkour/envs/latest/lib/python3.4/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/docs/checkouts/readthedocs.org/user_builds/parkour/envs/latest/lib/python3.4/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/docs/checkouts/readthedocs.org/user_builds/parkour/envs/latest/lib/python3.4/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/docs/checkouts/readthedocs.org/user_builds/parkour/envs/latest/lib/python3.4/site-packages/sphinx/themes/basic/page.html", line 10, in top-level template code
    {%- extends "layout.html" %}
  File "/home/docs/checkouts/readthedocs.org/user_builds/parkour/envs/latest/lib/python3.4/site-packages/sphinx_rtd_theme/layout.html", line 122, in top-level template code
    {% block menu %}
  File "/home/docs/checkouts/readthedocs.org/user_builds/parkour/envs/latest/lib/python3.4/site-packages/sphinx_rtd_theme/layout.html", line 123, in block "menu"
    {% set toctree = toctree(maxdepth=4, collapse=theme_collapse_navigation, includehidden=True) %}
  File "/home/docs/checkouts/readthedocs.org/user_builds/parkour/envs/latest/lib/python3.4/site-packages/jinja2/sandbox.py", line 427, in call
    return __context.call(__obj, *args, **kwargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/parkour/envs/latest/lib/python3.4/site-packages/sphinx/builders/html.py", line 810, in <lambda>
    ctx['toctree'] = lambda **kw: self._get_local_toctree(pagename, **kw)
  File "/home/docs/checkouts/readthedocs.org/user_builds/parkour/envs/latest/lib/python3.4/site-packages/sphinx/builders/html.py", line 964, in _get_local_toctree
    self.fix_refuris(toctree)
  File "/home/docs/checkouts/readthedocs.org/user_builds/parkour/envs/latest/lib/python3.4/site-packages/sphinx/builders/html.py", line 949, in fix_refuris
    for refnode in tree.traverse(nodes.reference):
AttributeError: 'NoneType' object has no attribute 'traverse'

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/parkour/envs/latest/lib/python3.4/site-packages/sphinx/builders/html.py", line 949, in fix_refuris
    for refnode in tree.traverse(nodes.reference):
AttributeError: 'NoneType' object has no attribute 'traverse'
The full traceback has been saved in /tmp/sphinx-err-vcou4jq4.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

**Comment by toolness** [comment]
This seems to be a duplicate of #2398, where there is more discussion happening, at least.
