### ISSUE TITLE
macOS can result in ValueError: unknown locale: UTF-8

### ISSUE THREAD

**Issue by uchuugaka** [rtfd/readthedocs.org#2619]
## Details
macOS by default seems to have unset environment variables for LC_* or LANG
This causes a failure with the underlying Python 2.7.x standard library locale module when the underlying docutils library module tries to import that.

It is not unique to readthedocs, but rather a failure to have these env vars set by default on macOS in the command line shell.
However, it may be an unusual experience if somebody tried to build this and hadn't come across it yet.

* Project URL:  any
* Build URL (if applicable): any
* Read the Docs username (if applicable): 

## Expected Result
The server should simply work, just like any other django server on a mac.

*A description of what you wanted to happen*

## Actual Result
The server fails with a straight forward traceback, but a non-obvious solution unless somebody Googles well.

Fortunately a simple solution can be found at:
https://coderwall.com/p/-k_93g/mac-os-x-valueerror-unknown-locale-utf-8-in-python

Setting up the shell environment variables before starting up will resolve it.
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
(any valid locale here should be ok.
This can be set in a ~/.bash_profile at the user level, but also in /etc/profile for a system wide setting.

However, readthedocs could handle this directly by noting it on the page
http://docs.readthedocs.io/en/latest/install.html
OR by changing the environment in Python in the manage.py file for the django app itself.
~/path/to/rtd/checkouts/readthedocs.org/manage.py

They can be set like this (or more fancy ways and even conditionally, of course based on if they're not set or keys not found)

```
#!/usr/bin/env python
import os
import sys

if __name__ == "__main__":
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "readthedocs.settings.dev")
    # Set something if needed.
    os.environ.setdefault("LC_ALL", "en_US.UTF-8")
    os.environ.setdefault("LANG", "en_US.UTF-8")
    sys.path.append(os.getcwd())

    from django.core.management import execute_from_command_line

    execute_from_command_line(sys.argv)

```

## Resulting Error
looks like this (with my absolute path obscured with ~/path/to):

```
$ python manage.py runserver
Performing system checks...

System check identified no issues (1 silenced).
January 28, 2017 - 07:25:26
Django version 1.8.16, using settings 'readthedocs.settings.dev'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "~/path/to/rtd/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__
    return self.application(environ, start_response)
  File "~/path/to/rtd/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 170, in __call__
    self.load_middleware()
  File "~/path/to/rtd/lib/python2.7/site-packages/django/core/handlers/base.py", line 52, in load_middleware
    mw_instance = mw_class()
  File "~/path/to/rtd/lib/python2.7/site-packages/django/middleware/locale.py", line 24, in __init__
    for url_pattern in get_resolver(None).url_patterns:
  File "~/path/to/rtd/lib/python2.7/site-packages/django/core/urlresolvers.py", line 401, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "~/path/to/rtd/lib/python2.7/site-packages/django/core/urlresolvers.py", line 395, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "~/path/to/rtd/checkouts/readthedocs.org/readthedocs/urls.py", line 55, in <module>
    url(r'^api/v2/', include('readthedocs.restapi.urls')),
  File "~/path/to/rtd/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "~/path/to/rtd/checkouts/readthedocs.org/readthedocs/restapi/urls.py", line 6, in <module>
    from readthedocs.comments.views import CommentViewSet
  File "~/path/to/rtd/checkouts/readthedocs.org/readthedocs/comments/views.py", line 22, in <module>
    from sphinx.websupport import WebSupport
  File "~/path/to/rtd/lib/python2.7/site-packages/sphinx/websupport/__init__.py", line 18, in <module>
    from docutils.core import publish_parts
  File "~/path/to/rtd/lib/python2.7/site-packages/docutils/core.py", line 20, in <module>
    from docutils import frontend, io, utils, readers, writers
  File "~/path/to/rtd/lib/python2.7/site-packages/docutils/frontend.py", line 41, in <module>
    import docutils.utils
  File "~/path/to/rtd/lib/python2.7/site-packages/docutils/utils/__init__.py", line 20, in <module>
    import docutils.io
  File "~/path/to/rtd/lib/python2.7/site-packages/docutils/io.py", line 18, in <module>
    from docutils.utils.error_reporting import locale_encoding, ErrorString, ErrorOutput
  File "~/path/to/rtd/lib/python2.7/site-packages/docutils/utils/error_reporting.py", line 47, in <module>
    locale_encoding = locale.getlocale()[1] or locale.getdefaultlocale()[1]
  File "~/path/to/rtd/lib/python2.7/locale.py", line 562, in getlocale
    return _parse_localename(localename)
  File "~/path/to/rtd/lib/python2.7/locale.py", line 475, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8
[28/Jan/2017 07:25:36] "GET / HTTP/1.1" 500 59

```

The error is replicable even more simply by launching the python interpreter, and doing
`from docutils import frontend, io, utils, readers, writers`
(importing any one of those is where the choke occurs)

```
>>> from docutils import frontend, io, utils, readers, writers
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/docutils/frontend.py", line 41, in <module>
    import docutils.utils
  File "/Library/Python/2.7/site-packages/docutils/utils/__init__.py", line 20, in <module>
    import docutils.io
  File "/Library/Python/2.7/site-packages/docutils/io.py", line 18, in <module>
    from docutils.utils.error_reporting import locale_encoding, ErrorString, ErrorOutput
  File "/Library/Python/2.7/site-packages/docutils/utils/error_reporting.py", line 47, in <module>
    locale_encoding = locale.getlocale()[1] or locale.getdefaultlocale()[1]
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 543, in getdefaultlocale
    return _parse_localename(localename)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 475, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8
```

**Comment by agjohnson** [comment]
Thanks for the info! This doesn't look to be any problem with RTD itself, so I'm going to close this issue. I hope it helps anyone else that hits this issue. This comes down to setting up your environment correctly, so I'd view this outside our control and not something we should be opinionated on.
