### ISSUE TITLE
Private instance: build uses system python for creating virtualenv instead of python running RTD

### ISSUE THREAD

**Issue by cdunklau** [rtfd/readthedocs.org#2636]
It seems that RTD assumes that the environment's `python` (or `python3`) executable is the right one to use, but this isn't the case if you run it from a non-activated virtualenv.

## Expected Result

I believe RTD should create virtualenvs using whatever python version it's running under (probably by using `sys.executable`?) instead of whatever `python` refers to in the process environment.

## Actual Result

I installed a private instance of RTD, following the [instructions](http://read-the-docs.readthedocs.io/en/latest/install.html), except I didn't activate the virtualenv. Instead, I just ran `rtdvenv/bin/python manage.py runserver`. Everything went fine, until I tried to build from a repo, and wound up getting these logs:

```
[08/Feb/2017 10:25:16] INFO [readthedocs.projects.tasks:104] (Build) [myproject:latest] Updating docs from VCS
[08/Feb/2017 10:25:16] "GET /api/v1/version/20/ HTTP/1.1" 200 1710
[08/Feb/2017 10:25:16] INFO [readthedocs.projects.tasks:454] (Build) [myproject:latest] Checking out version latest: master
[08/Feb/2017 10:25:18] "POST /api/v2/project/24/sync_versions/ HTTP/1.1" 200 43
[08/Feb/2017 10:25:18] INFO [readthedocs.doc_builder.environments:289] (Build) [myproject:latest] Build finished
[08/Feb/2017 10:25:19] "GET /api/v2/project/24/ HTTP/1.1" 200 322
[08/Feb/2017 10:25:19] INFO [readthedocs.core.symlink:91] (Build) [myproject:] Symlinking Version: Version latest of myproject (20)
[08/Feb/2017 10:25:19] INFO [readthedocs.projects.tasks:830] (Build) [myproject:] Updating static metadata
[08/Feb/2017 10:25:19] "PUT /api/v2/project/24/ HTTP/1.1" 200 322
[08/Feb/2017 10:25:19] "PUT /api/v2/build/14/ HTTP/1.1" 200 314
[08/Feb/2017 10:25:19] ERROR [readthedocs.doc_builder.environments:65] Command is ('python', '-mvirtualenv', '--no-site-packages', '--no-download', '/home/readthedocs/readthedocs.org/user_builds/myproject/envs/latest')
[08/Feb/2017 10:25:19] INFO [readthedocs.doc_builder.environments:103] Running: 'python -mvirtualenv --no-site-packages --no-download /home/readthedocs/readthedocs.org/user_builds/myproject/envs/latest' [/home/readthedocs/readthedocs.org]
[08/Feb/2017 10:25:19] "POST /api/v2/command/ HTTP/1.1" 201 384
[08/Feb/2017 10:25:19] ERROR [readthedocs.doc_builder.environments:307] (Build) [myproject:latest] Command python -mvirtualenv --no-site-packages --no-download /home/readthedocs/readthedocs.org/user_builds/myproject/envs/latest failed:
Usage: virtualenv.py [OPTIONS] DEST_DIR

virtualenv.py: error: no such option: --no-download
Traceback (most recent call last):
  File "/home/readthedocs/readthedocs.org/readthedocs/projects/tasks.py", line 166, in run
    self.setup_environment()
  File "/home/readthedocs/readthedocs.org/readthedocs/projects/tasks.py", line 309, in setup_environment
    self.python_env.setup_base()
  File "/home/readthedocs/readthedocs.org/readthedocs/doc_builder/python_environments.py", line 101, in setup_base
    bin_path=None,  # Don't use virtualenv bin that doesn't exist yet
  File "/home/readthedocs/readthedocs.org/readthedocs/doc_builder/environments.py", line 314, in run
    return self.run_command_class(cls=self.command_class, cmd=cmd, **kwargs)
  File "/home/readthedocs/readthedocs.org/readthedocs/doc_builder/environments.py", line 351, in run_command_class
    raise BuildEnvironmentWarning(msg)
BuildEnvironmentWarning: Command python -mvirtualenv --no-site-packages --no-download /home/readthedocs/readthedocs.org/user_builds/myproject/envs/latest failed:
Usage: virtualenv.py [OPTIONS] DEST_DIR

virtualenv.py: error: no such option: --no-download

[08/Feb/2017 10:25:19] INFO [readthedocs.doc_builder.environments:289] (Build) [myproject:latest] Build finished
```

(I put in the logging bit for `ERROR [readthedocs.doc_builder.environments:65] Command is ...` to see what was going on)

The traceback occurs because my system python has an old virtualenv version (1.11.6) which doesn't have the `--no-download` option. Adding the extra logging bit helped me isolate the problem.

## Culprit and possible resolution

https://github.com/rtfd/readthedocs.org/blob/5b5ffb559450c53fd1faacdc3fd1aefd5ab321e6/readthedocs/doc_builder/python_environments.py#L95

This seems to be the code that creates the venv. For some reason, `self.config.python_interpreter` is just the string `'python'`. If I switch the project config to CPython 3.x, it becomes `'python3'`.

To ensure that the environment gets created with the intended interpreter, but still uses the specific version installed in the RTD venv, this code should probably look more like this:

```python
        self.build_env.run(
            sys.executable,
            '-mvirtualenv',
            '-p{envpython}'.format(envpython=self.config.python_interpreter),
            site_packages,
            '--no-download',
            env_path,
            bin_path=None,  # Don't use virtualenv bin that doesn't exist yet
        )
```

I'm quite new to looking at RTD, so I'm concerned this will affect something else I haven't noticed.

As a side note, the other invokations of `build_env.run(...)` in that file have the executable hardcoded as `'python'`, and should probably be changed to `sys.executable` instead.

**Comment by agjohnson** [comment]
I'm not sure of the expected result here. If you are running outside the virtualenv, missing the virtualenv requirement set by our requirements, then you will most definitely run into problems. Unless I'm missing something, it seems the directions still stand, and RTD should be executed inside a virtualenv.
