### ISSUE TITLE
conda env create fails with permission denied

### ISSUE THREAD

**Issue by willsheffler** [rtfd/readthedocs.org#2701]
## Details

* Project URL: https://readthedocs.org/projects/rif
* Build URL (if applicable): https://readthedocs.org/projects/rif/builds/5117259/
* Read the Docs username (if applicable): willsheffler

## Expected Result

First, thank you for your excellent service!!!! Fantastic!

I am using a conda environment to build a python/c++ project. I "wiped" my latest version, then my build started failing with permission denied on "conda env create" (log below). The previous version which worked. I don't believe I changed anything re: the conda env setup, so I suspect the wipe was the problem?

https://readthedocs.org/projects/rif/builds/5117030/

## Actual Result

build log:

 conda env create --name latest --file /home/docs/checkouts/readthedocs.org/user_builds/rif/checkouts/latest/docs/environment.yml
Fetching package metadata ...An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : linux-64
          conda version : 4.3.11
       conda is private : False
      conda-env version : 4.3.11
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : /usr/local/miniconda  (read only)
    default environment : /home/docs/checkouts/readthedocs.org/user_builds/rif/conda/latest
       envs directories : /home/docs/checkouts/readthedocs.org/user_builds/rif/conda
                          /usr/local/miniconda/envs
                          /home/docs/.conda/envs
          package cache : /usr/local/miniconda/pkgs
                          /home/docs/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.11 requests/2.12.4 CPython/2.7.13 Linux/3.13.0-108-generic debian/stretch/sid glibc/2.23
                UID:GID : 1005:205

`$ /usr/local/miniconda/bin/conda-env create --name latest --file /home/docs/checkouts/readthedocs.org/user_builds/rif/checkouts/latest/docs/environment.yml`

    Traceback (most recent call last):
      File "/usr/local/miniconda/lib/python2.7/site-packages/conda/exceptions.py", line 616, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/usr/local/miniconda/lib/python2.7/site-packages/conda_env/cli/main_create.py", line 112, in execute
        installer.install(prefix, pkg_specs, args, env)
      File "/usr/local/miniconda/lib/python2.7/site-packages/conda_env/installers/conda.py", line 29, in install
        prefix=prefix)
      File "/usr/local/miniconda/lib/python2.7/site-packages/conda/core/index.py", line 125, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "/usr/local/miniconda/lib/python2.7/site-packages/conda/core/index.py", line 552, in fetch_index
        repodatas = _collect_repodatas(use_cache, tasks)
      File "/usr/local/miniconda/lib/python2.7/site-packages/conda/core/index.py", line 541, in _collect_repodatas
        repodatas = _collect_repodatas_serial(use_cache, tasks)
      File "/usr/local/miniconda/lib/python2.7/site-packages/conda/core/index.py", line 514, in _collect_repodatas_serial
        for url, schan, pri in tasks]
      File "/usr/local/miniconda/lib/python2.7/site-packages/conda/core/index.py", line 144, in func
        res = f(*args, **kwargs)
      File "/usr/local/miniconda/lib/python2.7/site-packages/conda/core/index.py", line 500, in fetch_repodata
        with open(cache_path, 'w') as fo:
    IOError: [Errno 13] Permission denied: u'/usr/local/miniconda/pkgs/cache/cff4679f.json'

Command time: 1s Return:

**Comment by willsheffler** [comment]
I see this is a duplicate of 2700, which I didn't see before I started submitting this. Please ignore.
