### ISSUE TITLE
ImportError: No module named 'requests.packages'; 'requests' is not a package

### ISSUE THREAD

**Issue by pierrrrrrre** [rtfd/readthedocs.org#2743]
Hello!

For a few weeks now, both of our projects' documentation builds are failing in readthedocs with the same error:

```
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/checkbox/envs/latest/lib/python3.5/site-packages/sphinx/util/requests.py", line 23, in <module>
    from requests.packages.urllib3.exceptions import SSLError
ImportError: No module named 'requests.packages'; 'requests' is not a package

During handling of the above exception, another exception occurred:
```

Locally, I can compile the documentation without any problem using the proper Git repository and the command `./setup.py build_sphinx`.

Thanks in advance for your help!

## Details

* Project URLs:
  * https://readthedocs.org/projects/checkbox
  * https://readthedocs.org/projects/plainbox
* Build URLs (for instance):
  * https://readthedocs.org/projects/checkbox/builds/5188964/
  * https://readthedocs.org/projects/plainbox/builds/5182356/
* Read the Docs username (if applicable): ePierre

## Expected Result

The build works and a new version of the documentation is made available.

## Actual Result

The build fails. Complete log:

```
Running Sphinx v1.5.3
making output directory...

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/checkbox/envs/latest/lib/python3.5/site-packages/sphinx/util/requests.py", line 23, in <module>
    from requests.packages.urllib3.exceptions import SSLError
ImportError: No module named 'requests.packages'; 'requests' is not a package

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/checkbox/envs/latest/lib/python3.5/site-packages/sphinx/application.py", line 512, in setup_extension
    mod = __import__(extension, None, None, ['setup'])
  File "/home/docs/checkouts/readthedocs.org/user_builds/checkbox/envs/latest/lib/python3.5/site-packages/sphinx/builders/linkcheck.py", line 34, in <module>
    from sphinx.util import encode_uri, requests
  File "/home/docs/checkouts/readthedocs.org/user_builds/checkbox/envs/latest/lib/python3.5/site-packages/sphinx/util/requests.py", line 27, in <module>
    from urllib3.exceptions import SSLError
ImportError: No module named 'urllib3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/checkbox/envs/latest/lib/python3.5/site-packages/sphinx/cmdline.py", line 295, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/checkbox/envs/latest/lib/python3.5/site-packages/sphinx/application.py", line 189, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/checkbox/envs/latest/lib/python3.5/site-packages/sphinx/application.py", line 516, in setup_extension
    err)
sphinx.errors.ExtensionError: Could not import extension sphinx.builders.linkcheck (exception: No module named 'urllib3')

Extension error:
Could not import extension sphinx.builders.linkcheck (exception: No module named 'urllib3')
```

**Comment by humitos** [comment]
@pierrrrrrre hi! it seems the problem is you are mocking `requests` at (https://git.launchpad.net/plainbox/tree/docs/conf.py#n31) and it's needed by `sphink.builder.linkcheck`

Please, try not mocking it and let me know.

**Comment by pierrrrrrre** [comment]
Thanks a lot @humitos for pointing this out! I removed those from out conf.py files and it works now!

Cheers,
