### ISSUE TITLE
Autodoc fail with Gtk

### ISSUE THREAD

**Issue by poulp** [rtfd/readthedocs.org#2990]
## Details

* Project URL: http://zenipy.readthedocs.io
* Build URL (if applicable): https://readthedocs.org/projects/zenipy/builds/5646749/
* Read the Docs username (if applicable): ploulp

## Expected Result

I use autodoc to create doc directly from the python files. My project use Gtk+3 trough the python bindings Pygobject (https://pygobject.readthedocs.io/en/latest/)

## Actual Result
The build does not fail but an import error with Gtk skip my autodoc generation. Here the error : 
```
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/zenipy/envs/latest/local/lib/python3.5/site-packages/sphinx/ext/autodoc.py", line 551, in import_object
    __import__(self.modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/zenipy/checkouts/latest/zenipy/__init__.py", line 1, in <module>
    from .zenipy import (
  File "/home/docs/checkouts/readthedocs.org/user_builds/zenipy/checkouts/latest/zenipy/zenipy.py", line 5, in <module>
    gi.require_version('Gtk', '3.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 102, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gtk not available
```
My code look like this : 
```
import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk, GLib
```

In the advanced settings i enabled `Use system packages`, but it still doesn't work :(

**Comment by agjohnson** [comment]
It looks like Gtk 3.0 binding are missing. Perhaps review our documentation on how to stub out dependencies that rely on headers that aren't installed. Closing this as this is an issue covered in our documentation.
