### ISSUE TITLE
ImportError: cannot import name get_apps

### ISSUE THREAD

**Issue by AdnreiHN** [rtfd/readthedocs.org#2999]
Hi.

I try to install ReadTheDocs on Ubuntu 14.04 LTS however,  as the docs says that I need to run ./managepy syncdb - there is no such command syncdb, it is sync data. When I run this, I get the bellow error. Can you tell  me what is wrong and update your docs so I can install this? Thanks!

./manage.py syncdata
[11/Jul/2017 02:26:33] root:120[13211]: INFO Generating grammar tables from /usr/lib/python2.7/lib2to3/Grammar.txt
[11/Jul/2017 02:26:33] root:120[13211]: INFO Generating grammar tables from /usr/lib/python2.7/lib2to3/PatternGrammar.txt
Traceback (most recent call last):
  File "./manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/rtd/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/opt/rtd/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/rtd/local/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/rtd/local/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/opt/rtd/local/lib/python2.7/site-packages/django_extensions/management/utils.py", line 58, in inner
    ret = func(self, *args, **kwargs)
  File "/opt/rtd/local/lib/python2.7/site-packages/django/utils/decorators.py", line 184, in inner
    return func(*args, **kwargs)
  File "/opt/rtd/local/lib/python2.7/site-packages/django_extensions/management/commands/syncdata.py", line 67, in handle
    from django.db.models import get_apps
ImportError: cannot import name get_apps

**Comment by ericholscher** [comment]
Thanks for working to get Read the Docs into your organization. We currently don't have time to support local installs for free as a core team. This is explained in more depth here: http://docs.readthedocs.io/en/latest/open-source-philosophy.html#unsupported -- I will close this issue because of this policy. 

We do offer paid hosting for companies at readthedocs.com, as well as [paid support](https://readthedocs.com/services/#open-source-support) for local installs.
