### ISSUE TITLE
AttributeError: 'builtin_function_or_method' object has no attribute 'split'

### ISSUE THREAD

**Issue by jamchen1025** [rtfd/readthedocs.org#3067]
## Details
I create a simple project (means only docs, some configure files and a simple __init__.py)
When I choose CPython 2.X -> build success, but CPython 3.X will build fail.

* Project URL: [jtwstock](https://github.com/jamchen1025/jtwstock/tree/feature/build_first_setting)
* Build URL (if applicable): [RTD build fail](https://readthedocs.org/projects/jtwstock/builds/5885160/)
* Read the Docs username (if applicable): jam.chen1025

## Expected Result
docs build success.

## Actual Result

*A description of what actually happened*
```
running install
running bdist_egg
running egg_info
creating jtwstock.egg-info
writing jtwstock.egg-info/PKG-INFO
Traceback (most recent call last):
  File "setup.py", line 47, in <module>
    "Programming Language :: Python :: 3"
  File "/home/docs/.pyenv/versions/3.5.2/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/docs/.pyenv/versions/3.5.2/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/docs/.pyenv/versions/3.5.2/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/docs/checkouts/readthedocs.org/user_builds/jtwstock/envs/feature-build_first_setting/lib/python3.5/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/docs/checkouts/readthedocs.org/user_builds/jtwstock/envs/feature-build_first_setting/lib/python3.5/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/docs/.pyenv/versions/3.5.2/lib/python3.5/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/docs/.pyenv/versions/3.5.2/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/docs/checkouts/readthedocs.org/user_builds/jtwstock/envs/feature-build_first_setting/lib/python3.5/site-packages/setuptools/command/bdist_egg.py", line 152, in run
    self.run_command("egg_info")
  File "/home/docs/.pyenv/versions/3.5.2/lib/python3.5/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/docs/.pyenv/versions/3.5.2/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/docs/checkouts/readthedocs.org/user_builds/jtwstock/envs/feature-build_first_setting/lib/python3.5/site-packages/setuptools/command/egg_info.py", line 272, in run
    writer(self, ep.name, os.path.join(self.egg_info, ep.name))
  File "/home/docs/checkouts/readthedocs.org/user_builds/jtwstock/envs/feature-build_first_setting/lib/python3.5/site-packages/setuptools/command/egg_info.py", line 605, in write_pkg_info
    metadata.write_pkg_info(cmd.egg_info)
  File "/home/docs/.pyenv/versions/3.5.2/lib/python3.5/distutils/dist.py", line 1107, in write_pkg_info
    self.write_pkg_file(pkg_info)
  File "/home/docs/checkouts/readthedocs.org/user_builds/jtwstock/envs/feature-build_first_setting/lib/python3.5/site-packages/setuptools/dist.py", line 53, in write_pkg_file
    long_desc = rfc822_escape(self.get_long_description())
  File "/home/docs/.pyenv/versions/3.5.2/lib/python3.5/distutils/util.py", line 471, in rfc822_escape
    lines = header.split('\n')
AttributeError: 'builtin_function_or_method' object has no attribute 'split'
```

**Comment by stsewd** [comment]
Closing this as the user [hasn't responded or given more information](https://docs.readthedocs.io/en/latest/contribute.html#initial-triage), feel free to reopen with more information if you are still having this problem :).

Also, I think this is probably an issue with the dependencies of your project rather than rtd. Can you verify that this works on your local environment with py3?
