### ISSUE TITLE
Unable to build project with scipy v1.0.0

### ISSUE THREAD

**Issue by reiinakano** [rtfd/readthedocs.org#3188]
## Details

* Project URL: https://readthedocs.org/projects/scikit-plot
* Build URL (if applicable): https://readthedocs.org/projects/scikit-plot/builds/6176303/
* Read the Docs username (if applicable): reiinakano

## Expected Result
Successful build as in my previous builds
*A description of what you wanted to happen*

## Actual Result
```
Building wheels for collected packages: scipy, subprocess32
  Running setup.py bdist_wheel for scipy: started
  Running setup.py bdist_wheel for scipy: finished with status 'error'
  Complete output from command /home/docs/checkouts/readthedocs.org/user_builds/scikit-plot/envs/v0.3.2/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-aaYEAX/scipy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpIa8hOxpip-wheel- --python-tag cp27:
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-aaYEAX/scipy/setup.py", line 418, in <module>
      setup_package()
    File "/tmp/pip-build-aaYEAX/scipy/setup.py", line 398, in setup_package
      from numpy.distutils.core import setup
  ImportError: No module named numpy.distutils.core
  
  ----------------------------------------
  Failed building wheel for scipy
  Running setup.py clean for scipy
  Complete output from command /home/docs/checkouts/readthedocs.org/user_builds/scikit-plot/envs/v0.3.2/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-aaYEAX/scipy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" clean --all:
  
  `setup.py clean` is not supported, use one of the following instead:
  
    - `git clean -xdf` (cleans all files)
    - `git clean -Xdf` (cleans all versioned files, doesn't touch
                        files that aren't checked into the git repo)
  
  Add `--force` to your command to use it anyway if you must (unsupported).
  
  
  ----------------------------------------
  Failed cleaning build dir for scipy
  Running setup.py bdist_wheel for subprocess32: started
  Running setup.py bdist_wheel for subprocess32: finished with status 'done'
  Stored in directory: /home/docs/checkouts/readthedocs.org/user_builds/scikit-plot/.cache/pip/wheels/7d/4c/a4/ce9ceb463dae01f4b95e670abd9afc8d65a45f38012f8030cc
Successfully built subprocess32
Failed to build scipy
Installing collected packages: numpy, cycler, subprocess32, python-dateutil, backports.functools-lru-cache, pyparsing, matplotlib, scikit-learn, scipy
  Running setup.py install for scipy: started
    Running setup.py install for scipy: finished with status 'error'
    Complete output from command /home/docs/checkouts/readthedocs.org/user_builds/scikit-plot/envs/v0.3.2/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-aaYEAX/scipy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-PeD_7E-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/docs/checkouts/readthedocs.org/user_builds/scikit-plot/envs/v0.3.2/include/site/python2.7/scipy:
    
    Note: if you need reliable uninstall behavior, then install
    with pip instead of using `setup.py install`:
    
      - `pip install .`       (from a git repo or downloaded source
                               release)
      - `pip install scipy`   (last SciPy release on PyPI)
    
    
    lapack_opt_info:
    lapack_mkl_info:
      libraries mkl_rt not found in ['/home/docs/checkouts/readthedocs.org/user_builds/scikit-plot/envs/v0.3.2/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
      NOT AVAILABLE
    
    openblas_lapack_info:
      libraries openblas not found in ['/home/docs/checkouts/readthedocs.org/user_builds/scikit-plot/envs/v0.3.2/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
      NOT AVAILABLE
    
    atlas_3_10_threads_info:
    Setting PTATLAS=ATLAS
      libraries tatlas,tatlas not found in /home/docs/checkouts/readthedocs.org/user_builds/scikit-plot/envs/v0.3.2/lib
      libraries lapack_atlas not found in /home/docs/checkouts/readthedocs.org/user_builds/scikit-plot/envs/v0.3.2/lib
      libraries tatlas,tatlas not found in /usr/local/lib
      libraries lapack_atlas not found in /usr/local/lib
      libraries tatlas,tatlas not found in /usr/lib
      libraries lapack_atlas not found in /usr/lib
      libraries tatlas,tatlas not found in /usr/lib/x86_64-linux-gnu
      libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu
    <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
      NOT AVAILABLE
    
    atlas_3_10_info:
      libraries satlas,satlas not found in /home/docs/checkouts/readthedocs.org/user_builds/scikit-plot/envs/v0.3.2/lib
      libraries lapack_atlas not found in /home/docs/checkouts/readthedocs.org/user_builds/scikit-plot/envs/v0.3.2/lib
      libraries satlas,satlas not found in /usr/local/lib
      libraries lapack_atlas not found in /usr/local/lib
      libraries satlas,satlas not found in /usr/lib
      libraries lapack_atlas not found in /usr/lib
      libraries satlas,satlas not found in /usr/lib/x86_64-linux-gnu
      libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu
    <class 'numpy.distutils.system_info.atlas_3_10_info'>
      NOT AVAILABLE
    
    atlas_threads_info:
    Setting PTATLAS=ATLAS
      libraries ptf77blas,ptcblas,atlas not found in /home/docs/checkouts/readthedocs.org/user_builds/scikit-plot/envs/v0.3.2/lib
      libraries lapack_atlas not found in /home/docs/checkouts/readthedocs.org/user_builds/scikit-plot/envs/v0.3.2/lib
      libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib
      libraries lapack_atlas not found in /usr/local/lib
      libraries ptf77blas,ptcblas,atlas not found in /usr/lib
      libraries lapack_atlas not found in /usr/lib
      libraries ptf77blas,ptcblas,atlas not found in /usr/lib/x86_64-linux-gnu
      libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu
    <class 'numpy.distutils.system_info.atlas_threads_info'>
      NOT AVAILABLE
    
    atlas_info:
      libraries f77blas,cblas,atlas not found in /home/docs/checkouts/readthedocs.org/user_builds/scikit-plot/envs/v0.3.2/lib
      libraries lapack_atlas not found in /home/docs/checkouts/readthedocs.org/user_builds/scikit-plot/envs/v0.3.2/lib
      libraries f77blas,cblas,atlas not found in /usr/local/lib
      libraries lapack_atlas not found in /usr/local/lib
      libraries f77blas,cblas,atlas not found in /usr/lib
      libraries lapack_atlas not found in /usr/lib
      libraries f77blas,cblas,atlas not found in /usr/lib/x86_64-linux-gnu
      libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu
    <class 'numpy.distutils.system_info.atlas_info'>
      NOT AVAILABLE
    
    /home/docs/checkouts/readthedocs.org/user_builds/scikit-plot/envs/v0.3.2/local/lib/python2.7/site-packages/numpy/distutils/system_info.py:572: UserWarning:
        Atlas (http://math-atlas.sourceforge.net/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [atlas]) or by setting
        the ATLAS environment variable.
      self.calc_info()
    lapack_info:
      libraries lapack not found in ['/home/docs/checkouts/readthedocs.org/user_builds/scikit-plot/envs/v0.3.2/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
      NOT AVAILABLE
    
    /home/docs/checkouts/readthedocs.org/user_builds/scikit-plot/envs/v0.3.2/local/lib/python2.7/site-packages/numpy/distutils/system_info.py:572: UserWarning:
        Lapack (http://www.netlib.org/lapack/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [lapack]) or by setting
        the LAPACK environment variable.
      self.calc_info()
    lapack_src_info:
      NOT AVAILABLE
    
    /home/docs/checkouts/readthedocs.org/user_builds/scikit-plot/envs/v0.3.2/local/lib/python2.7/site-packages/numpy/distutils/system_info.py:572: UserWarning:
        Lapack (http://www.netlib.org/lapack/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [lapack_src]) or by setting
        the LAPACK_SRC environment variable.
      self.calc_info()
      NOT AVAILABLE
    
    Running from scipy source directory.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-aaYEAX/scipy/setup.py", line 418, in <module>
        setup_package()
      File "/tmp/pip-build-aaYEAX/scipy/setup.py", line 414, in setup_package
        setup(**metadata)
      File "/home/docs/checkouts/readthedocs.org/user_builds/scikit-plot/envs/v0.3.2/local/lib/python2.7/site-packages/numpy/distutils/core.py", line 135, in setup
        config = configuration()
      File "/tmp/pip-build-aaYEAX/scipy/setup.py", line 336, in configuration
        config.add_subpackage('scipy')
      File "/home/docs/checkouts/readthedocs.org/user_builds/scikit-plot/envs/v0.3.2/local/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 1029, in add_subpackage
        caller_level = 2)
      File "/home/docs/checkouts/readthedocs.org/user_builds/scikit-plot/envs/v0.3.2/local/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 998, in get_subpackage
        caller_level = caller_level + 1)
      File "/home/docs/checkouts/readthedocs.org/user_builds/scikit-plot/envs/v0.3.2/local/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 935, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "scipy/setup.py", line 15, in configuration
        config.add_subpackage('linalg')
      File "/home/docs/checkouts/readthedocs.org/user_builds/scikit-plot/envs/v0.3.2/local/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 1029, in add_subpackage
        caller_level = 2)
      File "/home/docs/checkouts/readthedocs.org/user_builds/scikit-plot/envs/v0.3.2/local/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 998, in get_subpackage
        caller_level = caller_level + 1)
      File "/home/docs/checkouts/readthedocs.org/user_builds/scikit-plot/envs/v0.3.2/local/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 935, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "scipy/linalg/setup.py", line 19, in configuration
        raise NotFoundError('no lapack/blas resources found')
    numpy.distutils.system_info.NotFoundError: no lapack/blas resources found
    
    ----------------------------------------
Command "/home/docs/checkouts/readthedocs.org/user_builds/scikit-plot/envs/v0.3.2/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-aaYEAX/scipy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-PeD_7E-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/docs/checkouts/readthedocs.org/user_builds/scikit-plot/envs/v0.3.2/include/site/python2.7/scipy" failed with error code 1 in /tmp/pip-build-aaYEAX/scipy/
```
*A description of what actually happened*

This used to work. The only major change I can see is that latest scipy is now v1.0.0 and somehow it fails on this. I could try to force rtd-requirements to use v0.19 but then I'd have to bump my package another version. :( Please let me know if this is the only viable fix.

Edit: Looks like if I had released a version 6 hours earlier (pre-scipy 1.0) I wouldn't have had to face this. Oh well, first blood I guess :P

**Comment by agjohnson** [comment]
Pinning the requirements, or if you need scipy 1.0, using conda instead is the best way around dependency issues.

**Comment by reiinakano** [comment]
Sorry, I don't understand what you mean by pinning the requirements. I'm not sure how to use conda with rtd either, could you point me to some references?
