### ISSUE TITLE
"ImportError: No module named _csv" during RTD's own pip install step

### ISSUE THREAD

**Issue by edmorley** [rtfd/readthedocs.org#3219]
## Details

* Project URL: https://readthedocs.org/projects/treeherder/
* Build URL (if applicable): https://readthedocs.org/projects/treeherder/builds/6212486/

## Expected Result

For the `pip install` that that is initiated by RTD (rather than the one from our own requirements file) to succeed.

## Actual Result

The `pip install` step owned by RTD (ie the one that installs the various dependencies such as `sphinx-rtd-theme`) failed with:

```
$ python /home/docs/checkouts/readthedocs.org/user_builds/treeherder/envs/latest/bin/pip install --use-wheel --upgrade --cache-dir /home/docs/checkouts/readthedocs.org/user_builds/treeherder/.cache/pip Pygments==2.2.0 setuptools==28.8.0 docutils==0.13.1 mock==1.0.1 pillow==2.6.1 alabaster>=0.7,<0.8,!=0.7.5 commonmark==0.5.4 recommonmark==0.4.0 sphinx==1.5.6 sphinx-rtd-theme<0.3 readthedocs-sphinx-ext<0.6 

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/treeherder/envs/latest/bin/pip", line 7, in <module>
  File "/home/docs/checkouts/readthedocs.org/user_builds/treeherder/envs/latest/local/lib/python2.7/site-packages/pip/__init__.py", line 28, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/home/docs/checkouts/readthedocs.org/user_builds/treeherder/envs/latest/local/lib/python2.7/site-packages/pip/vcs/subversion.py", line 9, in <module>
    from pip.index import Link
  File "/home/docs/checkouts/readthedocs.org/user_builds/treeherder/envs/latest/local/lib/python2.7/site-packages/pip/index.py", line 31, in <module>
    from pip.wheel import Wheel, wheel_ext
  File "/home/docs/checkouts/readthedocs.org/user_builds/treeherder/envs/latest/local/lib/python2.7/site-packages/pip/wheel.py", line 7, in <module>
    import csv
  File "/usr/lib/python2.7/csv.py", line 8, in <module>
    from _csv import Error, __version__, writer, reader, register_dialect, \
ImportError: No module named _csv 
```

This error seems rather strange - I can't seem to find much online about it. 

Subsequent builds have passed without the need to clear the build cache.

**Comment by stsewd** [comment]
This is very strange, probably a virtualenv error with a corrupt environment as explained here (https://stackoverflow.com/questions/36478488/python-import-underscore-module/36479178#36479178). It probably will not happen again.

**Comment by edmorley** [comment]
Hi - thank you for the reply. I'm not sure the `support` label is correct - our project has worked fine for months (ie this wasn't a problem with us figuring out how to use RTD) and the failure occurred in the RTD bootstrap steps rather than our own requirements file. However given this hasn't occurred since I'm happy to just close it out and call it a one-off corruption bug :-)

**Comment by RichardLitt** [comment]
@edmorley Thanks for clarifying! Glad that you think this can be closed, regardless of my poor labelling. :)
