### ISSUE TITLE
RemovedInSphinx20Warning: builder.css_files is deprecated.

### ISSUE THREAD

**Issue by joachimwolff** [rtfd/readthedocs.org#3459]
Subject: Red the docs fails to build

### Problem
- I wanted to build the read the docs files, but it is crashing with the error message below. I asked already the sphinx project, they recommended to ask here. See https://github.com/sphinx-doc/sphinx/issues/4353

* Project URL: hicexplorer.readthedocs.io
* Build URL (if applicable): 
* Read the Docs username (if applicable): joachimwolff

#### Procedure to reproduce the problem
```
python /home/docs/checkouts/readthedocs.org/user_builds/hicexplorer/envs/master/bin/sphinx-build -T -b readthedocs -d _build/doctrees-readthedocs -D language=en . _build/html
```

## Actual Result
I got the following error:
```
Running Sphinx v1.6.5
making output directory...
loading translations [en]... done
/home/docs/checkouts/readthedocs.org/user_builds/hicexplorer/envs/master/local/lib/python2.7/site-packages/sphinx/util/compat.py:40: RemovedInSphinx17Warning: sphinx.util.compat.Directive is deprecated and will be removed in Sphinx 1.7, please use docutils' instead.
  RemovedInSphinx17Warning)
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [readthedocs]: targets for 27 source files that are out of date
updating environment: 27 added, 0 changed, 0 removed
reading sources... [  3%] content/HiCExport
reading sources... [  7%] content/News
reading sources... [ 11%] content/example_usage
reading sources... [ 14%] content/installation
reading sources... [ 18%] content/list-of-tools
reading sources... [ 22%] content/mES-HiC_analysis
reading sources... [ 25%] content/tools/findRestSite
reading sources... [ 29%] content/tools/hicBuildMatrix
reading sources... [ 33%] content/tools/hicCompareMatrices
reading sources... [ 37%] content/tools/hicCorrectMatrix
reading sources... [ 40%] content/tools/hicCorrelate
reading sources... [ 44%] content/tools/hicExport
reading sources... [ 48%] content/tools/hicFindEnrichedContacts
reading sources... [ 51%] content/tools/hicFindTADs
reading sources... [ 55%] content/tools/hicInfo
reading sources... [ 59%] content/tools/hicLog2Ratio
reading sources... [ 62%] content/tools/hicMergeMatrixBins
reading sources... [ 66%] content/tools/hicMergeTADbins
reading sources... [ 70%] content/tools/hicPCA
reading sources... [ 74%] content/tools/hicPlotDistVsCounts
reading sources... [ 77%] content/tools/hicPlotMatrix
reading sources... [ 81%] content/tools/hicPlotTADs
reading sources... [ 85%] content/tools/hicPlotViewpoint
reading sources... [ 88%] content/tools/hicQC
reading sources... [ 92%] content/tools/hicSumMatrices
reading sources... [ 96%] content/tools/hicTransform
reading sources... [100%] index

/home/docs/checkouts/readthedocs.org/user_builds/hicexplorer/checkouts/master/docs/content/News.rst:15: WARNING: Bullet list ends without a blank line; unexpected unindent.
/home/docs/checkouts/readthedocs.org/user_builds/hicexplorer/checkouts/master/docs/content/News.rst:18: WARNING: Block quote ends without a blank line; unexpected unindent.
/home/docs/checkouts/readthedocs.org/user_builds/hicexplorer/checkouts/master/docs/content/News.rst:41: WARNING: Bullet list ends without a blank line; unexpected unindent.
/home/docs/checkouts/readthedocs.org/user_builds/hicexplorer/checkouts/master/docs/content/News.rst:43: WARNING: Block quote ends without a blank line; unexpected unindent.
/home/docs/checkouts/readthedocs.org/user_builds/hicexplorer/checkouts/master/docs/content/example_usage.rst:: WARNING: image file not readable: content/../images/eigenvector1_lieberman.png
looking for now-outdated files... none found
pickling environment... done
checking consistency... /home/docs/checkouts/readthedocs.org/user_builds/hicexplorer/checkouts/master/docs/content/tools/findRestSite.rst: WARNING: document isn't included in any toctree
/home/docs/checkouts/readthedocs.org/user_builds/hicexplorer/checkouts/master/docs/content/tools/hicBuildMatrix.rst: WARNING: document isn't included in any toctree
/home/docs/checkouts/readthedocs.org/user_builds/hicexplorer/checkouts/master/docs/content/tools/hicCompareMatrices.rst: WARNING: document isn't included in any toctree
/home/docs/checkouts/readthedocs.org/user_builds/hicexplorer/checkouts/master/docs/content/tools/hicCorrectMatrix.rst: WARNING: document isn't included in any toctree
/home/docs/checkouts/readthedocs.org/user_builds/hicexplorer/checkouts/master/docs/content/tools/hicCorrelate.rst: WARNING: document isn't included in any toctree
/home/docs/checkouts/readthedocs.org/user_builds/hicexplorer/checkouts/master/docs/content/tools/hicExport.rst: WARNING: document isn't included in any toctree
/home/docs/checkouts/readthedocs.org/user_builds/hicexplorer/checkouts/master/docs/content/tools/hicFindEnrichedContacts.rst: WARNING: document isn't included in any toctree
/home/docs/checkouts/readthedocs.org/user_builds/hicexplorer/checkouts/master/docs/content/tools/hicFindTADs.rst: WARNING: document isn't included in any toctree
/home/docs/checkouts/readthedocs.org/user_builds/hicexplorer/checkouts/master/docs/content/tools/hicInfo.rst: WARNING: document isn't included in any toctree
/home/docs/checkouts/readthedocs.org/user_builds/hicexplorer/checkouts/master/docs/content/tools/hicLog2Ratio.rst: WARNING: document isn't included in any toctree
/home/docs/checkouts/readthedocs.org/user_builds/hicexplorer/checkouts/master/docs/content/tools/hicMergeMatrixBins.rst: WARNING: document isn't included in any toctree
/home/docs/checkouts/readthedocs.org/user_builds/hicexplorer/checkouts/master/docs/content/tools/hicMergeTADbins.rst: WARNING: document isn't included in any toctree
/home/docs/checkouts/readthedocs.org/user_builds/hicexplorer/checkouts/master/docs/content/tools/hicPCA.rst: WARNING: document isn't included in any toctree
/home/docs/checkouts/readthedocs.org/user_builds/hicexplorer/checkouts/master/docs/content/tools/hicPlotDistVsCounts.rst: WARNING: document isn't included in any toctree
/home/docs/checkouts/readthedocs.org/user_builds/hicexplorer/checkouts/master/docs/content/tools/hicPlotMatrix.rst: WARNING: document isn't included in any toctree
/home/docs/checkouts/readthedocs.org/user_builds/hicexplorer/checkouts/master/docs/content/tools/hicPlotTADs.rst: WARNING: document isn't included in any toctree
/home/docs/checkouts/readthedocs.org/user_builds/hicexplorer/checkouts/master/docs/content/tools/hicPlotViewpoint.rst: WARNING: document isn't included in any toctree
/home/docs/checkouts/readthedocs.org/user_builds/hicexplorer/checkouts/master/docs/content/tools/hicQC.rst: WARNING: document isn't included in any toctree
/home/docs/checkouts/readthedocs.org/user_builds/hicexplorer/checkouts/master/docs/content/tools/hicSumMatrices.rst: WARNING: document isn't included in any toctree
/home/docs/checkouts/readthedocs.org/user_builds/hicexplorer/checkouts/master/docs/content/tools/hicTransform.rst: WARNING: document isn't included in any toctree
done
preparing documents... done
writing output... [  3%] content/HiCExport

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/hicexplorer/envs/master/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 306, in main
    app.build(opts.force_all, filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/hicexplorer/envs/master/local/lib/python2.7/site-packages/sphinx/application.py", line 339, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/hicexplorer/envs/master/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 331, in build_update
    'out of date' % len(to_build))
  File "/home/docs/checkouts/readthedocs.org/user_builds/hicexplorer/envs/master/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 397, in build
    self.write(docnames, list(updated_docnames), method)
  File "/home/docs/checkouts/readthedocs.org/user_builds/hicexplorer/envs/master/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 434, in write
    self._write_serial(sorted(docnames))
  File "/home/docs/checkouts/readthedocs.org/user_builds/hicexplorer/envs/master/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 443, in _write_serial
    self.write_doc(docname, doctree)
  File "/home/docs/checkouts/readthedocs.org/user_builds/hicexplorer/envs/master/local/lib/python2.7/site-packages/sphinx/builders/html.py", line 561, in write_doc
    self.handle_page(docname, ctx, event_arg=doctree)
  File "/home/docs/checkouts/readthedocs.org/user_builds/hicexplorer/envs/master/local/lib/python2.7/site-packages/sphinx/builders/html.py", line 949, in handle_page
    templatename, ctx, event_arg)
  File "/home/docs/checkouts/readthedocs.org/user_builds/hicexplorer/envs/master/local/lib/python2.7/site-packages/sphinx/application.py", line 493, in emit_firstresult
    return self.events.emit_firstresult(event, self, *args)
  File "/home/docs/checkouts/readthedocs.org/user_builds/hicexplorer/envs/master/local/lib/python2.7/site-packages/sphinx/events.py", line 84, in emit_firstresult
    for result in self.emit(name, *args):
  File "/home/docs/checkouts/readthedocs.org/user_builds/hicexplorer/envs/master/local/lib/python2.7/site-packages/sphinx/events.py", line 79, in emit
    results.append(callback(*args))
  File "/home/docs/checkouts/readthedocs.org/user_builds/hicexplorer/envs/master/local/lib/python2.7/site-packages/readthedocs_ext/readthedocs.py", line 74, in update_body
    app.builder.css_files.insert(0, theme_css)
  File "/home/docs/checkouts/readthedocs.org/user_builds/hicexplorer/envs/master/local/lib/python2.7/site-packages/sphinx/builders/html.py", line 106, in insert
    RemovedInSphinx20Warning)
RemovedInSphinx20Warning: builder.css_files is deprecated. Please use app.add_stylesheet() instead.

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/hicexplorer/envs/master/local/lib/python2.7/site-packages/sphinx/builders/html.py", line 106, in insert
    RemovedInSphinx20Warning)
RemovedInSphinx20Warning: builder.css_files is deprecated. Please use app.add_stylesheet() instead.
The full traceback has been saved in /tmp/sphinx-err-qv76_y.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
`- <public link of unexpected result if you have>``
```

#### Expected results
Build the read the docs files ;) I can run it on my local machine with `make html` and it is working.
I know what this kind of error message means but I do not know how to fix it. 

### Reproducible project / your project
- https://github.com/deeptools/HiCExplorer

### Environment info
- Sphinx v1.6.5
- readthedocs.org with the following config file:

```
# -*- coding: utf-8 -*-
#
# HiCExplorer documentation build configuration file, created by
# sphinx-quickstart on Wed Sep 23 13:37:43 2015.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import sys
import os

# to allow readthedocs to compile without installing some dependencies
import mock

MOCK_MODULES = ['numpy', 'numpy.distutils.core', 'pandas', 'pysam', 'intervaltree',
                'scipy', 'scipy.sparse', 'scipy.stats',
                'matplotlib', 'matplotlib.pyplot', 'matplotlib.gridspec', 'matplotlib.ticker',
                'matplotlib.textpath', 'matplotlib.patches', 'matplotlib.colors', 'matplotlib.cm',
                'mpl_toolkits', 'mpl_toolkits.axisartist', 'mpl_toolkits.mplot3d', 'mpl_toolkits.axes_grid1',
                'Bio', 'Bio.Seq', 'Bio.Alphabet',
                'pyBigWig', 'tables', 'pytables', 'future', 'past', 'builtins', 'past.builtins',
                'future.utils', 'cooler', '__future__', 'logging']

for mod_name in MOCK_MODULES:
    sys.modules[mod_name] = mock.Mock()


# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
# sys.path.insert(0, os.path.abspath('.'))

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.doctest',
    'sphinxarg.ext'
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The encoding of source files.
# source_encoding = 'utf-8-sig'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = u'HiCExplorer'
copyright = u'2017, Fidel Ramírez, Bjoern Gruening, Vivek Bhardwaj, Joachim Wolff'
author = u'Fidel Ramírez, Bjoern Gruening, Vivek Bhardwaj, Joachim Wolff'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#


def get_version():
    import re
    try:
        f = open("../hicexplorer/_version.py")
    except EnvironmentError:
        return None
    for line in f.readlines():
        mo = re.match("__version__ = '([^']+)'", line)
        if mo:
            ver = mo.group(1)
            return ver
    return None


version = get_version()
# The full version, including alpha/beta/rc tags.
release = version

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
# today = ''
# Else, today_fmt is used as the format for a strftime call.
# today_fmt = '%B %d, %Y'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = ['_build']

# The reST default role (used for this markup: `text`) to use for all
# documents.
# default_role = None

# If true, '()' will be appended to :func: etc. cross-reference text.
# add_function_parentheses = True

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
# add_module_names = True

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
# show_authors = False

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# A list of ignored prefixes for module index sorting.
# modindex_common_prefix = []

# If true, keep warnings as "system message" paragraphs in the built documents.
# keep_warnings = False

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
on_rtd = os.environ.get('READTHEDOCS', None) == 'True'

if not on_rtd:  # only import and set the theme if we're building docs locally
    import sphinx_rtd_theme
    html_theme = 'sphinx_rtd_theme'
    html_theme_path = [sphinx_rtd_theme.get_html_theme_path()]

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
# html_theme_options = {}

# Add any paths that contain custom themes here, relative to this directory.
# html_theme_path = []

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
# html_title = None

# A shorter title for the navigation bar.  Default is the same as html_title.
# html_short_title = None

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
# html_logo = None

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
# html_favicon = None

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Add any extra paths that contain custom files (such as robots.txt or
# .htaccess) here, relative to this directory. These files are copied
# directly to the root of the documentation.
# html_extra_path = []

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
# html_last_updated_fmt = '%b %d, %Y'

# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
# html_use_smartypants = True

# Custom sidebar templates, maps document names to template names.
# html_sidebars = {}

# Additional templates that should be rendered to pages, maps page names to
# template names.
# html_additional_pages = {}

# If false, no module index is generated.
# html_domain_indices = True

# If false, no index is generated.
# html_use_index = True

# If true, the index is split into individual pages for each letter.
# html_split_index = False

# If true, links to the reST sources are added to the pages.
# html_show_sourcelink = True

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
# html_show_sphinx = True

# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
# html_show_copyright = True

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.  The value of this option must be the
# base URL from which the finished HTML is served.
# html_use_opensearch = ''

# This is the file name suffix for HTML files (e.g. ".xhtml").
# html_file_suffix = None

# Language to be used for generating the HTML full-text search index.
# Sphinx supports the following languages:
#   'da', 'de', 'en', 'es', 'fi', 'fr', 'hu', 'it', 'ja'
#   'nl', 'no', 'pt', 'ro', 'ru', 'sv', 'tr'
# html_search_language = 'en'

# A dictionary with options for the search language support, empty by default.
# Now only 'ja' uses this config value
# html_search_options = {'type': 'default'}

# The name of a javascript file (relative to the configuration directory) that
# implements a search results scorer. If empty, the default will be used.
# html_search_scorer = 'scorer.js'

# Output file base name for HTML help builder.
htmlhelp_basename = 'HiCExplorerdoc'

# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    # 'preamble': '',

    # Latex figure (float) alignment
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'HiCExplorer.tex', u'HiCExplorer Documentation',
     u'Fidel Ramírez', 'manual'),
]

# The name of an image file (relative to this directory) to place at the top of
# the title page.
# latex_logo = None

# For "manual" documents, if this is true, then toplevel headings are parts,
# not chapters.
# latex_use_parts = False

# If true, show page references after internal links.
# latex_show_pagerefs = False

# If true, show URL addresses after external links.
# latex_show_urls = False

# Documents to append as an appendix to all manuals.
# latex_appendices = []

# If false, no module index is generated.
# latex_domain_indices = True


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'hicexplorer', u'HiCExplorer Documentation',
     [author], 1)
]

# If true, show URL addresses after external links.
# man_show_urls = False


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'HiCExplorer', u'HiCExplorer Documentation',
     author, 'HiCExplorer', 'One line description of project.',
     'Miscellaneous'),
]

# Documents to append as an appendix to all manuals.
# texinfo_appendices = []

# If false, no module index is generated.
# texinfo_domain_indices = True

# How to display URL addresses: 'footnote', 'no', or 'inline'.
# texinfo_show_urls = 'footnote'

# If true, do not generate a @detailmenu in the "Top" node's menu.
# texinfo_no_detailmenu = False

```

**Comment by stsewd** [comment]
@joachimwolff I see your lasts builds are successful https://readthedocs.org/projects/hicexplorer/builds/ were you able to solve the issue?

**Comment by joachimwolff** [comment]
At one point we had to fix dependencies to older versions, see commit history: https://github.com/deeptools/HiCExplorer/commits/master/docs/requirements.txt

It looks like that the fixation of the versions is no longer required, therefore I would say it is fixed. 

@fidelram Can you tell us if it was just working or what needed to be changed for a fix? Thank you.

**Comment by fidelram** [comment]
We still have a different issue that suddenly appeared and that we can not replicate locally. The build passes but the documentation is incomplete. We are using sphinx-argparse to automatically capture the parameters of our python functions but this is no longer working. However, in an branch that has not been updated (the documentation branch) this worked fine.

The messages look like:

```
WARNING: Failed to import "parse_arguments" from "hicexplorer.hicPCA
```

Although the hicexplorer.hicPCA have the parse_arguments method

This is full list of warnings:
```
Release 2.1.1
------------
/home/docs/checkouts/readthedocs.org/user_builds/hicexplorer/checkouts/latest/docs/content/News.rst:47: WARNING: Bullet list ends without a blank line; unexpected unindent.
/home/docs/checkouts/readthedocs.org/user_builds/hicexplorer/checkouts/latest/docs/content/News.rst:50: WARNING: Block quote ends without a blank line; unexpected unindent.
/home/docs/checkouts/readthedocs.org/user_builds/hicexplorer/checkouts/latest/docs/content/News.rst:73: WARNING: Bullet list ends without a blank line; unexpected unindent.
/home/docs/checkouts/readthedocs.org/user_builds/hicexplorer/checkouts/latest/docs/content/News.rst:75: WARNING: Block quote ends without a blank line; unexpected unindent.
/home/docs/checkouts/readthedocs.org/user_builds/hicexplorer/checkouts/latest/docs/content/example_usage.rst:171: WARNING: Bullet list ends without a blank line; unexpected unindent.
/home/docs/checkouts/readthedocs.org/user_builds/hicexplorer/checkouts/latest/docs/content/example_usage.rst:176: WARNING: Bullet list ends without a blank line; unexpected unindent.
/home/docs/checkouts/readthedocs.org/user_builds/hicexplorer/checkouts/latest/docs/content/example_usage.rst:180: WARNING: Bullet list ends without a blank line; unexpected unindent.
/home/docs/checkouts/readthedocs.org/user_builds/hicexplorer/checkouts/latest/docs/content/tools/hicAggregateContacts.rst:17: WARNING: Failed to import "parse_arguments" from "hicexplorer.hicAggregateContacts"
/home/docs/checkouts/readthedocs.org/user_builds/hicexplorer/checkouts/latest/docs/content/tools/hicBuildMatrix.rst:6: WARNING: Failed to import "parse_arguments" from "hicexplorer.hicBuildMatrix"
/home/docs/checkouts/readthedocs.org/user_builds/hicexplorer/checkouts/latest/docs/content/tools/hicCompareMatrices.rst:17: WARNING: Failed to import "parse_arguments" from "hicexplorer.hicCompareMatrices"
/home/docs/checkouts/readthedocs.org/user_builds/hicexplorer/checkouts/latest/docs/content/tools/hicCorrectMatrix.rst:9: WARNING: Failed to import "parse_arguments" from "hicexplorer.hicCorrectMatrix"
/home/docs/checkouts/readthedocs.org/user_builds/hicexplorer/checkouts/latest/docs/content/tools/hicCorrelate.rst:17: WARNING: Failed to import "parse_arguments" from "hicexplorer.hicCorrelate"
/home/docs/checkouts/readthedocs.org/user_builds/hicexplorer/checkouts/latest/docs/content/tools/hicExport.rst:6: WARNING: Failed to import "parse_arguments" from "hicexplorer.hicExport"
/home/docs/checkouts/readthedocs.org/user_builds/hicexplorer/checkouts/latest/docs/content/tools/hicFindEnrichedContacts.rst:6: WARNING: Failed to import "parse_arguments" from "hicexplorer.hicFindEnrichedContacts"
/home/docs/checkouts/readthedocs.org/user_builds/hicexplorer/checkouts/latest/docs/content/tools/hicFindTADs.rst:12: WARNING: Failed to import "parse_arguments" from "hicexplorer.hicFindTADs"
/home/docs/checkouts/readthedocs.org/user_builds/hicexplorer/checkouts/latest/docs/content/tools/hicInfo.rst:6: WARNING: Failed to import "parse_arguments" from "hicexplorer.hicInfo"
/home/docs/checkouts/readthedocs.org/user_builds/hicexplorer/checkouts/latest/docs/content/tools/hicMergeMatrixBins.rst:17: WARNING: Failed to import "parse_arguments" from "hicexplorer.hicMergeMatrixBins"
/home/docs/checkouts/readthedocs.org/user_builds/hicexplorer/checkouts/latest/docs/content/tools/hicMergeTADbins.rst:6: WARNING: Failed to import "parse_arguments" from "hicexplorer.hicMergeTADbins"
/home/docs/checkouts/readthedocs.org/user_builds/hicexplorer/checkouts/latest/docs/content/tools/hicPCA.rst:6: WARNING: Failed to import "parse_arguments" from "hicexplorer.hicPCA"
/home/docs/checkouts/readthedocs.org/user_builds/hicexplorer/checkouts/latest/docs/content/tools/hicPlotDistVsCounts.rst:19: WARNING: Failed to import "parse_arguments" from "hicexplorer.hicPlotDistVsCounts"
/home/docs/checkouts/readthedocs.org/user_builds/hicexplorer/checkouts/latest/docs/content/tools/hicPlotMatrix.rst:6: WARNING: Failed to import "parse_arguments" from "hicexplorer.hicPlotMatrix"
/home/docs/checkouts/readthedocs.org/user_builds/hicexplorer/checkouts/latest/docs/content/tools/hicPlotTADs.rst:12: WARNING: Failed to import "parse_arguments" from "hicexplorer.hicPlotTADs"
/home/docs/checkouts/readthedocs.org/user_builds/hicexplorer/checkouts/latest/docs/content/tools/hicPlotViewpoint.rst:6: WARNING: Failed to import "parse_arguments" from "hicexplorer.hicPlotViewpoint"
/home/docs/checkouts/readthedocs.org/user_builds/hicexplorer/checkouts/latest/docs/content/tools/hicSumMatrices.rst:6: WARNING: Failed to import "parse_arguments" from "hicexplorer.hicSumMatrices"
```

**Comment by fidelram** [comment]
Just pick any of the latest builds, for example:

https://readthedocs.org/projects/hicexplorer/builds/7067814/

And then go to the last item on the page.

**Comment by stsewd** [comment]
@fidelram do you have checked the option ` Install your project inside a virtualenv using setup.py install` on the advanced settings of your project or try this https://github.com/sphinx-doc/sphinx/blob/master/sphinx/templates/quickstart/conf.py_t#L9

**Comment by fidelram** [comment]
Thanks for your info. The problem was solved by adding a now 'mock' module. We don't know why there was not a more specific error.

**Comment by stsewd** [comment]
@fidelram ok, I'm closing this issue then, feel free to open a new one if you have another problem.
