### ISSUE TITLE
elastic search indexing not working on local installation

### ISSUE THREAD

**Issue by xrmx** [rtfd/readthedocs.org#3697]
## Details

On a local RTD version as `09f8282be35c20dcca42c85d3f845bba8b784cfe` each project build returns the exception below and thus search does not work.
Elastic search is from docker image "elasticsearch:1.5.2" which should match the elasticsearch-py 1.5.0 from requirements. Same result with elasticsearch:1.7.6 docker image.

## Expected Result

Elastic search indexes updated after project build.

## Actual Result

The exception `ElasticsearchIllegalArgumentException[Can't specify parent if no parent field has been configured]` is raised

```
[28/Feb/2018 04:39:37] readthedocs.projects.tasks:779[21905]: INFO (Search Index) Sending Data: pip [user_guide news logic cookbook configuration development usage index quickstart installing reference/pip_show reference/pip reference/pip_hash reference/pip_freeze reference/pip_search reference/pip_uninstall reference/pip_download reference/index reference/pip_list reference/pip_install reference/pip_wheel]
[28/Feb/2018 04:39:37] readthedocs.restapi.utils:104[21905]: INFO Updating search index: project=pip pages=[user_guide news logic cookbook configuration development usage index quickstart installing reference/pip_show reference/pip reference/pip_hash reference/pip_freeze reference/pip_search reference/pip_uninstall reference/pip_download reference/index reference/pip_list reference/pip_install reference/pip_wheel]
[28/Feb/2018 04:39:37] celery.app.trace:248[21905]: ERROR Task readthedocs.projects.tasks.sync_callback[cfaf9e6d-6c5a-448b-8d02-9d4b205dba95] raised unexpected: RequestError(400, u"ElasticsearchIllegalArgumentException[Can't specify parent if no parent field has been configured]", {u'status': 400, u'error': u"ElasticsearchIllegalArgumentException[Can't specify parent if no parent field has been configured]"})
Traceback (most recent call last):
  File "/home/rm/src/readthedocs/rtd/local/lib/python2.7/site-packages/celery/app/trace.py", line 374, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/rm/src/readthedocs/rtd/checkouts/readthedocs.org/readthedocs/projects/tasks.py", line 1092, in sync_callback
    update_search(version_pk, commit=commit)
  File "/home/rm/src/readthedocs/rtd/local/lib/python2.7/site-packages/celery/local.py", line 191, in __call__
    return self._get_current_object()(*a, **kw)
  File "/home/rm/src/readthedocs/rtd/local/lib/python2.7/site-packages/celery/app/task.py", line 380, in __call__
    return self.run(*args, **kwargs)
  File "/home/rm/src/readthedocs/rtd/checkouts/readthedocs.org/readthedocs/projects/tasks.py", line 789, in update_search
    delete=delete_non_commit_files,
  File "/home/rm/src/readthedocs/rtd/checkouts/readthedocs.org/readthedocs/restapi/utils.py", line 169, in index_search_request
    page_obj.bulk_index(index_list, parent=project.slug, routing=route)
  File "/home/rm/src/readthedocs/rtd/checkouts/readthedocs.org/readthedocs/search/indexes.py", line 142, in bulk_index
    bulk_index(self.es, docs, chunk_size=chunk_size)
  File "/home/rm/src/readthedocs/rtd/local/lib/python2.7/site-packages/elasticsearch/helpers/__init__.py", line 182, in bulk
    for ok, item in streaming_bulk(client, actions, **kwargs):
  File "/home/rm/src/readthedocs/rtd/local/lib/python2.7/site-packages/elasticsearch/helpers/__init__.py", line 124, in streaming_bulk
    raise e
RequestError: TransportError(400, u"ElasticsearchIllegalArgumentException[Can't specify parent if no parent field has been configured]")
```

**Comment by xrmx** [comment]
So this makes the indexing works fine but definetely not a fix

```
diff --git a/readthedocs/search/indexes.py b/readthedocs/search/indexes.py
index 1b2ede6a..f71cf934 100644
--- a/readthedocs/search/indexes.py
+++ b/readthedocs/search/indexes.py
@@ -132,7 +132,7 @@ class Index(object):
                 '_id': source['id'],
                 '_source': source,
             }
-            if parent:
+            if parent and False:
                 doc['_parent'] = parent
             if routing:
                 doc['_routing'] = routing
```

**Comment by gaborbernat** [comment]
@xrmx do you get this error with ES 1.3.9 too?

**Comment by xrmx** [comment]
@gaborbernat Ii'm using elasticsearch from docker and there's no docker image for 1.3.9. Anyway I'm dog fooding the elasticsearch5 branch so if I think we can close this as dup of #3803.

**Comment by gaborbernat** [comment]
I see. I'm using 1.3.9 and still getting this error. ES5 will be nice, might take a few days to merge though :thinking:

**Comment by stsewd** [comment]
The guide was merged, you can see it in https://docs.readthedocs.io/en/latest/custom_installs/elasticsearch.html
