### ISSUE TITLE
Build failing and stuck at Triggered state at local installation

### ISSUE THREAD

**Issue by rajujha373** [rtfd/readthedocs.org#3836]
At the local installation of RTD when a new project is imported, the build is failing with the following error message.
<pre>
[23/Mar/2018 06:36:06] readthedocs.projects.tasks:284[14368]: ERROR An unhandled exception was raised during build setup
Traceback (most recent call last):
  File "/home/raj/Desktop/opensource/READTHEDOCS/readthedocs.org/readthedocs/projects/tasks.py", line 268, in run
    self.project = self.get_project(pk)
  File "/home/raj/Desktop/opensource/READTHEDOCS/readthedocs.org/readthedocs/projects/tasks.py", line 424, in get_project
    project_data = api_v2.project(project_pk).get()
  File "/home/raj/Desktop/opensource/READTHEDOCS/venv3/lib/python3.5/site-packages/slumber/__init__.py", line 155, in get
    resp = self._request("GET", params=kwargs)
  File "/home/raj/Desktop/opensource/READTHEDOCS/venv3/lib/python3.5/site-packages/slumber/__init__.py", line 101, in _request
    raise exception_class("Client Error %s: %s" % (resp.status_code, url), response=resp, content=resp.content)
slumber.exceptions.HttpClientError: Client Error 403: http://localhost:8000/api/v2/project/26/
[23/Mar/2018 06:36:06] celery.app.trace:248[14368]: ERROR Task readthedocs.projects.tasks.update_docs[13361472-0910-4c73-a7df-fe8f5d200740] raised unexpected: AttributeError("'UpdateDocsTask' object has no attribute 'setup_env'",)
Traceback (most recent call last):
  File "/home/raj/Desktop/opensource/READTHEDOCS/readthedocs.org/readthedocs/projects/tasks.py", line 268, in run
    self.project = self.get_project(pk)
  File "/home/raj/Desktop/opensource/READTHEDOCS/readthedocs.org/readthedocs/projects/tasks.py", line 424, in get_project
    project_data = api_v2.project(project_pk).get()
  File "/home/raj/Desktop/opensource/READTHEDOCS/venv3/lib/python3.5/site-packages/slumber/__init__.py", line 155, in get
    resp = self._request("GET", params=kwargs)
  File "/home/raj/Desktop/opensource/READTHEDOCS/venv3/lib/python3.5/site-packages/slumber/__init__.py", line 101, in _request
    raise exception_class("Client Error %s: %s" % (resp.status_code, url), response=resp, content=resp.content)
slumber.exceptions.HttpClientError: Client Error 403: http://localhost:8000/api/v2/project/26/
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/raj/Desktop/opensource/READTHEDOCS/venv3/lib/python3.5/site-packages/celery/app/trace.py", line 374, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/raj/Desktop/opensource/READTHEDOCS/readthedocs.org/readthedocs/projects/tasks.py", line 288, in run
    build_id=build_pk,
AttributeError: 'UpdateDocsTask' object has no attribute 'setup_env'
</pre>

I tried installing setup_env using <code>pip install setup_env</code> in two different virtualenv of python3 and python2 as well. 
While python2 doesn't support <code>setup_env</code>, installing it with python3 doesn't solve the problem as well.
![screenshot from 2018-03-23 17-00-50](https://user-images.githubusercontent.com/16777442/37827668-6be284c4-2ebe-11e8-8f81-cde11d00f524.png)

**Comment by stsewd** [comment]
`setup_env'` is a method declared on the rtd source code, so you don't need to installed it. Did you change the port when running `python manage runserver`?

**Comment by rajujha373** [comment]
Yes, I did. I tried to run the server at 
<code> 0.0.0.0:8080 </code>
 <code> 127.0.0.1:8000 </code> 
<code> 0.0.0.0:8000 </code> and 
<code> 127.0.0.1:8080 </code>
but with no success

**Comment by stsewd** [comment]
@rajujha373 did you follow the instructions when changing the port?

> For builds to properly kick off as expected, it is necessary the port you’re serving on (i.e. runserver 0.0.0.0:8080) match the port defined in PRODUCTION_DOMAIN. You can utilize local_settings.py to modify this. (By default, it’s localhost:8000)

https://docs.readthedocs.io/en/latest/install.html

Also here is a _better guide_ that maybe you can follow https://github.com/rtfd/readthedocs.org/pull/3631

**Comment by rajujha373** [comment]
yes, @stsewd I followed the steps given at #3631 but sadly the problem still persists for me.

**Comment by stsewd** [comment]
There is something special with the network or the computer you are running? Also, can you try building without the `PDF` and `Epub` options enabled? (this is under the project admin section)

**Comment by stsewd** [comment]
@rajujha373 hey, were you able to solve this?

**Comment by grimmlink** [comment]
Hi,

I was having the same problem : 
```
HttpClientError: Client Error 403: http://localhost:8000/api/v2/project/1/
```

When i opened the URL `/api/v2/project/1/` then it works and i get the JSON data while the server gets a 403

So then it was a permission issue: i just added the parameters in local_settings
SLUMBER_USERNAME = '***'
SLUMBER_PASSWORD = '***'

**Comment by stsewd** [comment]
Closing this as the user [hasn't responded or given more information](https://docs.readthedocs.io/en/latest/contribute.html#initial-triage), feel free to reopen with more information if you are still having this problem :).

Also there is pointed solution https://github.com/rtfd/readthedocs.org/issues/3836#issuecomment-389203663

**Comment by Trigun27** [comment]
> Hi,
> 
> I was having the same problem :
> 
> ```
> HttpClientError: Client Error 403: http://localhost:8000/api/v2/project/1/
> ```
> When i opened the URL `/api/v2/project/1/` then it works and i get the JSON data while the server gets a 403
> 
> So then it was a permission issue: i just added the parameters in local_settings
> SLUMBER_USERNAME = '***'
> SLUMBER_PASSWORD = '***'

Hi, can you help me pls. You just add SLUMBER_USERNAME  to local_settings and whar username did you  use? 
thnaks

**Comment by git-abhijit** [comment]
Hi, 
Can you please share the details of the SLUMBER_USERNAME and SLUMBER_PASSWORD ? 

Like can we give the user name and password given while executing python manage.py createsuperuser ?
