### ISSUE TITLE
`cannot import name new_document` exception on latex extension

### ISSUE THREAD

**Issue by martingalloar** [rtfd/readthedocs.org#4115]
## Details

* Read the Docs project URL: http://pysap.readthedocs.io/
* Build URL (if applicable): http://readthedocs.org/projects/pysap/builds/7215941/
* Read the Docs username (if applicable): martingalloar

## Expected Result

Successful build (as in Travis for example https://travis-ci.org/CoreSecurity/pysap/jobs/381096678#L1456)

## Actual Result

Build failed with the following exception:

```
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pysap/envs/latest/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 305, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pysap/envs/latest/local/lib/python2.7/site-packages/sphinx/application.py", line 192, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pysap/envs/latest/local/lib/python2.7/site-packages/sphinx/application.py", line 456, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pysap/envs/latest/local/lib/python2.7/site-packages/sphinx/registry.py", line 199, in load_extension
    raise ExtensionError(__('Could not import extension %s') % extname, err)
ExtensionError: Could not import extension sphinx.builders.latex (exception: cannot import name new_document)

Extension error:
Could not import extension sphinx.builders.latex (exception: cannot import name new_document)
```

**Comment by LoganMcKenzie** [comment]
I came across this error and for me it was related to https://github.com/pypa/pip/issues/5221, and maybe other malfunctioning installations. Check the installs on your system, especially pip.
