### ISSUE TITLE
API calls fail on new installation

### ISSUE THREAD

**Issue by boerngen-schmidt** [rtfd/readthedocs.org#4126]
## Details

Documentation is not build when DB Backend is set to Postgresql

## Expected Result

Documentation being build

## Actual Result
```
[22/May/2018 19:05:26] "POST /dashboard/import/manual/ HTTP/1.1" 200 16617
[22/May/2018 19:05:34] readthedocs.core.symlink:93[504]: INFO (Build) [bess-docs:] Symlinking Version: Version latest of BESS Docs (1)
[22/May/2018 19:05:34] celery.app.trace:124[504]: INFO Task readthedocs.projects.tasks.symlink_project[4ab716c0-b1dc-466d-bcff-e7f56da66fc0] succeeded in 0.227485799998s: None
[22/May/2018 19:05:34] readthedocs.projects.models:333[504]: INFO Re-symlinking project and subprojects: project=bess-docs
[22/May/2018 19:05:34] readthedocs.core.symlink:93[504]: INFO (Build) [bess-docs:] Symlinking Version: Version latest of BESS Docs (1)
[22/May/2018 19:05:35] celery.app.trace:124[504]: INFO Task readthedocs.projects.tasks.symlink_project[55772c8d-77d9-4c96-a874-535c1f4eabb1] succeeded in 0.0841775999979s: None
[22/May/2018 19:05:35] readthedocs.projects.models:342[504]: INFO Re-symlinking superprojects: project=bess-docs
[22/May/2018 19:05:35] readthedocs.projects.tasks:1091[504]: INFO (Build) [bess-docs:] Updating static metadata
[22/May/2018 19:05:35] celery.app.trace:124[504]: INFO Task readthedocs.projects.tasks.update_static_metadata[9673620e-4c48-49df-ba6a-d9551e654f6e] succeeded in 0.0368913999991s: None
[22/May/2018 19:05:35] "GET /api/v2/project/1/ HTTP/1.1" 403 39
[22/May/2018 19:05:35] readthedocs.projects.tasks:328[504]: ERROR An unhandled exception was raised during build setup
Traceback (most recent call last):
  File "/home/rtd/readthedocs.org/readthedocs/projects/tasks.py", line 312, in run
    self.project = self.get_project(pk)
  File "/home/rtd/readthedocs.org/readthedocs/projects/tasks.py", line 477, in get_project
    project_data = api_v2.project(project_pk).get()
  File "/home/rtd/venv/lib/python2.7/site-packages/slumber/__init__.py", line 155, in get
    resp = self._request("GET", params=kwargs)
  File "/home/rtd/venv/lib/python2.7/site-packages/slumber/__init__.py", line 101, in _request
    raise exception_class("Client Error %s: %s" % (resp.status_code, url), response=resp, content=resp.content)
HttpClientError: Client Error 403: http://rtd.be.local:8000/api/v2/project/1/
[22/May/2018 19:05:35] celery.app.trace:249[504]: ERROR Task readthedocs.projects.tasks.update_docs[6ee92c59-3dd2-49a6-9c42-37effa4f2c8d] raised unexpected: AttributeError("'UpdateDocsTaskStep' object has no attribute 'setup_env'",)
Traceback (most recent call last):
  File "/home/rtd/venv/lib/python2.7/site-packages/celery/app/trace.py", line 375, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/rtd/readthedocs.org/readthedocs/projects/tasks.py", line 227, in run
    return step.run(*args, **kwargs)
  File "/home/rtd/readthedocs.org/readthedocs/projects/tasks.py", line 332, in run
    build_id=build_pk,
AttributeError: 'UpdateDocsTaskStep' object has no attribute 'setup_env'
[22/May/2018 19:05:35] "POST /dashboard/import/manual/ HTTP/1.1" 302 0
```

Once I comment out the following block in my local_settings.py
```python
DATABASES = {
  'default': {
    'ENGINE': 'django.db.backends.postgresql_psycopg2',
    'NAME': 'rtd',
    'USER': 'rtd',
    'PASSWORD': 'rtd',
    'HOST': 'db'
  }
}
```
it works fine again, since it will be using the default sqlite backend. Or am I just missing a setting?

**Comment by safwanrahman** [comment]
Seems like you do not generate dumpdata after adding postgress as database!

**Comment by boerngen-schmidt** [comment]
@safwanrahman care to elaborate a little more on the term "dumpdata". I do not understand what you mean by this. I found https://docs.djangoproject.com/en/2.0/ref/django-admin/#dumpdata but I do not want to dump any data, since there is none. 
According to the docs it is not nessesary to load the sample data, if I set slumber username and password, but I'll give it a try tomorrow.

**Comment by agjohnson** [comment]
The API call is failing, this isn't related to Postgres. My guess is that the API user is either missing or misconfigured.

**Comment by stsewd** [comment]
I think you are missing the api configuration for the slumber_username, you can see it here https://docs.readthedocs.io/en/latest/install.html.

Closing this as the user [hasn't responded or given more information](https://docs.readthedocs.io/en/latest/contribute.html#initial-triage), feel free to reopen with more information if you are still having this problem :).
