### ISSUE TITLE
UpdateDocsTaskStep fails becasue api returns wrong type

### ISSUE THREAD

**Issue by xrmx** [rtfd/readthedocs.org#4157]
## Details

With python3.5 sometimes the call to the slumber client in UpdateDocsTaskStep.get_project returns a bytestring and not a dict. The data inside the bytestring is just fine and decoding as json works correctly.

```
[readthedocs.projects.tasks:328]
Traceback (most recent call last):
 File "/docs.italia.it/readthedocs/projects/tasks.py", line 312, in run
   self.project = self.get_project(pk)
 File "/docs.italia.it/readthedocs/projects/tasks.py", line 478, in get_project
   return APIProject(**project_data)
TypeError: ModelBase object argument after ** must be a mapping, not bytes
```

I can reproduce this easily the first time the celery worker for the build is restarted.

I can easily workaround this bug by trying to decode and unserialize the json and willing to do a PR with that if it's fine for you.

## Expected Result

api_v2.project(project_pk).get() returns a dict

## Actual Result

api_v2.project(project_pk).get() returns a byte string

**Comment by xrmx** [comment]
With easy workaround i mean something like this:

```
diff --git a/readthedocs/projects/tasks.py b/readthedocs/projects/tasks.py
index d871eb0..f3c6e44 100644
--- a/readthedocs/projects/tasks.py
+++ b/readthedocs/projects/tasks.py
@@ -475,6 +475,9 @@ class UpdateDocsTaskStep(SyncRepositoryMixin):
     def get_project(project_pk):
         """Get project from API."""
         project_data = api_v2.project(project_pk).get()
+        # workaround for getting bytes instead of deserialized json
+        if isinstance(project_data, bytes):
+            project_data = json.loads(project_data.decode())
         return APIProject(**project_data)
 
     @staticmethod
```

**Comment by xrmx** [comment]
Found the root cause:
```
Traceback (most recent call last): [celery.redirected:235]
File "/virtualenv/lib/python3.5/site-packages/slumber/__init__.py", line 134, in _try_to_serialize_response
    return stype.loads(resp.content.decode(encoding)) [celery.redirected:235]
File "/home/readthedocs/restapi/client.py", line 28, in loads
    return JSONParser().parse(data) [celery.redirected:235]
File "/virtualenv/lib/python3.5/site-packages/rest_framework/parsers.py", line 66, in parse
    return json.load(decoded_stream) [celery.redirected:235]
File "/usr/lib/python3.5/json/__init__.py", line 265, in load
      return loads(fp.read(), [celery.redirected:235]
File "/usr/lib/python3.5/codecs.py", line 493, in read
     newdata = self.stream.read() [celery.redirected:235]
AttributeError: 'str' object has no attribute 'read' [celery.redirected:235]
```

**Comment by agjohnson** [comment]
We aren't seeing this in production or development, though we also aren't going to support python 3.5. Does the same happen with Python 3.6?

I think we need more information to verify this.

**Comment by xrmx** [comment]
I've added a PR with a test that should fail with the actual code. The commit contains a stacktrace and an explanation of what is happening. Just look at DRF parser code and the slumber one that is extended and you'll see that they are expecting two different types.
