### ISSUE TITLE
Requiring psychopy exceeds build memory limits, build fails.

### ISSUE THREAD

**Issue by jfkominsky** [rtfd/readthedocs.org#4295]
Short version: RTD cannot compile any project that requires psychopy with sphinx autodoc documentation because pip installing psychopy exceeds the memory limits.

## Details

* Read the Docs project URL: https://pyhab.readthedocs.io/en/latest/

## Expected Result

Just tried to build documentation for this project: https://github.com/jfkominsky/PyHab 
Using Sphinx and autodoc to get function docstrings from each class. Autodoc requires importing everything at the top of a file. One essential package is not part of RTD, psychopy, so I added a requirements file with just psychopy to pip install it in the virtualenv. 

## Actual Result
With Py2:
[7387131.txt](https://github.com/rtfd/readthedocs.org/files/2133186/7387131.txt)

Here's the error message itself:

> [rtd-command-info] start-time: 2018-06-23T17:48:11.977771, end-time: 2018-06-23T17:48:21.570270, duration: 9, exit-code: 137
> python /home/docs/checkouts/readthedocs.org/user_builds/pyhab/envs/latest/bin/pip install --exists-action=w --cache-dir /home/docs/checkouts/readthedocs.org/user_builds/pyhab/.cache/pip -r/home/docs/checkouts/readthedocs.org/user_builds/pyhab/checkouts/latest/docs/requirements.txt
> Command killed due to excessive memory consumption

I tried again with Py3 and got a different error:

> ERROR: failed building wxWidgets
>     Traceback (most recent call last):
>       File "build.py", line 1321, in cmd_build_wx
>         wxbuild.main(wxDir(), build_options)
>       File "/tmp/pip-build-7a1lqn7v/wxPython/buildtools/build_wxwidgets.py", line 374, in main
>         "Error running configure")
>       File "/tmp/pip-build-7a1lqn7v/wxPython/buildtools/build_wxwidgets.py", line 85, in exitIfError
>         raise builder.BuildError(msg)
>     buildtools.builder.BuildError: Error running configure
>     Finished command: build_wx (0m10.842s)
>     Finished command: build (0m10.842s)
>     Command '"/home/docs/checkouts/readthedocs.org/user_builds/pyhab/envs/latest/bin/python" -u build.py build' failed with exit code 1.

**Comment by jfkominsky** [comment]
RESOLVED (kinda): I just mocked everything I needed by putting mock in the requirements file and making all the problematic modules into mock.MagicMock() objects in conf.py.
