### ISSUE TITLE
Build has begun failing (ID: 7552524)

### ISSUE THREAD

**Issue by urschrei** [rtfd/readthedocs.org#4440]
## Details

* Read the Docs project URL:
https://pyzotero.readthedocs.org
* Build URL (if applicable):
Latest failing: https://readthedocs.org/projects/pyzotero/builds/7552524/
First failing: https://readthedocs.org/projects/pyzotero/builds/7352876/
Latest passing: https://readthedocs.org/projects/pyzotero/builds/7191653/
* Read the Docs username (if applicable):
urschrei

I've just noticed that the build has been failing for a while – it began failing following this commit: https://github.com/urschrei/pyzotero/commit/bb5c7ac3c2d39092396f003fef8493eb00f74262, which is odd, as it has no obvious effect on the build. Wiping the build environment hasn't had any effect, and there's nothing obvious in the raw build logs either.

**Comment by humitos** [comment]
@urschrei thanks for reporting this.

I found the issue. It's a bug on our side and it's because the library we use to get some information from git repositories: `gitpython`.

There is a problem when reading the `tags`:

```
Traceback (most recent call last):
  File "/home/humitos/rtfd/code/readthedocs.org/readthedocs/projects/tasks.py", line 412, in run_setup
    self.setup_vcs()
  File "/home/humitos/rtfd/code/readthedocs.org/readthedocs/projects/tasks.py", line 540, in setup_vcs
    self.sync_repo()
  File "/home/humitos/rtfd/code/readthedocs.org/readthedocs/projects/tasks.py", line 133, in sync_repo
    } for v in version_repo.tags
  File "/home/humitos/rtfd/code/readthedocs.org/readthedocs/vcs_support/backends/git.py", line 129, in tags
    for tag in repo.tags
  File "/home/humitos/rtfd/code/readthedocs.org/readthedocs/vcs_support/backends/git.py", line 129, in <listcomp>
    for tag in repo.tags
  File "/home/humitos/.pyenv/versions/3.6.6/envs/readthedocs.org/lib/python3.6/site-packages/git/refs/tag.py", line 35, in commit
    "use the `.object` property instead to access it") % (self, obj.type))
ValueError: Cannot resolve commit as tag maintainer-gpg-pub points to a blob object - use the `.object` property instead to access it
```

I followed what the error message says but I'm not sure if that's what we want to do yet:

```
In [25]: repo.tags[0]
Out[25]: <git.TagReference "refs/tags/maintainer-gpg-pub">

In [26]: _.object.hexsha
Out[26]: 'af1bfa70250df34409c086ea993779989f800fa1'
```

As a workaround, you can remove the tag `maintainer-gpg-pub` from your repo and your build will start running properly.

I'll try to propose a fix soon.
