### ISSUE TITLE
Validate conf.py before build docs

### ISSUE THREAD

**Issue by humitos** [rtfd/readthedocs.org#4745]
This build https://readthedocs.org/projects/wagtail/builds/7918857/ produced a log into Sentry as an ERROR https://sentry.io/read-the-docs/readthedocs-org/issues/712546002/?query=is:unresolved which is annoying. These exceptions are raised to communicate a specific message to the user and shouldn't be logged as ERROR for us to take a look at.

> I'm not sure if this is already implemented in v2 of our configuration or not.

There is some related work at #4495 and #4590.

**Comment by stsewd** [comment]
I think this happens when we try to find a`conf.py` file for the user and we found more than one. With v2 we still keep the `find automatically` magic.

**Comment by invinciblycool** [comment]
@stsewd So it this supposed to be fixed? If yes, I would like to take a stab at it.

**Comment by stsewd** [comment]
@invinciblycool we can't validate this on the config module because we put None when rtd needs to find the file automatically, I think there is a case where rtd fails to find one or there are multiple config files, we need to dig a little more to see the entire flow and see how we want to fix this.

**Comment by stsewd** [comment]
We haven't seen this in ~2 months, we should test if this can be replicated. I think it was raised when the project has 2 `conf.py` files, and isn't using a config file.

**Comment by stsewd** [comment]
I was able to replicate this locally

```
Traceback (most recent call last):
  File "/home/stsewd/rtd/readthedocs.org/readthedocs/doc_builder/backends/sphinx.py", line 176, in append_conf
    self.config_file or self.project.conf_file(self.version.slug)
  File "/home/stsewd/rtd/readthedocs.org/readthedocs/projects/models.py", line 719, in conf_file
    ProjectConfigurationError.MULTIPLE_CONF_FILES,
readthedocs.projects.exceptions.ProjectConfigurationError: We found more than one conf.py and are not sure which one to use. Please, specify the correct file under the Advanced settings tab
 in the project's Admin.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stsewd/rtd/readthedocs.org/readthedocs/projects/tasks.py", line 565, in run_build
    outcomes = self.build_docs()
  File "/home/stsewd/rtd/readthedocs.org/readthedocs/projects/tasks.py", line 830, in build_docs
    outcomes['html'] = self.build_docs_html()
  File "/home/stsewd/rtd/readthedocs.org/readthedocs/projects/tasks.py", line 847, in build_docs_html
    html_builder.append_conf()
  File "/home/stsewd/rtd/readthedocs.org/readthedocs/doc_builder/backends/sphinx.py", line 183, in append_conf
    ).with_traceback(trace)
  File "/home/stsewd/rtd/readthedocs.org/readthedocs/doc_builder/backends/sphinx.py", line 176, in append_conf
    self.config_file or self.project.conf_file(self.version.slug)
  File "/home/stsewd/rtd/readthedocs.org/readthedocs/projects/models.py", line 719, in conf_file
    ProjectConfigurationError.MULTIPLE_CONF_FILES,
readthedocs.projects.exceptions.ProjectConfigurationError: A configuration file was not found. Make sure you have a conf.py file in your repository.
```

with this structure

```
├── conf.py
├── more
│   └── conf.py
├── README.rst
└── requirements.txt
```

**Comment by dojutsu-user** [comment]
@stsewd 
Is this still valid?

**Comment by stsewd** [comment]
Yeah, I think we fail with a general exception with the above structure https://github.com/rtfd/readthedocs.org/issues/4745#issuecomment-470754025

**Comment by dojutsu-user** [comment]
@stsewd 
I am not sure as what needs to be done here.
Can you provide some details here.

**Comment by NewishBrand** [comment]
www.mynewish.com
