### ISSUE TITLE
Unclean package installation when virtualenv option is enabled

### ISSUE THREAD

**Issue by mueslo** [rtfd/readthedocs.org#4968]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/fplore/
* Build URLs: 
   * https://readthedocs.org/projects/fplore/builds/8212795/
   * https://readthedocs.org/projects/fplore/builds/8213217/

## Expected Result

Documentation builds fine as it did previously and as it does locally.

## Actual Result

Build errors.

```
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/fplore/envs/latest/bin/sphinx-build", line 7, in <module>
    from sphinx.cmd.build import main
  File "/home/docs/checkouts/readthedocs.org/user_builds/fplore/envs/latest/lib/python3.5/site-packages/sphinx/cmd/build.py", line 25, in <module>
    from sphinx.application import Sphinx
  File "/home/docs/checkouts/readthedocs.org/user_builds/fplore/envs/latest/lib/python3.5/site-packages/sphinx/application.py", line 34, in <module>
    from sphinx.environment import BuildEnvironment
  File "/home/docs/checkouts/readthedocs.org/user_builds/fplore/envs/latest/lib/python3.5/site-packages/sphinx/environment/__init__.py", line 38, in <module>
    from sphinx.util.websupport import is_commentable
  File "/home/docs/checkouts/readthedocs.org/user_builds/fplore/envs/latest/lib/python3.5/site-packages/sphinx/util/websupport.py", line 11, in <module>
    from sphinxcontrib.websupport.utils import is_commentable  # NOQA
  File "/home/docs/checkouts/readthedocs.org/user_builds/fplore/envs/latest/lib/python3.5/site-packages/sphinxcontrib/websupport/__init__.py", line 13, in <module>
    __import__('pkg_resources').declare_namespace(__name__)
  File "/home/docs/checkouts/readthedocs.org/user_builds/fplore/envs/latest/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3017, in <module>
    @_call_aside
  File "/home/docs/checkouts/readthedocs.org/user_builds/fplore/envs/latest/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/fplore/envs/latest/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3045, in _initialize_master_working_set
    dist.activate(replace=False)
  File "/home/docs/checkouts/readthedocs.org/user_builds/fplore/envs/latest/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2577, in activate
    declare_namespace(pkg)
  File "/home/docs/checkouts/readthedocs.org/user_builds/fplore/envs/latest/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2151, in declare_namespace
    _handle_ns(packageName, path_item)
  File "/home/docs/checkouts/readthedocs.org/user_builds/fplore/envs/latest/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2091, in _handle_ns
    _rebuild_mod_path(path, packageName, module)
  File "/home/docs/checkouts/readthedocs.org/user_builds/fplore/envs/latest/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2120, in _rebuild_mod_path
    orig_path.sort(key=position_in_sys_path)
AttributeError: '_NamespacePath' object has no attribute 'sort'
```

and sometimes

```
Using base prefix '/usr'
New python executable in /home/docs/checkouts/readthedocs.org/user_builds/fplore/envs/latest/bin/python3.5
Not overwriting existing python script /home/docs/checkouts/readthedocs.org/user_builds/fplore/envs/latest/bin/python (you must use /home/docs/checkouts/readthedocs.org/user_builds/fplore/envs/latest/bin/python3.5)
Installing setuptools, pip, wheel...
  Complete output from command /home/docs/checkouts...latest/bin/python3.5 - setuptools pip wheel:
  Traceback (most recent call last):
  File "<stdin>", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/usr/local/lib/python3.5/dist-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/__init__.py", line 26, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/usr/local/lib/python3.5/dist-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/utils/__init__.py", line 27, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/usr/local/lib/python3.5/dist-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/_vendor/pkg_resources/__init__.py", line 3018, in <module>
  File "/usr/local/lib/python3.5/dist-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/_vendor/pkg_resources/__init__.py", line 3004, in _call_aside
  File "/usr/local/lib/python3.5/dist-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/_vendor/pkg_resources/__init__.py", line 3046, in _initialize_master_working_set
  File "/usr/local/lib/python3.5/dist-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/_vendor/pkg_resources/__init__.py", line 2578, in activate
  File "/usr/local/lib/python3.5/dist-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/_vendor/pkg_resources/__init__.py", line 2152, in declare_namespace
  File "/usr/local/lib/python3.5/dist-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/_vendor/pkg_resources/__init__.py", line 2092, in _handle_ns
  File "/usr/local/lib/python3.5/dist-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/_vendor/pkg_resources/__init__.py", line 2121, in _rebuild_mod_path
AttributeError: '_NamespacePath' object has no attribute 'sort'
----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/virtualenv.py", line 2328, in <module>
    main()
  File "/usr/local/lib/python3.5/dist-packages/virtualenv.py", line 713, in main
    symlink=options.symlink)
  File "/usr/local/lib/python3.5/dist-packages/virtualenv.py", line 945, in create_environment
    download=download,
  File "/usr/local/lib/python3.5/dist-packages/virtualenv.py", line 901, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/usr/local/lib/python3.5/dist-packages/virtualenv.py", line 797, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /home/docs/checkouts...latest/bin/python3.5 - setuptools pip wheel failed with error code 1
```

**Comment by stsewd** [comment]
Can you try wiping the environment before build? `Versions` -> `Edit` -> `Wipe`

**Comment by mueslo** [comment]
That potentially fixed it.

I was looking for an option like that under the admin part of the control panel, but since it wasn't there, I assumed it clears it every run.

Now I'm getting new issues which do not occur locally, but I'm not sure yet why they occur (https://readthedocs.org/projects/fplore/builds/8213711/)

**Comment by mueslo** [comment]
I attempted to create a [minimum failing example based on matplotlib](https://github.com/mueslo/rtd_min_fail). However, this doesn't fail.

My workaround also succeeded (explicitly specifying `matplotlib~=2.2` in `docs/requirements.txt`. So it is definitely related to the way RTD first installs matplotlib 3.x and then 2.x.

**Comment by mueslo** [comment]
@stsewd I belive this qualifies as a bug, not a support request

**Comment by stsewd** [comment]
>This erroneous import behavious is caused by enabling the virtualenv option on readthedocs. So in essence, RTD does not properly isolate virtualenv packages.

Do you mean the install option? I'm guessing some residuals from the previous installation (if I understand correctly you change the versions, right?). If so, you should only need to wipe the environment to resolve that, we can't do that automatically because we don't know what packages are going to be installed, if we cache the virtualenv installation to save resources.

**Comment by stsewd** [comment]
I believe this is a sphinx-galery issue, when the package is installed in rtd they install an additional package https://github.com/sphinx-gallery/sphinx-gallery/blob/29d317b1674a08fc36a4e2ad35e183cdce8f1e39/setup.py#L20-L22, that package has a different version of matplolib https://github.com/mwaskom/seaborn/blob/f0349b1a7f1e022cb1da8b94f2e019f04eeed397/setup.py#L35, I'll try to replicate this locally setting a env variable, but not sure what we can do here.
