### ISSUE TITLE
Failing to build from mkdocs repository though layout respected

### ISSUE THREAD

**Issue by parthi2929** [rtfd/readthedocs.org#4974]
## Details
My local mkdocs build is successful. The docs section is part of my project repository and resides in ```mkdocs``` folder of my repository. When I try to deploy in RTD, I get the following build error.  Kindly help. 

```
ERROR   -  Config value: 'docs_dir'. Error: The 'docs_dir' should not be the parent directory of the config file. Use a child directory instead so that the config file is a sibling of the config file. 
ERROR   -  Config value: 'site_dir'. Error: The 'site_dir' should not be within the 'docs_dir' as this leads to the build directory being copied into itself and duplicate nested files in the 'site_dir'.(site_dir: '/home/docs/checkouts/readthedocs.org/user_builds/intro-to-statistics/checkouts/latest/_build/html', docs_dir: '/home/docs/checkouts/readthedocs.org/user_builds/intro-to-statistics/checkouts/latest') 

Aborted with 2 Configuration Errors!
```

* Read the Docs project URL: https://readthedocs.org/projects/intro-to-statistics/
* Build URL (if applicable): https://readthedocs.org/projects/intro-to-statistics/builds/
* Read the Docs username (if applicable): parthi2929
* Github repository: https://github.com/parthi2929/ud_st101

## Expected Result
The build should be successful, as I have my mkdocs' yml file outside ```docs_dir```. Also I have not uploaded ```site``` directory at all, as my understanding is, that is what RTD would build from ```docs_dir```. 

*A description of what you wanted to happen*
I want the build to be successful and appearance as in local build (Note I also use a custom_theme with additional modifications of RTD theme from Mkdocs, those changes reside in custom_theme in mkdocs folder at same level as ```docs_dir```). My lcoal successful output is as shown below.  
![image](https://user-images.githubusercontent.com/11896263/49694180-2eec0800-fbab-11e8-8dd2-61e45ae4970b.png)

## Actual Result
The error as shown above

**Comment by parthi2929** [comment]
I then tried to place mkdocs.yml in the root directory as per [RTD build instructions for mkdocs](https://docs.readthedocs.io/en/latest/builds.html?highlight=mkdocs.yml#mkdocs). This time also, my local build was successful (yml appropriately updated to reference ```docs_dir``` inside mkdocs folder), but RTD build gives a different error as below. 

```
INFO    -  Cleaning site directory 
INFO    -  Building documentation to directory: /home/docs/checkouts/readthedocs.org/user_builds/intro-to-statistics/checkouts/latest/_build/html 
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/intro-to-statistics/envs/latest/bin/mkdocs", line 11, in <module>
    sys.exit(cli())
  File "/home/docs/checkouts/readthedocs.org/user_builds/intro-to-statistics/envs/latest/local/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/intro-to-statistics/envs/latest/local/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/docs/checkouts/readthedocs.org/user_builds/intro-to-statistics/envs/latest/local/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/docs/checkouts/readthedocs.org/user_builds/intro-to-statistics/envs/latest/local/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/docs/checkouts/readthedocs.org/user_builds/intro-to-statistics/envs/latest/local/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/intro-to-statistics/envs/latest/local/lib/python2.7/site-packages/mkdocs/__main__.py", line 156, in build_command
    ), dirty=not clean)
  File "/home/docs/checkouts/readthedocs.org/user_builds/intro-to-statistics/envs/latest/local/lib/python2.7/site-packages/mkdocs/commands/build.py", line 282, in build
    build_pages(config, dirty=dirty)
  File "/home/docs/checkouts/readthedocs.org/user_builds/intro-to-statistics/envs/latest/local/lib/python2.7/site-packages/mkdocs/commands/build.py", line 229, in build_pages
    build_template(template, env, config, site_navigation)
  File "/home/docs/checkouts/readthedocs.org/user_builds/intro-to-statistics/envs/latest/local/lib/python2.7/site-packages/mkdocs/commands/build.py", line 88, in build_template
    output_content = template.render(context)
  File "/home/docs/checkouts/readthedocs.org/user_builds/intro-to-statistics/envs/latest/local/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/docs/checkouts/readthedocs.org/user_builds/intro-to-statistics/envs/latest/local/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/docs/checkouts/readthedocs.org/user_builds/intro-to-statistics/checkouts/latest/mkdocs/custom_theme/footer.html", line 7, in <module>
    <a href="{{ page.next_page.url|url }}" class="btn btn-neutral float-right" title="{{ page.next_page.title }}">Next <span class="icon icon-circle-arrow-right"></span></a>
jinja2.exceptions.TemplateAssertionError: no filter named 'url'
```

Looks like we cannot use modified RTD theme of mkdocs, while trying to deploy from RTD? Or its still me missing something? Kindly help.

**Comment by stsewd** [comment]
So, we don't have a way of specifying a custom location for mkdocs yet, we only search in the project's root. This feature would be available in the v2 of our config file.

About the second error, what version of mkdocs are you using locally? I believe you already fixed the issue https://readthedocs.org/projects/intro-to-statistics/builds/8245770/ adding a requirements.txt file.

**Comment by parthi2929** [comment]
I am using latest mkdocs 1.0.4, and yes, once I added requirements.txt that got solved. 

yes it would be better if you could also search in sub directories. Looking forward for that feature as that could help organize better the repo.

**Comment by stsewd** [comment]
We already have that feature implemented, but itsn't public yet, here are the future docs https://github.com/rtfd/readthedocs.org/pull/4451/files#diff-33bbde7fca852e881b51aa90f9f86b3fR243

**Comment by humitos** [comment]
@parthi2929 we can enable config V2 for your project. It's still in BETA but you can help us by testing it. Would you like us to enable it in your project so you can specify a different path for `mkdocs.yml`?

**Comment by parthi2929** [comment]
sure, though am novice in these, this way I could contribute something back for amazing work you guys are doing.

**Comment by humitos** [comment]
@parthi2929 done! Please, follow the docs that @stsewd pointed you and use a custom path for your mkdocs.yml file to test how it works and let us know! Thanks!

**Comment by parthi2929** [comment]
Hi, Sorry, I could not test it yet, what is the deadline for this test before we release?

**Comment by stsewd** [comment]
There's not a deadline, you can test it whenever you want :), just keep in mind that the schema will change after #4740 gets merged

**Comment by Zylann** [comment]
I'm new to ReadTheDocs and MkDocs, and I just got the second error you had about `site_dir`. I didnt specify such variable anywhere.

> I am using latest mkdocs 1.0.4, and yes, once I added requirements.txt that got solved.

What is `requirements.txt`? Why would it fix the `site_dir` error, what should I put in it?

**Comment by stsewd** [comment]
> Is specifying requirements.txt necessary due to ReadTheDocs defaulting to an older version otherwise?

Yes, we recommend pinning the mkdocs version, so your build is reproducible outside rtd.
