### ISSUE TITLE
Build fails with undefined filter "url"

### ISSUE THREAD

**Issue by byrnereese** [rtfd/readthedocs.org#4997]
## Details

* Read the Docs project URL: https://github.com/ringcentral/ringcentral-api-docs
* Build URL (if applicable): https://readthedocs.org/projects/ringcentral-api-docs/builds/8270734/
* Read the Docs username (if applicable): byrnereese

## Expected Result

I am trying to create a build for a branch called "bootstrap" in my account. I expect it to build without a problem. 

## Actual Result

I am getting the following error:

```
INFO    -  Cleaning site directory 
INFO    -  Building documentation to directory: /home/docs/checkouts/readthedocs.org/user_builds/ringcentral-api-docs/checkouts/bootstrap/_build/html 
ERROR   -  Error building page quick-start/index.md 
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/ringcentral-api-docs/envs/bootstrap/bin/mkdocs", line 11, in <module>
    sys.exit(cli())
  File "/home/docs/checkouts/readthedocs.org/user_builds/ringcentral-api-docs/envs/bootstrap/local/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ringcentral-api-docs/envs/bootstrap/local/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ringcentral-api-docs/envs/bootstrap/local/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/docs/checkouts/readthedocs.org/user_builds/ringcentral-api-docs/envs/bootstrap/local/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ringcentral-api-docs/envs/bootstrap/local/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ringcentral-api-docs/envs/bootstrap/local/lib/python2.7/site-packages/mkdocs/__main__.py", line 156, in build_command
    ), dirty=not clean)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ringcentral-api-docs/envs/bootstrap/local/lib/python2.7/site-packages/mkdocs/commands/build.py", line 282, in build
    build_pages(config, dirty=dirty)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ringcentral-api-docs/envs/bootstrap/local/lib/python2.7/site-packages/mkdocs/commands/build.py", line 242, in build_pages
    _build_page(page, config, site_navigation, env)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ringcentral-api-docs/envs/bootstrap/local/lib/python2.7/site-packages/mkdocs/commands/build.py", line 158, in _build_page
    output_content = template.render(context)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ringcentral-api-docs/envs/bootstrap/local/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ringcentral-api-docs/envs/bootstrap/local/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ringcentral-api-docs/checkouts/bootstrap/bootstrap4-theme/base.html", line 26, in <module>
    <link href="{{ 'css/bootstrap-custom.min.css'|url }}" rel="stylesheet">
jinja2.exceptions.TemplateAssertionError: no filter named 'url'
```

It says a filter is not found, but I understand the `url` filter to be standard. Is it not included?

**Comment by dojutsu-user** [comment]
I think that adding a `requirements.txt` file will solve the issue.
Related - [#4794 (comment)](https://github.com/rtfd/readthedocs.org/issues/4974#issuecomment-445516423)

**Comment by stsewd** [comment]
Probably you are missing a dependency or using a new version of mkdocs locally as pointed out above

**Comment by byrnereese** [comment]
I can confirm that this fixed my problem.

**Comment by RichardLitt** [comment]
@byrnereese Thanks for following up. Glad we got this fixed!
