### ISSUE TITLE
Local install read the docs

### ISSUE THREAD

**Issue by ilpepe** [rtfd/readthedocs.org#5126]
## Details

* Read the Docs project URL: - 
* Build URL (if applicable): - 
* Read the Docs username (if applicable): - 

## Expected Result
get the server up and running

## Actual Result
```
Traceback (most recent call last):
  File "./manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/checkouts/readthedocs.org/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/checkouts/readthedocs.org/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/checkouts/readthedocs.org/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/checkouts/readthedocs.org/venv/local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 61, in execute
    super(Command, self).execute(*args, **options)
  File "/home/ubuntu/checkouts/readthedocs.org/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/checkouts/readthedocs.org/venv/local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 72, in handle
    if not settings.DEBUG and not settings.ALLOWED_HOSTS:
  File "/home/ubuntu/checkouts/readthedocs.org/venv/local/lib/python2.7/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/home/ubuntu/checkouts/readthedocs.org/venv/local/lib/python2.7/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/ubuntu/checkouts/readthedocs.org/venv/local/lib/python2.7/site-packages/django/conf/__init__.py", line 129, in __init__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
```

declaring a SECRET_KEY in local settings does not help

**Comment by agjohnson** [comment]
You might have luck referring to the Django docs, this is a error stating your settings are not set up correctly and is not a bug with Read the Docs.

**Comment by ilpepe** [comment]
Hi,
I there is some documentation lacking concerning local installs.

E.g.
Do I have to change the dev to base in the manage.py file?
```
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "readthedocs.settings.base")
```
?
What else do I need to change? 

There are two install types mentioned on the readthedocs of RTD:
- one using debain: https://docs.readthedocs.io/en/latest/custom_installs/local_rtd_vm.html#install-rtd which seems to use python 2.7
- https://docs.readthedocs.io/en/latest/install.html, using python3.6.

This is a bit unclear to me.

Reading Django issues, SECRET KEY points towards circular imports of config... I can hardly be the only one having this problem?

**Comment by stsewd** [comment]
The docs for custom installations are maintained for the community, and probably not up to date.
