### ISSUE TITLE
Unable to build RTD docs on local

### ISSUE THREAD

**Issue by dojutsu-user** [rtfd/readthedocs.org#5298]
While building the RTD docs on local, it fails

Command:
```
$ python /home/pikachu/Desktop/rtd/readthedocs.org/user_builds/rtd-test/envs/latest/bin/sphinx-build -T -b readthedocs -d _build/doctrees-readthedocs -D language=en . _build/html
```
```
Running Sphinx v1.7.9

Traceback (most recent call last):
  File "/home/pikachu/Desktop/rtd/readthedocs.org/user_builds/rtd-test/envs/latest/lib/python3.7/site-packages/django/apps/config.py", line 122, in create
    cls = getattr(mod, cls_name)
AttributeError: module 'readthedocs' has no attribute 'notifications'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pikachu/Desktop/rtd/readthedocs.org/user_builds/rtd-test/envs/latest/lib/python3.7/site-packages/sphinx/config.py", line 161, in __init__
    execfile_(filename, config)
  File "/home/pikachu/Desktop/rtd/readthedocs.org/user_builds/rtd-test/envs/latest/lib/python3.7/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "conf.py", line 19, in <module>
    django.setup()
  File "/home/pikachu/Desktop/rtd/readthedocs.org/user_builds/rtd-test/envs/latest/lib/python3.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/pikachu/Desktop/rtd/readthedocs.org/user_builds/rtd-test/envs/latest/lib/python3.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/pikachu/Desktop/rtd/readthedocs.org/user_builds/rtd-test/envs/latest/lib/python3.7/site-packages/django/apps/config.py", line 127, in create
    import_module(entry)
  File "/home/pikachu/Desktop/rtd/readthedocs.org/user_builds/rtd-test/envs/latest/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/pikachu/Desktop/rtd/readthedocs.org/user_builds/rtd-test/checkouts/latest/readthedocs/notifications/__init__.py", line 17, in <module>
    from .notification import Notification, SiteNotification
  File "/home/pikachu/Desktop/rtd/readthedocs.org/user_builds/rtd-test/checkouts/latest/readthedocs/notifications/notification.py", line 14, in <module>
    from .backends import send_notification
  File "/home/pikachu/Desktop/rtd/readthedocs.org/user_builds/rtd-test/checkouts/latest/readthedocs/notifications/backends.py", line 16, in <module>
    from readthedocs.core.utils import send_email
  File "/home/pikachu/Desktop/rtd/readthedocs.org/user_builds/rtd-test/checkouts/latest/readthedocs/core/utils/__init__.py", line 17, in <module>
    from celery import group, chord
  File "/home/pikachu/Desktop/rtd/readthedocs.org/user_builds/rtd-test/envs/latest/lib/python3.7/site-packages/celery/local.py", line 511, in __getattr__
    module = __import__(self._object_origins[name], None, None, [name])
  File "/home/pikachu/Desktop/rtd/readthedocs.org/user_builds/rtd-test/envs/latest/lib/python3.7/site-packages/celery/canvas.py", line 27, in <module>
    from celery.result import GroupResult
  File "/home/pikachu/Desktop/rtd/readthedocs.org/user_builds/rtd-test/envs/latest/lib/python3.7/site-packages/celery/result.py", line 15, in <module>
    from .app import app_or_default
  File "/home/pikachu/Desktop/rtd/readthedocs.org/user_builds/rtd-test/envs/latest/lib/python3.7/site-packages/celery/app/__init__.py", line 10, in <module>
    from .base import Celery
  File "/home/pikachu/Desktop/rtd/readthedocs.org/user_builds/rtd-test/envs/latest/lib/python3.7/site-packages/celery/app/base.py", line 11, in <module>
    from kombu import pools
  File "/home/pikachu/Desktop/rtd/readthedocs.org/user_builds/rtd-test/envs/latest/lib/python3.7/site-packages/kombu/pools.py", line 10, in <module>
    from .messaging import Producer
  File "/home/pikachu/Desktop/rtd/readthedocs.org/user_builds/rtd-test/envs/latest/lib/python3.7/site-packages/kombu/messaging.py", line 7, in <module>
    from .compression import compress
  File "/home/pikachu/Desktop/rtd/readthedocs.org/user_builds/rtd-test/envs/latest/lib/python3.7/site-packages/kombu/compression.py", line 6, in <module>
    import bz2
  File "/usr/local/lib/python3.7/bz2.py", line 19, in <module>
    from _bz2 import BZ2Compressor, BZ2Decompressor
ModuleNotFoundError: No module named '_bz2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pikachu/Desktop/rtd/readthedocs.org/user_builds/rtd-test/envs/latest/lib/python3.7/site-packages/sphinx/cmdline.py", line 303, in main
    args.warningiserror, args.tags, args.verbosity, args.jobs)
  File "/home/pikachu/Desktop/rtd/readthedocs.org/user_builds/rtd-test/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 163, in __init__
    confoverrides or {}, self.tags)
  File "/home/pikachu/Desktop/rtd/readthedocs.org/user_builds/rtd-test/envs/latest/lib/python3.7/site-packages/sphinx/config.py", line 167, in __init__
    raise ConfigError(CONFIG_ERROR % traceback.format_exc())
sphinx.errors.ConfigError: There is a programable error in your configuration file:

Traceback (most recent call last):
  File "/home/pikachu/Desktop/rtd/readthedocs.org/user_builds/rtd-test/envs/latest/lib/python3.7/site-packages/django/apps/config.py", line 122, in create
    cls = getattr(mod, cls_name)
AttributeError: module 'readthedocs' has no attribute 'notifications'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pikachu/Desktop/rtd/readthedocs.org/user_builds/rtd-test/envs/latest/lib/python3.7/site-packages/sphinx/config.py", line 161, in __init__
    execfile_(filename, config)
  File "/home/pikachu/Desktop/rtd/readthedocs.org/user_builds/rtd-test/envs/latest/lib/python3.7/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "conf.py", line 19, in <module>
    django.setup()
  File "/home/pikachu/Desktop/rtd/readthedocs.org/user_builds/rtd-test/envs/latest/lib/python3.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/pikachu/Desktop/rtd/readthedocs.org/user_builds/rtd-test/envs/latest/lib/python3.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/pikachu/Desktop/rtd/readthedocs.org/user_builds/rtd-test/envs/latest/lib/python3.7/site-packages/django/apps/config.py", line 127, in create
    import_module(entry)
  File "/home/pikachu/Desktop/rtd/readthedocs.org/user_builds/rtd-test/envs/latest/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/pikachu/Desktop/rtd/readthedocs.org/user_builds/rtd-test/checkouts/latest/readthedocs/notifications/__init__.py", line 17, in <module>
    from .notification import Notification, SiteNotification
  File "/home/pikachu/Desktop/rtd/readthedocs.org/user_builds/rtd-test/checkouts/latest/readthedocs/notifications/notification.py", line 14, in <module>
    from .backends import send_notification
  File "/home/pikachu/Desktop/rtd/readthedocs.org/user_builds/rtd-test/checkouts/latest/readthedocs/notifications/backends.py", line 16, in <module>
    from readthedocs.core.utils import send_email
  File "/home/pikachu/Desktop/rtd/readthedocs.org/user_builds/rtd-test/checkouts/latest/readthedocs/core/utils/__init__.py", line 17, in <module>
    from celery import group, chord
  File "/home/pikachu/Desktop/rtd/readthedocs.org/user_builds/rtd-test/envs/latest/lib/python3.7/site-packages/celery/local.py", line 511, in __getattr__
    module = __import__(self._object_origins[name], None, None, [name])
  File "/home/pikachu/Desktop/rtd/readthedocs.org/user_builds/rtd-test/envs/latest/lib/python3.7/site-packages/celery/canvas.py", line 27, in <module>
    from celery.result import GroupResult
  File "/home/pikachu/Desktop/rtd/readthedocs.org/user_builds/rtd-test/envs/latest/lib/python3.7/site-packages/celery/result.py", line 15, in <module>
    from .app import app_or_default
  File "/home/pikachu/Desktop/rtd/readthedocs.org/user_builds/rtd-test/envs/latest/lib/python3.7/site-packages/celery/app/__init__.py", line 10, in <module>
    from .base import Celery
  File "/home/pikachu/Desktop/rtd/readthedocs.org/user_builds/rtd-test/envs/latest/lib/python3.7/site-packages/celery/app/base.py", line 11, in <module>
    from kombu import pools
  File "/home/pikachu/Desktop/rtd/readthedocs.org/user_builds/rtd-test/envs/latest/lib/python3.7/site-packages/kombu/pools.py", line 10, in <module>
    from .messaging import Producer
  File "/home/pikachu/Desktop/rtd/readthedocs.org/user_builds/rtd-test/envs/latest/lib/python3.7/site-packages/kombu/messaging.py", line 7, in <module>
    from .compression import compress
  File "/home/pikachu/Desktop/rtd/readthedocs.org/user_builds/rtd-test/envs/latest/lib/python3.7/site-packages/kombu/compression.py", line 6, in <module>
    import bz2
  File "/usr/local/lib/python3.7/bz2.py", line 19, in <module>
    from _bz2 import BZ2Compressor, BZ2Decompressor
ModuleNotFoundError: No module named '_bz2'


Configuration error:
There is a programable error in your configuration file:

Traceback (most recent call last):
  File "/home/pikachu/Desktop/rtd/readthedocs.org/user_builds/rtd-test/envs/latest/lib/python3.7/site-packages/django/apps/config.py", line 122, in create
    cls = getattr(mod, cls_name)
AttributeError: module 'readthedocs' has no attribute 'notifications'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pikachu/Desktop/rtd/readthedocs.org/user_builds/rtd-test/envs/latest/lib/python3.7/site-packages/sphinx/config.py", line 161, in __init__
    execfile_(filename, config)
  File "/home/pikachu/Desktop/rtd/readthedocs.org/user_builds/rtd-test/envs/latest/lib/python3.7/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "conf.py", line 19, in <module>
    django.setup()
  File "/home/pikachu/Desktop/rtd/readthedocs.org/user_builds/rtd-test/envs/latest/lib/python3.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/pikachu/Desktop/rtd/readthedocs.org/user_builds/rtd-test/envs/latest/lib/python3.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/pikachu/Desktop/rtd/readthedocs.org/user_builds/rtd-test/envs/latest/lib/python3.7/site-packages/django/apps/config.py", line 127, in create
    import_module(entry)
  File "/home/pikachu/Desktop/rtd/readthedocs.org/user_builds/rtd-test/envs/latest/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/pikachu/Desktop/rtd/readthedocs.org/user_builds/rtd-test/checkouts/latest/readthedocs/notifications/__init__.py", line 17, in <module>
    from .notification import Notification, SiteNotification
  File "/home/pikachu/Desktop/rtd/readthedocs.org/user_builds/rtd-test/checkouts/latest/readthedocs/notifications/notification.py", line 14, in <module>
    from .backends import send_notification
  File "/home/pikachu/Desktop/rtd/readthedocs.org/user_builds/rtd-test/checkouts/latest/readthedocs/notifications/backends.py", line 16, in <module>
    from readthedocs.core.utils import send_email
  File "/home/pikachu/Desktop/rtd/readthedocs.org/user_builds/rtd-test/checkouts/latest/readthedocs/core/utils/__init__.py", line 17, in <module>
    from celery import group, chord
  File "/home/pikachu/Desktop/rtd/readthedocs.org/user_builds/rtd-test/envs/latest/lib/python3.7/site-packages/celery/local.py", line 511, in __getattr__
    module = __import__(self._object_origins[name], None, None, [name])
  File "/home/pikachu/Desktop/rtd/readthedocs.org/user_builds/rtd-test/envs/latest/lib/python3.7/site-packages/celery/canvas.py", line 27, in <module>
    from celery.result import GroupResult
  File "/home/pikachu/Desktop/rtd/readthedocs.org/user_builds/rtd-test/envs/latest/lib/python3.7/site-packages/celery/result.py", line 15, in <module>
    from .app import app_or_default
  File "/home/pikachu/Desktop/rtd/readthedocs.org/user_builds/rtd-test/envs/latest/lib/python3.7/site-packages/celery/app/__init__.py", line 10, in <module>
    from .base import Celery
  File "/home/pikachu/Desktop/rtd/readthedocs.org/user_builds/rtd-test/envs/latest/lib/python3.7/site-packages/celery/app/base.py", line 11, in <module>
    from kombu import pools
  File "/home/pikachu/Desktop/rtd/readthedocs.org/user_builds/rtd-test/envs/latest/lib/python3.7/site-packages/kombu/pools.py", line 10, in <module>
    from .messaging import Producer
  File "/home/pikachu/Desktop/rtd/readthedocs.org/user_builds/rtd-test/envs/latest/lib/python3.7/site-packages/kombu/messaging.py", line 7, in <module>
    from .compression import compress
  File "/home/pikachu/Desktop/rtd/readthedocs.org/user_builds/rtd-test/envs/latest/lib/python3.7/site-packages/kombu/compression.py", line 6, in <module>
    import bz2
  File "/usr/local/lib/python3.7/bz2.py", line 19, in <module>
    from _bz2 import BZ2Compressor, BZ2Decompressor
ModuleNotFoundError: No module named '_bz2'
```

But when I manually treid importing `_bz2`, it doesn't give me any errors
```python3
>>> import sys
>>> sys.executable
'/usr/local/bin/python3.7'
>>> from _bz2 import BZ2Compressor, BZ2Decompressor
>>> 
```

**Comment by stsewd** [comment]
Did you try building with python 3.6?

**Comment by stsewd** [comment]
Actually our docs are building with python 3.7 https://readthedocs.org/projects/docs/builds/8575726/

**Comment by dojutsu-user** [comment]
@stsewd 
I noticed that. And then I installed python3.7.
But still I'm unable to build it.
Is there any way I can switch back to python3.6 for the docs building?

**Comment by stsewd** [comment]
I just tried with the latest master `make html` builds fine for me.

>  Is there any way I can switch back to python3.6 for the docs building?

I use pyenv to manage different python versions https://github.com/pyenv/pyenv

**Comment by dojutsu-user** [comment]
`make html` fails when I used virtual environment with python3.7 with the following error.
```
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.8.4

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/home/pikachu/Desktop/rtd/python3.7/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 31, in <module>
    from pysqlite2 import dbapi2 as Database
ModuleNotFoundError: No module named 'pysqlite2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pikachu/Desktop/rtd/python3.7/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 33, in <module>
    from sqlite3 import dbapi2 as Database
  File "/usr/local/lib/python3.7/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/lib/python3.7/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pikachu/Desktop/rtd/python3.7/lib/python3.7/site-packages/sphinx/config.py", line 368, in eval_config_file
    execfile_(filename, namespace)
  File "/home/pikachu/Desktop/rtd/python3.7/lib/python3.7/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "/home/pikachu/Desktop/rtd/readthedocs.org/docs/conf.py", line 19, in <module>
    django.setup()
  File "/home/pikachu/Desktop/rtd/python3.7/lib/python3.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/pikachu/Desktop/rtd/python3.7/lib/python3.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/home/pikachu/Desktop/rtd/python3.7/lib/python3.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/pikachu/Desktop/rtd/python3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/pikachu/Desktop/rtd/python3.7/lib/python3.7/site-packages/django/contrib/auth/models.py", line 4, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/home/pikachu/Desktop/rtd/python3.7/lib/python3.7/site-packages/django/contrib/auth/base_user.py", line 52, in <module>
    class AbstractBaseUser(models.Model):
  File "/home/pikachu/Desktop/rtd/python3.7/lib/python3.7/site-packages/django/db/models/base.py", line 124, in __new__
    new_class.add_to_class('_meta', Options(meta, app_label))
  File "/home/pikachu/Desktop/rtd/python3.7/lib/python3.7/site-packages/django/db/models/base.py", line 325, in add_to_class
    value.contribute_to_class(cls, name)
  File "/home/pikachu/Desktop/rtd/python3.7/lib/python3.7/site-packages/django/db/models/options.py", line 214, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "/home/pikachu/Desktop/rtd/python3.7/lib/python3.7/site-packages/django/db/__init__.py", line 33, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "/home/pikachu/Desktop/rtd/python3.7/lib/python3.7/site-packages/django/db/utils.py", line 211, in __getitem__
    backend = load_backend(db['ENGINE'])
  File "/home/pikachu/Desktop/rtd/python3.7/lib/python3.7/site-packages/django/db/utils.py", line 115, in load_backend
    return import_module('%s.base' % backend_name)
  File "/home/pikachu/Desktop/rtd/python3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/pikachu/Desktop/rtd/python3.7/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 35, in <module>
    raise ImproperlyConfigured("Error loading either pysqlite2 or sqlite3 modules (tried in that order): %s" % exc)
django.core.exceptions.ImproperlyConfigured: Error loading either pysqlite2 or sqlite3 modules (tried in that order): No module named '_sqlite3'

Makefile:58: recipe for target 'html' failed
make: *** [html] Error 2
```

and is successful when build with virtual environment with python3.6

**Comment by dojutsu-user** [comment]
I think I have messed up the python versions on my ubuntu :disappointed:

**Comment by stsewd** [comment]
I just built our docs locally with 3.7 and it's working, make sure you updated your requirements, bc we are using sphinx 1.84 now. `pip install -r requirements/local-docs-build.txt`

**Comment by dojutsu-user** [comment]
@stsewd 
I reinstalled my ubuntu again and installed python3.7 again.
Created a virtual environment with it and setup the project.
Now, `make html` is success but I'm still unable to build the docs with RTD.
It fails with this error.

![screenshot from 2019-02-20 00-17-50](https://user-images.githubusercontent.com/29149191/53039345-02a31080-34a5-11e9-8b3c-13cd8d7a2c4c.png)

Log:
```
Internal Server Error: /projects/rtd-test/builds/
Traceback (most recent call last):
  File "/home/pikachu/Desktop/rtd/python3.7/lib/python3.7/site-packages/kombu/utils/objects.py", line 42, in __get__
    return obj.__dict__[self.__name__]
KeyError: 'backend'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pikachu/Desktop/rtd/python3.7/lib/python3.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/pikachu/Desktop/rtd/python3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/pikachu/Desktop/rtd/python3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/pikachu/Desktop/rtd/python3.7/lib/python3.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/pikachu/Desktop/rtd/python3.7/lib/python3.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/pikachu/Desktop/rtd/python3.7/lib/python3.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/pikachu/Desktop/rtd/python3.7/lib/python3.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/pikachu/Desktop/rtd/python3.7/lib/python3.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/home/pikachu/Desktop/rtd/readthedocs.org/readthedocs/builds/views.py", line 67, in post
    version=version,
  File "/home/pikachu/Desktop/rtd/readthedocs.org/readthedocs/core/utils/__init__.py", line 170, in trigger_build
    return (update_docs_task.apply_async(), build)
  File "/home/pikachu/Desktop/rtd/python3.7/lib/python3.7/site-packages/celery/canvas.py", line 221, in apply_async
    return _apply(args, kwargs, **options)
  File "/home/pikachu/Desktop/rtd/python3.7/lib/python3.7/site-packages/celery/app/task.py", line 522, in apply_async
    link=link, link_error=link_error, **options)
  File "/home/pikachu/Desktop/rtd/python3.7/lib/python3.7/site-packages/celery/app/task.py", line 738, in apply
    propagate=throw, app=self._get_app(),
  File "/home/pikachu/Desktop/rtd/python3.7/lib/python3.7/site-packages/celery/app/trace.py", line 288, in build_tracer
    backend = task.backend
  File "/home/pikachu/Desktop/rtd/python3.7/lib/python3.7/site-packages/celery/app/task.py", line 998, in backend
    return self.app.backend
  File "/home/pikachu/Desktop/rtd/python3.7/lib/python3.7/site-packages/kombu/utils/objects.py", line 44, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/home/pikachu/Desktop/rtd/python3.7/lib/python3.7/site-packages/celery/app/base.py", line 1174, in backend
    return self._get_backend()
  File "/home/pikachu/Desktop/rtd/python3.7/lib/python3.7/site-packages/celery/app/base.py", line 892, in _get_backend
    self.loader)
  File "/home/pikachu/Desktop/rtd/python3.7/lib/python3.7/site-packages/celery/app/backends.py", line 68, in by_url
    return by_name(backend, loader), url
  File "/home/pikachu/Desktop/rtd/python3.7/lib/python3.7/site-packages/celery/app/backends.py", line 48, in by_name
    cls = symbol_by_name(backend, aliases)
  File "/home/pikachu/Desktop/rtd/python3.7/lib/python3.7/site-packages/kombu/utils/imports.py", line 56, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "/home/pikachu/Desktop/rtd/python3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/pikachu/Desktop/rtd/python3.7/lib/python3.7/site-packages/celery/backends/redis.py", line 21
    from . import async, base
                      ^
SyntaxError: invalid syntax
[19/Feb/2019 18:49:15] django.request:135[21570]: ERROR Internal Server Error: /projects/rtd-test/builds/
Traceback (most recent call last):
  File "/home/pikachu/Desktop/rtd/python3.7/lib/python3.7/site-packages/kombu/utils/objects.py", line 42, in __get__
    return obj.__dict__[self.__name__]
KeyError: 'backend'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pikachu/Desktop/rtd/python3.7/lib/python3.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/pikachu/Desktop/rtd/python3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/pikachu/Desktop/rtd/python3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/pikachu/Desktop/rtd/python3.7/lib/python3.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/pikachu/Desktop/rtd/python3.7/lib/python3.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/pikachu/Desktop/rtd/python3.7/lib/python3.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/pikachu/Desktop/rtd/python3.7/lib/python3.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/pikachu/Desktop/rtd/python3.7/lib/python3.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/home/pikachu/Desktop/rtd/readthedocs.org/readthedocs/builds/views.py", line 67, in post
    version=version,
  File "/home/pikachu/Desktop/rtd/readthedocs.org/readthedocs/core/utils/__init__.py", line 170, in trigger_build
    return (update_docs_task.apply_async(), build)
  File "/home/pikachu/Desktop/rtd/python3.7/lib/python3.7/site-packages/celery/canvas.py", line 221, in apply_async
    return _apply(args, kwargs, **options)
  File "/home/pikachu/Desktop/rtd/python3.7/lib/python3.7/site-packages/celery/app/task.py", line 522, in apply_async
    link=link, link_error=link_error, **options)
  File "/home/pikachu/Desktop/rtd/python3.7/lib/python3.7/site-packages/celery/app/task.py", line 738, in apply
    propagate=throw, app=self._get_app(),
  File "/home/pikachu/Desktop/rtd/python3.7/lib/python3.7/site-packages/celery/app/trace.py", line 288, in build_tracer
    backend = task.backend
  File "/home/pikachu/Desktop/rtd/python3.7/lib/python3.7/site-packages/celery/app/task.py", line 998, in backend
    return self.app.backend
  File "/home/pikachu/Desktop/rtd/python3.7/lib/python3.7/site-packages/kombu/utils/objects.py", line 44, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/home/pikachu/Desktop/rtd/python3.7/lib/python3.7/site-packages/celery/app/base.py", line 1174, in backend
    return self._get_backend()
  File "/home/pikachu/Desktop/rtd/python3.7/lib/python3.7/site-packages/celery/app/base.py", line 892, in _get_backend
    self.loader)
  File "/home/pikachu/Desktop/rtd/python3.7/lib/python3.7/site-packages/celery/app/backends.py", line 68, in by_url
    return by_name(backend, loader), url
  File "/home/pikachu/Desktop/rtd/python3.7/lib/python3.7/site-packages/celery/app/backends.py", line 48, in by_name
    cls = symbol_by_name(backend, aliases)
  File "/home/pikachu/Desktop/rtd/python3.7/lib/python3.7/site-packages/kombu/utils/imports.py", line 56, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "/home/pikachu/Desktop/rtd/python3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/pikachu/Desktop/rtd/python3.7/lib/python3.7/site-packages/celery/backends/redis.py", line 21
    from . import async, base
                      ^
SyntaxError: invalid syntax
[19/Feb/2019 18:49:15] "POST /projects/rtd-test/builds/ HTTP/1.1" 500 183321
```

I think this is valid, as there were warnings earlier that `async` will become a reserved keyword in python3.7. https://github.com/celery/celery/issues/4849

Can you help me with that?

**Comment by stsewd** [comment]
Oh, runnning the reas the docs instance isn't supported with 3.7 yet, mostly because we need to update celery. #4756

**Comment by dojutsu-user** [comment]
Ohh.. Okay I get it.
Only the python3.7 was needed to install while still running RTD with python3.6
Thanks
