### ISSUE TITLE
Build error #8619059

### ISSUE THREAD

**Issue by Zlopez** [rtfd/readthedocs.org#5331]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/anitya
* Build URL (if applicable): https://readthedocs.org/projects/anitya/builds/8619059/
* Read the Docs username (if applicable):

## Expected Result

Build passed

## Actual Result

Build failed when installing project dependecies
```
Exception:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/anitya/envs/0.15.0/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 179, in main
    status = self.run(options, args)
  File "/home/docs/checkouts/readthedocs.org/user_builds/anitya/envs/0.15.0/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 355, in run
    session=session, autobuilding=True
  File "/home/docs/checkouts/readthedocs.org/user_builds/anitya/envs/0.15.0/lib/python3.7/site-packages/pip/_internal/wheel.py", line 1007, in build
    session=session,
  File "/home/docs/checkouts/readthedocs.org/user_builds/anitya/envs/0.15.0/lib/python3.7/site-packages/pip/_internal/download.py", line 865, in unpack_url
    unpack_file_url(link, location, download_dir, hashes=hashes)
  File "/home/docs/checkouts/readthedocs.org/user_builds/anitya/envs/0.15.0/lib/python3.7/site-packages/pip/_internal/download.py", line 763, in unpack_file_url
    unpack_file(from_path, location, content_type, link)
  File "/home/docs/checkouts/readthedocs.org/user_builds/anitya/envs/0.15.0/lib/python3.7/site-packages/pip/_internal/utils/misc.py", line 626, in unpack_file
    flatten=not filename.endswith('.whl')
  File "/home/docs/checkouts/readthedocs.org/user_builds/anitya/envs/0.15.0/lib/python3.7/site-packages/pip/_internal/utils/misc.py", line 522, in unzip_file
    shutil.copyfileobj(fp, destfp)
  File "/home/docs/checkouts/readthedocs.org/user_builds/anitya/envs/0.15.0/lib/python3.7/shutil.py", line 79, in copyfileobj
    buf = fsrc.read(length)
  File "/home/docs/.pyenv/versions/3.7.1/lib/python3.7/zipfile.py", line 899, in read
    data = self._read1(n)
  File "/home/docs/.pyenv/versions/3.7.1/lib/python3.7/zipfile.py", line 967, in _read1
    data += self._read2(n - len(data))
  File "/home/docs/.pyenv/versions/3.7.1/lib/python3.7/zipfile.py", line 1002, in _read2
    raise EOFError
EOFError
```

**Comment by humitos** [comment]
This need a little more research since I'm not able to reproduce the problem locally yet.

I saw this error before produced because of a network issue or similar where the zip file was corrupted.

I just triggered `latest` version in your project and it did build.

**Comment by Zlopez** [comment]
Thanks
I also tried to build it locally and didn't encountered any issue. If the build is now working I think we can close this issue.
I see that there is still one issue in https://readthedocs.org/projects/anitya/builds/8625660/, but this looks like some missing dependency.
