### ISSUE TITLE
Setting Up Apache Solr on Local Instance

### ISSUE THREAD

**Issue by jacobabennett** [rtfd/readthedocs.org#891]
I am currently in the process of installing a local version of readthedocs.org following the installation instructions http://read-the-docs.readthedocs.org/en/latest/install.html#solr-search-setup.

However, while trying to install and setup solr for search using the following command -- to generate the schema.xml file.

    ./manage.py build_solr_schema > $SOLR_PATH/solr/conf/schema.xml

However, instead of generating the schema.xml file, I get the following error.
```
Traceback (most recent call last):
   File "./manage.py", line 11, in <module>
   execute_from_command_line(sys.argv)
  File "/home/***/ford-env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
  utility.execute()
  File "/home/***/ford-env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/***/ford-env/local/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/***/ford-env/local/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/home/***/ford-env/local/lib/python2.7/site-packages/haystack/management/commands/build_solr_schema.py", line 26, in handle
    schema_xml = self.build_template(using=using)
  File "/home/***/ford-env/local/lib/python2.7/site-packages/haystack/management/commands/build_solr_schema.py", line 52, in build_template
    c = self.build_context(using=using)
  File "/home/***/ford-env/local/lib/python2.7/site-packages/haystack/management/commands/build_solr_schema.py", line 38, in build_context
    raise ImproperlyConfigured("'%s' isn't configured as a SolrEngine)." % backend.connection_alias)
```

Am I missing a step? I can get my local rtd to run fine, just sans search functionality. Any help is appreciated.

I also posted this a couple of days ago as a stackoverflow question http://stackoverflow.com/questions/25333255/setting-up-apache-solr-on-local-instance-of-readthedocs-org

**Comment by ericholscher** [comment]
Solr is no longer supported. We have moved to Elastic Search.
