### ISSUE TITLE
Relative paths in requirements don't seem to work

### ISSUE THREAD

**Issue by stuaxo** [rtfd/readthedocs.org#892]
In my project we have a sphinx extension .. my requirements file points at it like this:

./sphinxcontrib_shoebot

Locally I have pip 1.5.6 and installing this requirements flle works correctly.
On rtd I get this error:

```
requirements
-----

Exception:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/shoebot-test-rtd/envs/readthedocs/local/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/home/docs/checkouts/readthedocs.org/user_builds/shoebot-test-rtd/envs/readthedocs/local/lib/python2.7/site-packages/pip/commands/install.py", line 262, in run
    for req in parse_requirements(filename, finder=finder, options=options, session=session):
  File "/home/docs/checkouts/readthedocs.org/user_builds/shoebot-test-rtd/envs/readthedocs/local/lib/python2.7/site-packages/pip/req.py", line 1631, in parse_requirements
    req = InstallRequirement.from_line(line, comes_from, prereleases=getattr(options, "pre", None))
  File "/home/docs/checkouts/readthedocs.org/user_builds/shoebot-test-rtd/envs/readthedocs/local/lib/python2.7/site-packages/pip/req.py", line 172, in from_line
    return cls(req, comes_from, url=url, prereleases=prereleases)
  File "/home/docs/checkouts/readthedocs.org/user_builds/shoebot-test-rtd/envs/readthedocs/local/lib/python2.7/site-packages/pip/req.py", line 70, in __init__
    req = pkg_resources.Requirement.parse(req)
  File "/home/docs/checkouts/readthedocs.org/user_builds/shoebot-test-rtd/envs/readthedocs/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources.py", line 2667, in parse
    reqs = list(parse_requirements(s))
  File "/home/docs/checkouts/readthedocs.org/user_builds/shoebot-test-rtd/envs/readthedocs/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources.py", line 2605, in parse_requirements
    line, p, specs = scan_list(VERSION,LINE_END,line,p,(1,2),"version spec")
  File "/home/docs/checkouts/readthedocs.org/user_builds/shoebot-test-rtd/envs/readthedocs/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources.py", line 2573, in scan_list
    raise ValueError("Expected "+item_name+" in",line,"at",line[p:])
ValueError: ('Expected version spec in', './sphinxcontrib_shoebot', 'at', '/sphinxcontrib_shoebot')

Storing debug log for failure in /home/docs/.pip/pip.log
```

https://readthedocs.org/builds/shoebot-test-rtd/1610799/

**Comment by ericholscher** [comment]
Seems like #890 is the main issue here, closing this one.
