### ISSUE TITLE
Build fails with non-informative traceback from subprocess

### ISSUE THREAD

**Issue by cdeil** [rtfd/readthedocs.org#894]
I think this is the same issue as #627 from January.

It happened to the PDF build for me today after I wiped my project earlier today:
https://readthedocs.org/builds/gammapy/1615772/

The only error message displayed is this which doesn't give me any clue what the problem is or what I have to do to fix it:
```
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/readthedocs/projects/utils.py", line 85, in run
    stderr=subprocess.PIPE, env=environment)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by ericholscher** [comment]
Closing this, but in general we're working to fix the build system so these issues won't happen anymore
