### ISSUE TITLE
ERROR: non-ASCII filename not supported on this filesystem

### ISSUE THREAD

**Issue by sirgazil** [rtfd/readthedocs.org#958]
I'm trying to build a document that includes filenames and directories in Japanese in the `_static` directory, but the HTML build fails.
## Steps to reproduce
1. Go to kanary.rtfd.org
2. Go to the project "Builds" page
3. Click the "Build version:" button
## Expected Behavior
- The Recent builds list in the project "Builds" page should display the latest build as **Passed version latest (html)**.
- Going to http://kanary.rtfd.org/ should show the latest HTML build.
## Unexpected Behavior
- The Recent builds list in the project "Builds" page displays the latest build as **Failed version latest (html)**.
- Going to http://kanary.rtfd.org/ shows an old HTML build.

The HTML build error details are available in https://readthedocs.org/builds/kanary/1734409/ . The following is a summary:

```
ひ:: ERROR: non-ASCII filename not supported on this filesystem encoding 'ANSI_X3.4-1968', skipped.

Traceback (most recent call last):
  File "/home/docs/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 254, in main
    app.build(force_all, filenames)
  File "/home/docs/local/lib/python2.7/site-packages/sphinx/application.py", line 212, in build
    self.builder.build_update()
  File "/home/docs/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 214, in build_update
    'out of date' % len(to_build))
  File "/home/docs/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 279, in build
    self.finish()
  File "/home/docs/local/lib/python2.7/site-packages/sphinx/builders/html.py", line 482, in finish
    self.copy_static_files()
  File "/home/docs/local/lib/python2.7/site-packages/sphinx/builders/html.py", line 595, in copy_static_files
    ctx, exclude_matchers=matchers)
  File "/home/docs/local/lib/python2.7/site-packages/sphinx/util/__init__.py", line 171, in copy_static_entry
    exclude_matchers=exclude_matchers)
  File "/home/docs/local/lib/python2.7/site-packages/sphinx/util/__init__.py", line 171, in copy_static_entry
    exclude_matchers=exclude_matchers)
  File "/home/docs/local/lib/python2.7/site-packages/sphinx/util/__init__.py", line 167, in copy_static_entry
    if path.isdir(path.join(source, entry)):
  File "/home/docs/lib/python2.7/posixpath.py", line 80, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe3 in position 1: ordinal not in range(128)

Encoding error:
'ascii' codec can't decode byte 0xe3 in position 1: ordinal not in range(128)
The full traceback has been saved in /tmp/sphinx-err-W5Jvn4.log, if you want to report the issue to the developers.
```

**Comment by ericholscher** [comment]
Believe this was fixed.

**Comment by atytsky** [comment]
Now i have the same problem when I'm trying to build a document that includes filenames in Russian.

For example - https://readthedocs.org/projects/diadocsdk-1c/builds/3388391/

**Comment by agjohnson** [comment]
This may be due to our new builder backeds, reopening.

**Comment by wdv4758h** [comment]
I also encounter similar problem. Any clue ? or I can try to fix it with the traceback I get. This is a big problem to me.

```
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/wdv4758h-notes/envs/latest/lib/python3.4/site-packages/sphinx/cmdline.py", line 245, in main
    app.build(opts.force_all, filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/wdv4758h-notes/envs/latest/lib/python3.4/site-packages/sphinx/application.py", line 264, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/wdv4758h-notes/envs/latest/lib/python3.4/site-packages/sphinx/builders/__init__.py", line 245, in build_update
    'out of date' % len(to_build))
  File "/home/docs/checkouts/readthedocs.org/user_builds/wdv4758h-notes/envs/latest/lib/python3.4/site-packages/sphinx/builders/__init__.py", line 259, in build
    self.doctreedir, self.app))
  File "/home/docs/checkouts/readthedocs.org/user_builds/wdv4758h-notes/envs/latest/lib/python3.4/site-packages/sphinx/environment.py", line 618, in update
    self._read_serial(docnames, app)
  File "/home/docs/checkouts/readthedocs.org/user_builds/wdv4758h-notes/envs/latest/lib/python3.4/site-packages/sphinx/environment.py", line 638, in _read_serial
    self.read_doc(docname, app)
  File "/home/docs/checkouts/readthedocs.org/user_builds/wdv4758h-notes/envs/latest/lib/python3.4/site-packages/sphinx/environment.py", line 797, in read_doc
    self.process_images(docname, doctree)
  File "/home/docs/checkouts/readthedocs.org/user_builds/wdv4758h-notes/envs/latest/lib/python3.4/site-packages/sphinx/environment.py", line 1000, in process_images
    if not os.access(path.join(self.srcdir, imgpath), os.R_OK):
UnicodeEncodeError: 'ascii' codec can't encode characters in position 100-103: ordinal not in range(128)

Encoding error:
'ascii' codec can't encode characters in position 100-103: ordinal not in range(128)
The full traceback has been saved in /tmp/sphinx-err-guzhkhnm.log, if you want to report the issue to the developers.
```

**Comment by berkerpeksag** [comment]
I think https://github.com/rtfd/readthedocs-docker-images/pull/12 will fix this too.

**Comment by wdv4758h** [comment]
Has it already deployed ?

**Comment by humitos** [comment]
@wdv4758h hi, what's you project URL on RTD? are you still having this issue with unicode name files? The `kanary` project doesn't exist anymore and `diadocsdk-1c-docs` has only one unicode filename and it's not being used to build the documentation.

**Comment by wdv4758h** [comment]
@humitos No, I don't think I still having this issue.

Actually, I haven't use readthedocs for a long time. My project is using CI with Sphinx to build now.

And I just check the readthedocs of my project, it doesn't show that problem anymore. It still fail for some reason I can't see, though. Maybe it needs some modification.

**Comment by humitos** [comment]
I just tried this with `diadocsdk-1c-docs` project in my local instance using `build:2.0` docker image by renaming two different files and adding them to the toctree and it worked.

Here is the diff applied in their project to test this:

```diff
diff --git a/docs/source/Organization.rst "b/docs/source/Organizaci\303\263n.rst"
similarity index 100%
rename from docs/source/Organization.rst
rename to "docs/source/Organizaci\303\263n.rst"
diff --git a/docs/source/index.rst b/docs/source/index.rst
index 08f1665..8d1bcfb 100644
--- a/docs/source/index.rst
+++ b/docs/source/index.rst
@@ -13,6 +13,9 @@ AddIn Diadoc API - внешняя компонента, предназначен
    Примеры использования<Examples>  
    Ссылки для скачивания <Downloads>  
 
+   официальный <официальный>
+   Organización <Organización>
+
 .. toctree::
    :name: methods
    :maxdepth: 1
diff --git a/docs/source/Official.rst "b/docs/source/\320\276\321\204\320\270\321\206\320\270\320\260\320\273\321\214\320\275\321\213\320\271.rst"
similarity index 100%
rename from docs/source/Official.rst
rename to "docs/source/\320\276\321\204\320\270\321\206\320\270\320\260\320\273\321\214\320\275\321\213\320\271.rst"
```

Closing issue since it's solved. Feel free to re-open if you find something else.
