### ISSUE TITLE
json error when loaddata test_data with elasticsearch backend

### ISSUE THREAD

**Issue by tdewolf** [rtfd/readthedocs.org#981]
What I did: 
Install RTD according procedure on http://read-the-docs.readthedocs.org/en/latest/install.html until
"syncdb" and "migrate", included.
Then install elasticsearch 0.9.10, install plugins elasticsearch/marvel/latest and elasticsearch/elasticsearch-analysis-icu/2.0.0 and run elasticsearch 
Execute in rtd: ./manage loaddata test_data

What I get:
```(venv)thomas@gitserver:~/venv/sources/readthedocs.org/readthedocs$ ./manage.py loaddata test_data
[20/Oct/2014 06:42:54] INFO [requests.packages.urllib3.connectionpool:180] Starting new HTTP connection (1): 127.0.0.1
[20/Oct/2014 06:42:56] ERROR [celery_haystack.tasks.CeleryHaystackSignalHandler:150] <User: thomas> is not JSON serializable
Traceback (most recent call last):
  File "/home/thomas/venv/local/lib/python2.7/site-packages/celery_haystack/tasks.py", line 148, in run
    current_index.update_object(instance, **handler_options)
  File "/home/thomas/venv/local/lib/python2.7/site-packages/haystack/indexes.py", line 274, in update_object
    backend.update(self, [instance])
  File "/home/thomas/venv/local/lib/python2.7/site-packages/haystack/backends/elasticsearch_backend.py", line 183, in update
    self.conn.bulk_index(self.index_name, 'modelresult', prepped_docs, id_field=ID)
  File "/home/thomas/venv/local/lib/python2.7/site-packages/pyelasticsearch/client.py", line 96, in decorate
    return func(*args, query_params=query_params, **kwargs)
  File "/home/thomas/venv/local/lib/python2.7/site-packages/pyelasticsearch/client.py", line 381, in bulk_index
    body_bits.append(self._encode_json(doc))
  File "/home/thomas/venv/local/lib/python2.7/site-packages/pyelasticsearch/client.py", line 275, in _encode_json
    return json.dumps(value, cls=self.json_encoder, use_decimal=True)
  File "/home/thomas/venv/local/lib/python2.7/site-packages/simplejson/__init__.py", line 296, in dumps
    **kw).encode(obj)
  File "/home/thomas/venv/local/lib/python2.7/site-packages/simplejson/encoder.py", line 226, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/thomas/venv/local/lib/python2.7/site-packages/simplejson/encoder.py", line 296, in iterencode
    return _iterencode(o, 0)
  File "/home/thomas/venv/local/lib/python2.7/site-packages/pyelasticsearch/client.py", line 1009, in default
    return super(JsonEncoder, self).default(value)
  File "/home/thomas/venv/local/lib/python2.7/site-packages/simplejson/encoder.py", line 202, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <User: thomas> is not JSON serializable```

**Comment by ericholscher** [comment]
Is this still an issue? We've had a number of issues w/ ES that will hopefully be solved by the recent upgrade to 1.5.

**Comment by tdewolf** [comment]
will have to retest it. I'll let you know asap.

**Comment by tdewolf** [comment]
No longer an issue when using ES 1.5.0
